queue: API 定义
gotomicro/ekit pull request #109
Opened 2022-10-06 04:23 UTC by flycash

2022-10-06 04:27 UTC, flycash commented
在这里我只是简单定义了  API，并且区分了 Queue 和 BlockingQueue。

目前来看，BlockingQueue 和 Queue 并不是一种包含或者继承关系，而是一种平等的关系。也就是说，一个队列没有办法既是 Queue，又是 BlockingQueue。

如果用户需要将一个 Queue 转化为 BlockingQueue 或者反过来，那么他们可以考虑使用装饰器模式（或者我们提供）。

方法采用的是 Enqueue/Dequeue 两个，它很清晰。但是对于一些英语不太好的来说，可能难以想到。

另外一方面，Put/Get 也是一个比较好的选择，但是我考虑到部分队列是需要提供随机索引功能的，也就是：
```go
Get(index i)
```
相比之下，Enqueue 和 Dequeue 的语义更加直接

2022-10-06 04:51 UTC, longyue0521 commented on queue/types.go
> +	Enqueue(ctx context.Context, t T) error
我想是不是可以再精确描述一下Enqueue/Enqueue的spec

Enqueue如果队列满了,调用者会被阻塞,直到队列有空间可以存放t T,存入t并返回;或者ctx超时,此时返回的error为ctx.Err()
Dequeue如果此时队列里面没有元素，那么调用者会被阻塞，直到队列中有元素可以返回;或者ctx 超时,此时返回的error为ctx.Err()

我写的可能也准确 就是想用户看API Spec就可以知道想要的,不用翻代码看实现,类比于Go官方标准库中context.Context接口.

2022-10-08 04:42 UTC, longyue0521 approved these changes

2022-10-08 04:47 UTC, flycash commented
@longyue0521 再看看

2022-10-08 04:58 UTC, longyue0521 requested changes

2022-10-08 04:58 UTC, longyue0521 commented on queue/types.go
> +	// 在超时或者调用者主动 cancel 的情况下，所有的实现都必须返回 ctx。
在超时或者调用者主动 cancel 的情况下，所有实现返回的error必须是ctx.Err()或包装(wrap)过ctx.Err()的error

2022-10-08 04:58 UTC, longyue0521 commented on queue/types.go
> +	// 在超时或者调用者主动 cancel 的情况下，所有的实现都必须返回 ctx。
同上

2022-10-08 06:27 UTC, flyhigher139 commented
我在issue #103 里评论的发的队列和阻塞队列的设计可以么？

我觉得把阻塞队列视为队列的子类，问题也不大：
BlockingQueue，就是在Queue的基础上，增加了capacity，然后在size为0或capacity时，有阻塞行为

所以阻塞队列也支持队列的行为：
用Queue的出队入队方法操作BlockingQueue，在边界处返回nil
用BlockingQueue的出队入队方法操作BlockingQueue，在非边界处与Queue行为一致

2022-10-08 07:31 UTC, flycash commented
> 我在issue #103 里评论的发的队列和阻塞队列的设计可以么？
> 
> 我觉得把阻塞队列视为队列的子类，问题也不大： BlockingQueue，就是在Queue的基础上，增加了capacity，然后在size为0或capacity时，有阻塞行为
> 
> 所以阻塞队列也支持队列的行为： 用Queue的出队入队方法操作BlockingQueue，在边界处返回nil 用BlockingQueue的出队入队方法操作BlockingQueue，在非边界处与Queue行为一致

最开始我就是觉得从接口的角度就是这样。但是问题是，需要传递一个 context.Context 来作为参数。

不能在 Queue 创建的时候指定超时，因为你可以预期的是一个队列会在很多个地方用，那么不是所有的地方都用同一个超时。更加重要的是，参数传递 context.Context 才能放进去链路里面做整体控制

2022-10-08 07:59 UTC, flyhigher139 commented
> > 我在issue #103 里评论的发的队列和阻塞队列的设计可以么？
> > 我觉得把阻塞队列视为队列的子类，问题也不大： BlockingQueue，就是在Queue的基础上，增加了capacity，然后在size为0或capacity时，有阻塞行为
> > 所以阻塞队列也支持队列的行为： 用Queue的出队入队方法操作BlockingQueue，在边界处返回nil 用BlockingQueue的出队入队方法操作BlockingQueue，在非边界处与Queue行为一致
> 
> 最开始我就是觉得从接口的角度就是这样。但是问题是，需要传递一个 context.Context 来作为参数。
> 
> 不能在 Queue 创建的时候指定超时，因为你可以预期的是一个队列会在很多个地方用，那么不是所有的地方都用同一个超时。更加重要的是，参数传递 context.Context 才能放进去链路里面做整体控制

我设计的那个，也是在阻塞出入队的函数上有context.Context参数，只不过把常规queue也组合进去了，阻塞和不阻塞的出入队方法签名不同，既允许用户用非阻塞的方式出入队，也可以用阻塞的方法出入队。

老师是觉得这样多余了么，阻塞队列就只让用户在边界操作上阻塞？

2022-10-08 08:25 UTC, flycash commented
这个阻塞与否应该跟是不是边界没什么关系？

你可以写个伪代码？

2022-10-08 10:24 UTC, longyue0521 commented
> > > 我在issue #103 里评论的发的队列和阻塞队列的设计可以么？
> > > 我觉得把阻塞队列视为队列的子类，问题也不大： BlockingQueue，就是在Queue的基础上，增加了capacity，然后在size为0或capacity时，有阻塞行为
> > > 所以阻塞队列也支持队列的行为： 用Queue的出队入队方法操作BlockingQueue，在边界处返回nil 用BlockingQueue的出队入队方法操作BlockingQueue，在非边界处与Queue行为一致
> > 
> > 
> > 最开始我就是觉得从接口的角度就是这样。但是问题是，需要传递一个 context.Context 来作为参数。
> > 不能在 Queue 创建的时候指定超时，因为你可以预期的是一个队列会在很多个地方用，那么不是所有的地方都用同一个超时。更加重要的是，参数传递 context.Context 才能放进去链路里面做整体控制
> 
> 我设计的那个，也是在阻塞出入队的函数上有context.Context参数，只不过把常规queue也组合进去了，阻塞和不阻塞的出入队方法签名不同，既允许用户用非阻塞的方式出入队，也可以用阻塞的方法出入队。
> 
> 老师是觉得这样多余了么，阻塞队列就只让用户在边界操作上阻塞？

这种将非阻塞和阻塞出入队API混合的方式很让人困惑,使用者容易犯错,实现者不好实现

1. 从使用者角度,创建了BlockingQueue,意味着我知道自己要用阻塞API用你的话说就是边界情况阻塞,非边界情况与Queue处理是一样的,为什么还要提供非阻塞的API?要用非阻塞API,应该创建Queue而不是BlockingQueue! 如果是为了兼容中途需要从Queue变为BlockingQueue或反过来那么显示使用`NewBlockingQueueFrom(queue)`和`NewQueueFrom(blockingQueue)`完成转换的可读性更高更能表明意图.
2. 从使用者和实现者角度,如果混合调用阻塞和非阻塞API回发生什么?比如,协程1和2阻塞在出队方法上,这时队列中有元素入队,同一时刻协程3调用非阻塞出队API,请问这个元素给谁? (Queue中其他非阻塞方法也面临同样的问题),请问实现者要不要在API doc中描述清楚这些“未定义”的情况?使用者在用之前是不是得写个测试测测这种情况对当前业务有什么影响?

从实现的角度出发,BlockingQueue确实可以认为是Queue的子类,但从设计和使用的角度,在满足需求的前提下,API的简洁、易用且不容易用错更重要,因此BlockingQueue可以不是Queue的子类.

2022-10-08 10:28 UTC, longyue0521 commented on queue/types.go
> +	Dequeue(ctx context.Context) (T, error)
是否考虑在BlockingQueue和Queue中加入Size/Length()方法?

2022-10-08 10:40 UTC, flycash commented on queue/types.go
> +	Dequeue(ctx context.Context) (T, error)
暂时不打算加，我要先观望一下……类似的方法还有别 Peek，就是返回队首，但是队首还留在队列中；以及遍历的方法。总体上来说，暂时先看看 Enqueue 和 Dequeue。

=。=主要就是，我也只需要 Enqueue 和 Dequeue

2022-10-08 10:40 UTC, flycash commented
> > > > 我在issue #103 里评论的发的队列和阻塞队列的设计可以么？
> > > > 我觉得把阻塞队列视为队列的子类，问题也不大： BlockingQueue，就是在Queue的基础上，增加了capacity，然后在size为0或capacity时，有阻塞行为
> > > > 所以阻塞队列也支持队列的行为： 用Queue的出队入队方法操作BlockingQueue，在边界处返回nil 用BlockingQueue的出队入队方法操作BlockingQueue，在非边界处与Queue行为一致
> > > 
> > > 
> > > 最开始我就是觉得从接口的角度就是这样。但是问题是，需要传递一个 context.Context 来作为参数。
> > > 不能在 Queue 创建的时候指定超时，因为你可以预期的是一个队列会在很多个地方用，那么不是所有的地方都用同一个超时。更加重要的是，参数传递 context.Context 才能放进去链路里面做整体控制
> > 
> > 
> > 我设计的那个，也是在阻塞出入队的函数上有context.Context参数，只不过把常规queue也组合进去了，阻塞和不阻塞的出入队方法签名不同，既允许用户用非阻塞的方式出入队，也可以用阻塞的方法出入队。
> > 老师是觉得这样多余了么，阻塞队列就只让用户在边界操作上阻塞？
> 
> 这种将非阻塞和阻塞出入队API混合的方式很让人困惑,使用者容易犯错,实现者不好实现
> 
> 1. 从使用者角度,创建了BlockingQueue,意味着我知道自己要用阻塞API用你的话说就是边界情况阻塞,非边界情况与Queue处理是一样的,为什么还要提供非阻塞的API?要用非阻塞API,应该创建Queue而不是BlockingQueue! 如果是为了兼容中途需要从Queue变为BlockingQueue或反过来那么显示使用`NewBlockingQueueFrom(queue)`和`NewQueueFrom(blockingQueue)`完成转换的可读性更高更能表明意图.
> 2. 从使用者和实现者角度,如果混合调用阻塞和非阻塞API回发生什么?比如,协程1和2阻塞在出队方法上,这时队列中有元素入队,同一时刻协程3调用非阻塞出队API,请问这个元素给谁? (Queue中其他非阻塞方法也面临同样的问题),请问实现者要不要在API doc中描述清楚这些“未定义”的情况?使用者在用之前是不是得写个测试测测这种情况对当前业务有什么影响?
> 
> 从实现的角度出发,BlockingQueue确实可以认为是Queue的子类,但从设计和使用的角度,在满足需求的前提下,API的简洁、易用且不容易用错更重要,因此BlockingQueue可以不是Queue的子类.

行，那么我们就保持这种 API，后面相互装换的可以考虑提供装饰器啥的

2022-10-08 11:14 UTC, flyhigher139 commented
> > > > 我在issue #103 里评论的发的队列和阻塞队列的设计可以么？
> > > > 我觉得把阻塞队列视为队列的子类，问题也不大： BlockingQueue，就是在Queue的基础上，增加了capacity，然后在size为0或capacity时，有阻塞行为
> > > > 所以阻塞队列也支持队列的行为： 用Queue的出队入队方法操作BlockingQueue，在边界处返回nil 用BlockingQueue的出队入队方法操作BlockingQueue，在非边界处与Queue行为一致
> > > 
> > > 
> > > 最开始我就是觉得从接口的角度就是这样。但是问题是，需要传递一个 context.Context 来作为参数。
> > > 不能在 Queue 创建的时候指定超时，因为你可以预期的是一个队列会在很多个地方用，那么不是所有的地方都用同一个超时。更加重要的是，参数传递 context.Context 才能放进去链路里面做整体控制
> > 
> > 
> > 我设计的那个，也是在阻塞出入队的函数上有context.Context参数，只不过把常规queue也组合进去了，阻塞和不阻塞的出入队方法签名不同，既允许用户用非阻塞的方式出入队，也可以用阻塞的方法出入队。
> > 老师是觉得这样多余了么，阻塞队列就只让用户在边界操作上阻塞？
> 
> 这种将非阻塞和阻塞出入队API混合的方式很让人困惑,使用者容易犯错,实现者不好实现
> 
> 1. 从使用者角度,创建了BlockingQueue,意味着我知道自己要用阻塞API用你的话说就是边界情况阻塞,非边界情况与Queue处理是一样的,为什么还要提供非阻塞的API?要用非阻塞API,应该创建Queue而不是BlockingQueue! 如果是为了兼容中途需要从Queue变为BlockingQueue或反过来那么显示使用`NewBlockingQueueFrom(queue)`和`NewQueueFrom(blockingQueue)`完成转换的可读性更高更能表明意图.
> 2. 从使用者和实现者角度,如果混合调用阻塞和非阻塞API回发生什么?比如,协程1和2阻塞在出队方法上,这时队列中有元素入队,同一时刻协程3调用非阻塞出队API,请问这个元素给谁? (Queue中其他非阻塞方法也面临同样的问题),请问实现者要不要在API doc中描述清楚这些“未定义”的情况?使用者在用之前是不是得写个测试测测这种情况对当前业务有什么影响?
> 
> 从实现的角度出发,BlockingQueue确实可以认为是Queue的子类,但从设计和使用的角度,在满足需求的前提下,API的简洁、易用且不容易用错更重要,因此BlockingQueue可以不是Queue的子类.

@longyue0521 
如果是保持行为尽量单一，去掉非阻塞出入队的操作没问题。

不过下面1和2的补充不合适。在BlockingQueue里，无论阻塞还是非阻塞出入队，都要做成线程安全的，阻塞出入队，在边界处会阻塞等待，一直到满足条件被唤醒继续；而非阻塞的出入队，是在边界处直接返回false或nil，不用实现阻塞等待机制。

我之所以会把非阻塞出入队的行为也加上去，是考虑，BlockingQueue首先是线程安全Queue，所以线程安全的出入队操作放出来无可厚非，如果想缩减BlockingQueue的行为，去掉非阻塞出入队，也无可厚非

2022-10-08 11:36 UTC, flycash commented
我赞同就是用户需要知道自己用的是阻塞队列，还是普通队列；而且我也认为，不太存在什么场景是用户需要在阻塞队列和非阻塞队列中转换的。

用户如果传入一个过期时间是过去的 context，那么就相当于立刻尝试从队列里面拿出来一个元素了，也就是接近普通队列了。

不过还是不建议用户这种用法。

2022-10-08 11:38 UTC, flycash commented
什么时候阻塞应该跟在不在边界没什么关系，纯粹是实现的事情。另外我这里说的队首，只是一般逻辑上的队首。在优先级队列里面这个队首的概念就被弱化了。例如说，我完全可以设计一个极小的优先级队列，每次取元素，我都是遍历，也是可以的。但是这并不妨碍我依旧阻塞掉调用者

2022-10-08 13:43 UTC, longyue0521 commented
@flyhigher139

> 不过下面1和2的补充不合适。在BlockingQueue里，无论阻塞还是非阻塞出入队，都要做成线程安全的，阻塞出入队，在边界处会阻塞等待，一直到满足条件被唤醒继续；而非阻塞的出入队，是在边界处直接返回false或nil，不用实现阻塞等待机制。

> 我之所以会把非阻塞出入队的行为也加上去，是考虑，BlockingQueue首先是线程安全Queue，所以线程安全的出入队操作放出来无可厚非，如果想缩减BlockingQueue的行为，去掉非阻塞出入队，也无可厚非

`BlockingQueue首先是线程安全Queue，所以线程安全的出入队操作放出来无可厚非`你这里强调了线程安全,我认为这种从**实现角度**建立起Queue接口与BlockingQueue接口之间的“继承”关系是不合适的.接口之间建立关系(耦合)应该基于抽象/逻辑语义而非实现细节,Queue接口的实现类既可以是线程安全的也可以不是,BlockingQueue也一样只是当前需求中非线程安全的阻塞队列实现出来没意义而已.当然,如果你设计的Queue接口spec要求其实现类必须是线程安全的,那么上面的关系建立是可以的.

其实可以提供一个ThreadSafeBlockingQueue实现类,同时实现Queue接口和BlockingQueue接口(不组合Queue接口),来达到你现在在接口层面要实现的效果.

另外,我提出的混合调用阻塞与非阻塞API的问题,与线程安全与否没关系,即便实现了线程安全,问题依然存在——相同功能(出队/入队),阻塞API与非阻塞API的优先级问题及在各种场景下都要维持这个优先级的问题. 你可以将代码实现出来提PR,咱们再来详细具体讨论.

2022-10-08 14:30 UTC, flyhigher139 commented
> @flyhigher139
> 
> > 不过下面1和2的补充不合适。在BlockingQueue里，无论阻塞还是非阻塞出入队，都要做成线程安全的，阻塞出入队，在边界处会阻塞等待，一直到满足条件被唤醒继续；而非阻塞的出入队，是在边界处直接返回false或nil，不用实现阻塞等待机制。
> 
> > 我之所以会把非阻塞出入队的行为也加上去，是考虑，BlockingQueue首先是线程安全Queue，所以线程安全的出入队操作放出来无可厚非，如果想缩减BlockingQueue的行为，去掉非阻塞出入队，也无可厚非
> 
> `BlockingQueue首先是线程安全Queue，所以线程安全的出入队操作放出来无可厚非`你这里强调了线程安全,我认为这种从**实现角度**建立起Queue接口与BlockingQueue接口之间的“继承”关系是不合适的.接口之间建立关系(耦合)应该基于抽象/逻辑语义而非实现细节,Queue接口的实现类既可以是线程安全的也可以不是,BlockingQueue也一样只是当前需求中非线程安全的阻塞队列实现出来没意义而已.当然,如果你设计的Queue接口spec要求其实现类必须是线程安全的,那么上面的关系建立是可以的.
> 
> 其实可以提供一个ThreadSafeBlockingQueue实现类,同时实现Queue接口和BlockingQueue接口(不组合Queue接口),来达到你现在在接口层面要实现的效果.
> 
> 另外,我提出的混合调用阻塞与非阻塞API的问题,与线程安全与否没关系,即便实现了线程安全,问题依然存在——相同功能(出队/入队),阻塞API与非阻塞API的优先级问题及在各种场景下都要维持这个优先级的问题. 你可以将代码实现出来提PR,咱们再来详细具体讨论.

语意上讲，BlockingQueue就是用在并发情况下的线程安全队列，不存在线程不安全的BlockingQueue一说吧

2022-10-08 14:35 UTC, flyhigher139 commented
> 什么时候阻塞应该跟在不在边界没什么关系，纯粹是实现的事情。另外我这里说的队首，只是一般逻辑上的队首。在优先级队列里面这个队首的概念就被弱化了。例如说，我完全可以设计一个极小的优先级队列，每次取元素，我都是遍历，也是可以的。但是这并不妨碍我依旧阻塞掉调用者

对，我上面的表达不准确。最开始我设计BlockingQueue时，是考虑了3组出入队接口的offer/pull，有超时控制的offerWithTimeout/pullWithTimeout，和能阻塞的put/take，后面两个，通过context.Context参数，能合并到一块去，所以就只剩下边界阻塞这一个特殊情况了

2022-10-08 14:37 UTC, flyhigher139 commented
@flycash @longyue0521 队列接口，不考虑`peek()`方法么？

2022-10-09 02:01 UTC, flyhigher139 commented
> 这个阻塞与否应该跟是不是边界没什么关系？
> 
> 你可以写个伪代码？

好，我直接按我那个想法，切个分支先简单实现以下BlockingQueue吧

2022-10-09 05:07 UTC, flycash commented
我先合并了。我现在不想要提供那么多方法，关于 peek，遍历之类的。暂时在没有需求的场景下，我想保持接口简单。如果你们要实现，也不要提供别的方法，就先提供入队和出队，阻塞队列和非阻塞队列是不是继承关系，这种语义问题不太重要，因为不同的人有不同的看法，我们只需要保证能够满足需求就可以。

2022-10-09 05:07 UTC, merged