基于堆和切片，实现Priority queue
gotomicro/ekit pull request #110
Opened 2022-10-09 13:02 UTC by flyhigher139

#105 

线程安全的PriorityArrayQueue

2022-10-10 03:40 UTC, longyue0521 requested changes

2022-10-10 03:40 UTC, longyue0521 commented on queue/priority_array_queue.go
> +type PriorityArrayQueue[T any] struct {
参考List的命名ArrayList/LinkedList,相应地ArrayPriorityQueue

2022-10-10 03:40 UTC, longyue0521 commented on queue/priority_array_queue_test.go
> +			capacity: 8,
将魔数8改为len(data)+X表明意图

2022-10-10 03:40 UTC, longyue0521 commented on queue/priority_array_queue_test.go
> +				if err != nil {
去掉if err !=nil 判断,并将assert.Nil改为assert.NoError,一旦有Error就会报错了;如果希望立即停止可以使用require.NoError

2022-10-10 03:40 UTC, longyue0521 commented on queue/priority_array_queue_test.go
> +				el, err := tc.q.Dequeue()
缺少测试用例——先Enqueue再Dequeue,也就是说Enqueue(0)/Enqueue(-1)再Dequeue出0和-1,再走下面的Dequeue出1到6的流程.Enqueue(0)/Enqueue(-1)根据上方的实现应该报“达到容量上限”的错

2022-10-10 03:40 UTC, longyue0521 commented on queue/priority_array_queue_test.go
> +				if err != nil {
去掉if err != nil,改assert.Nil为assert.NoError或require.NoError

2022-10-10 03:40 UTC, longyue0521 commented on queue/priority_array_queue_test.go
> +				if err != nil {
同上

2022-10-10 03:40 UTC, longyue0521 commented on queue/priority_array_queue_test.go
> +			q:        NewPriorityArrayQueueFromArray[int](data, less),
用data创建出来的优先级队列,应该既可以Enqueue又可以Dequeue以及未来可能支持的其他方法.本质上来说就是一个将切片convert到优先级队列的过程,要是只能Dequeue,那用标准库的Sort/heapSort就行了.

2022-10-10 03:40 UTC, longyue0521 commented on queue/priority_array_queue_test.go
> +			q:         NewPriorityArrayQueue[int](len(data), less),
这个测试用例在TestPriorityArrayQueue_Dequeue中已经覆盖到了,从空队列一直到len(data)

2022-10-10 03:56 UTC, longyue0521 requested changes

2022-10-10 03:56 UTC, longyue0521 commented on queue/priority_array_queue_test.go
> +		})
缺少并发相关的测试用例

单生产者,单消费者,满足优先级不变性(a < b return true / a < b return false)
单生产者,多消费者,满足优先级不变性(a < b return true / a < b return false)
多生产者,单消费者,满足优先级不变性(a < b return true / a < b return false)
多生产者,多消费者,满足优先级不变性(a < b return true / a < b return false)

生产者协程调用Enqueue, 消费者协程调用Dequeue,如果想简化测试用例可以只测多对多场景,但优先级控制应该都测到即a < b return ture小顶堆和a < b return false 大顶堆

2022-10-10 03:57 UTC, longyue0521 commented
将测试代码中所有`assert.Nil(t, err) if err != nil {  return }` 替换为 `require.NoError(t, err)`

2022-10-10 03:57 UTC, flyhigher139 commented on queue/priority_array_queue.go
> +		data:     make([]T, 1, len(data)+1),
主要目的是，直接实现数组的堆化，可以通过option修改capacity
把数组直接堆化为优先队列相当于快捷操作，类似python的标准库的heapq，这种方式我之前时不时会用，就提供了

2022-10-10 04:01 UTC, flyhigher139 commented on queue/priority_array_queue.go
> +	p.data = append(p.data, t)
好的，扩缩容稍后我加上去

2022-10-10 04:09 UTC, longyue0521 commented on queue/priority_array_queue.go
> +		data:     make([]T, 1, len(data)+1),
python标准库heapq即便堆化后也是可以heappush和heappop的.如果你想模拟python的实现,那么你应该提供包方法,然后始终将data作为第一个参数,明确意图.但这可能不是ekit想要支持的方式.

2022-10-10 04:10 UTC, longyue0521 commented on queue/priority_array_queue.go
> +		data:     make([]T, 1, len(data)+1),
你可以将option去掉,显示强制用户指定capacity

2022-10-11 04:19 UTC, flycash commented on queue/priority_array_queue.go
> +	ErrEmptyQueue    = errors.New("队列为空")
都定义为私有的，暂时我不想让用户依赖于这两个错误

2022-10-11 04:19 UTC, flycash commented on queue/priority_array_queue.go
> +type Less[T any] func(a, b T) bool
我的看法是在 ekit 的里面定义一个 Comparable 接口：
```go
type Comparable[T any] interface {
	// CompareTo 方法只能返回以下三个返回值:
	// 1: dst 比较大
	// 0: 两者一样大小
	// -1: dst 比较小
	CompareTo(dst T) int
}
```
例如 User 就是：
```go
func (u User) CompareTo(dst User)
```
Comparable 作为一个通用的泛型约束，后续在设计树形结构，跳表之类的时候都用得上。

相应地，后面的 PriorityQueue 的泛型参数 T 就不是 T any 而是 T Comparable 了。

2022-10-11 04:19 UTC, flycash commented on queue/priority_array_queue.go
> +func (p *PriorityArrayQueue[T]) Enqueue(t T) error {
这个方法我不建议使用 double-write 的形式。我们可以做一个假设，就是大多数情况下，用户入队是肯定成功的，那么也就是你迟早都要加写锁。

所以在这种情况下，对于大部分操作来说，反而平白多了一个加读锁的过程

2022-10-11 04:19 UTC, flycash commented on queue/priority_array_queue.go
> +type Less[T any] func(a, b T) bool
其实我的目标是给用户提供两种手段：
- 实现接口
- 指定一个比较的方法

你这里采用的是指定一个比较的方法，倒也不是不行，但是我觉得有些人可能会喜欢实现接口的形式。

2022-10-11 04:19 UTC, flycash commented on queue/priority_array_queue.go
> +type PriorityArrayQueue[T any] struct {
这个结构体上说清楚，是优先级最小的在队首，还是优先级最高的在队首

2022-10-11 04:19 UTC, flycash commented on queue/priority_array_queue.go
> +	if len(p.data) < 2 {
类似地，这里面如果我们认为大多数情况下，出队都能拿到一个元素，那么直接加写锁。这个和入队不太一样，入队那边我觉得大多数时候成功是这个假设还是挺准确的，而出队的话，反而有点不确定究竟是大多数时候有元素，还是大多数时候没元素

2022-10-11 04:19 UTC, flycash commented on queue/priority_array_queue.go
> +type Less[T any] func(a, b T) bool
或者我们只保留传入一个比较方法的做法？把 Less 改名 Comparator，然后返回 0，-1， 1。将这个接口挪过去 ekit 下

2022-10-11 05:39 UTC, longyue0521 commented on queue/priority_array_queue.go
> +type Less[T any] func(a, b T) bool
对于自定义类型实现Comparable接口是可以的，但对于原生类型（int/float/time.Time等等）,用户需要额外做些事情，要么用别名要么定义新的named type才能实现CompareTo方法。

Less/Comparator的做法更通用更方便， Comparator的返回值不要限定在-1，1
——可以用小于0的数表示，a < b；等于0表示 a == b；大于0的数表示 a > b；这样用`User1.Age - User2.Age`就可以了不用调整到1或-1

2022-10-11 05:48 UTC, flyhigher139 commented on queue/priority_array_queue.go
> +type Less[T any] func(a, b T) bool
好，那我先把Less改为Comparator，挪一下位置吧

2022-10-11 05:56 UTC, flyhigher139 commented on queue/priority_array_queue.go
> +type Less[T any] func(a, b T) bool
> 我的看法是在 ekit 的里面定义一个 Comparable 接口：
> 
> ```go
> type Comparable[T any] interface {
> 	// CompareTo 方法只能返回以下三个返回值:
> 	// 1: dst 比较大
> 	// 0: 两者一样大小
> 	// -1: dst 比较小
> 	CompareTo(dst T) int
> }
> ```
> 
> 例如 User 就是：
> 
> ```go
> func (u User) CompareTo(dst User)
> ```
> 
> Comparable 作为一个通用的泛型约束，后续在设计树形结构，跳表之类的时候都用得上。
> 
> 相应地，后面的 PriorityQueue 的泛型参数 T 就不是 T any 而是 T Comparable 了。

其实我第一反应，这是想这么实现。当时感觉麻烦了就没加，我晚点补上去

如果把这个加上去，就改成T实现Comparable接口，如果传入了Less方法，就Less做比较，没有的话，就调用Comparable接口做比较吧？

2022-10-11 06:08 UTC, flyhigher139 commented on queue/priority_array_queue.go
> +func (p *PriorityArrayQueue[T]) Enqueue(t T) error {
好，我把出入队都改成直接加写锁

受老师启发，我觉得，出队的时候，如果队列用的比较频繁，队列为空的概率比较低，如果用的不那么频繁，虽然队列为空的概率会高一点，但性能损失的影响应该低一点。所以出队也直接用写锁是OK的

2022-10-11 07:39 UTC, flyhigher139 commented
上面讨论的内容有点多，我先做以下几点吧

- [ ] isOutOfCapacity := p.capacity != 0 && len(p.data)-1 == p.capacity
- [ ] 扩缩容
- [ ] err 定义为私有
- [ ] 出入队改为直接用写锁
- [ ] 将测试代码中所有assert.Nil(t, err) if err != nil { return } 替换为 require.NoError(t, err)
- [ ] 把 Less 改名 Comparator，然后返回 0，-1， 1，然后挪到 ekit下 
- [ ] 结构体上说清楚，这是个基于小顶堆的优先队列

2022-10-11 09:40 UTC, flycash commented on queue/priority_array_queue.go
> +func NewPriorityArrayQueueFromArray[T any](data []T, less Less[T], opts ...PriorityArrayQueueOption[T]) *PriorityArrayQueue[T] {
> 将测试代码中所有`assert.Nil(t, err) if err != nil { return }` 替换为 `require.NoError(t, err)`

不是所有的都能替换的，因为有些确实返回了 error，并且比较了预期的 error，后续不再进行返回值比较，那就不能改成 require.NoError

2022-10-11 09:41 UTC, flycash commented
将测试代码中所有assert.Nil(t, err) if err != nil { return } 替换为 require.NoError(t, err)

不是所有的都能替换的，因为有些确实返回了 error，并且比较了预期的 error，后续不再进行返回值比较，那就不能改成 require.NoError

2022-10-11 09:42 UTC, flycash commented
缩容可以直接将原本 ArrayList 里面的缩容代码放进去 Internal/slice 里面，你就可以直接调用方法了

2022-10-11 10:01 UTC, flycash commented on queue/priority_array_queue.go
> +type Less[T any] func(a, b T) bool
那可能用 Comparator 比较合适：
```go
type Comparator[T] func(src T, dst T) int
```
主要是你顾虑的基础类型。等后面我们再来考虑 Comparable 接口

2022-10-11 10:05 UTC, flycash commented on queue/priority_array_queue.go
> +type PriorityArrayQueue[T any] struct {
直接叫做 PriorityQueue 也不是不行，就是稍微觉得以后万一我们要提供一个非线程安全，非阻塞的优先级队列，这个名字就冲突了

2022-10-12 01:52 UTC, longyue0521 commented
还需要加一个Peek方法,查看对头元素

2022-10-12 05:35 UTC, flyhigher139 commented
> 还需要加一个Peek方法,查看对头元素

嗯，昨晚偷懒了，今天晚上加上去

2022-10-12 07:01 UTC, flycash requested changes

2022-10-12 07:01 UTC, flycash commented on queue/priority_array_queue.go
> +func WithNewCapacity[T any](capacity int) PriorityArrayQueueOption[T] {
又或者：
```go
type config struct {
   cap int
}
```
后面所有的 Queue 实现都会利用这个 config 来构造，Option 构造的应该是这个 Config

2022-10-12 07:04 UTC, flycash commented on queue/priority_array_queue.go
> +type PriorityArrayQueue[T any] struct {
- 将 PrioriyArrayQueue 改成 ConcurrentPriorityQueue
- 将 ConcurrentPriorityQueue 拆成两个，一个叫做 priorityQueue（或者挪过去 internal/queque），它是无锁的，非线程安全实现，一个就保持叫做 ConcurrentPriorityQueue，是使用读写锁对 priorityQueue 一个装饰器
- 后面我在设计延时队列的时候，我可以直接使用非线程安全的。

2022-10-12 07:09 UTC, longyue0521 commented on queue/priority_array_queue.go
> +		t := new(T)
`ErrEmptyQueue    = errors.New("队列为空")` 改为 `errEmptyQueue = errors.New("ekit: 队列为空")`

2022-10-12 07:13 UTC, longyue0521 commented
只保留`func NewConcurrentPriorityQueue(cap int, compare Comparator[T])`吧，在注释中准确描述cap和compare即可。如果需要，用户可以自己遍历slice，然后再将元素Enqueue进去以达到他想要的初始状态。

2022-10-12 07:14 UTC, longyue0521 commented on queue/priority_array_queue.go
> +func WithNewCapacity[T any](capacity int) PriorityArrayQueueOption[T] {
只保留`func NewConcurrentPriorityQueue(cap int, compare Comparator[T])`吧，在注释中准确描述cap和compare即可。如果需要，用户可以自己遍历slice，然后再将元素Enqueue进去以达到他想要的初始状态。

2022-10-12 07:24 UTC, flyhigher139 commented on queue/priority_array_queue.go
> +}
把那个计算capacity的方法摘出去，然后两边都改一下就可以了吧？

2022-10-12 07:43 UTC, flyhigher139 commented on queue/priority_array_queue.go
> +type PriorityArrayQueueOption[T any] func(p *PriorityArrayQueue[T])
我是想，首先2种情况，是不是都要支持：
1. 直接创建一个空的优先队列
2. 把一个现成的切片转换为优先队列

对于1，接下来只要考虑这个队列有界无界即可，这个我比较倾向于`func NewConcurrentPriorityQueue(cap int, compare Comparator[T])`，这里由于cap是必传参数，创建时用户就要确定用有界还是无界队列，option的话，由于是可选，可能用户就直接忽略了

对于2，我主要是python影响，感觉可以支持。如果支持，主要是考虑这个情况下，cap 多大，这里默认不是无界队列了。这种情况，我以前的用法，就是数组多大，队列容量就多大了，如果需要容量更大的，就不用这个方法来创建队列。这里，是不是考虑用切片的cap作为队列的cap，也是合理的？

2022-10-12 08:12 UTC, longyue0521 commented on queue/priority_array_queue.go
> +type PriorityArrayQueueOption[T any] func(p *PriorityArrayQueue[T])
2这种情况，就是根据slice创建完队列后就只能Dequeue而不能再Enqueue那个场景了吧，如果想要继续调用Enqueue，还得用`func NewConcurrentPriorityQueue(cap int, compare Comparator[T])`。

不如让用户显示指定cap，`func NewConcurrentPriorityQueueFrom(slice []T, cap int, compare Comparator[T])`，返回的队列能否再Enqueue让用户自己决定。

2022-10-12 11:51 UTC, flyhigher139 commented on queue/priority_array_queue.go
> +type PriorityArrayQueueOption[T any] func(p *PriorityArrayQueue[T])
2的情况，一开始就把队列初始化好并加满了处理，要有出队处理的，才能再有新的入队，总容量就随初始化好了就不会再变了
并发场景的话，可以做成阻塞的优先队列

2022-10-12 12:11 UTC, longyue0521 commented on queue/priority_array_queue.go
> +type PriorityArrayQueueOption[T any] func(p *PriorityArrayQueue[T])
这种操作可能是python中的常用方法,Go中一般是帮用户入队,入队成功后用户想入队出队都行. 要不简单点,先只提供`NewConcurrentPriorityQueue(cap int, compare Comparator[T])`这个核心构造方法吧.衍生的API以后再说

2022-10-12 15:38 UTC, flyhigher139 commented on queue/priority_array_queue.go
> +type PriorityArrayQueueOption[T any] func(p *PriorityArrayQueue[T])
嗯，我也同意只保留核心的这个

2022-10-13 02:58 UTC, flycash requested changes
并发测试可以考虑使用这种方案：
多个goroutine不断往队列里面塞元素

塞完之后过个 goroutine 从队列里面拿，拿出来的再放到一个 chan（或者线程安全 List) 里面，最后你比较最终的那个 chan（或者线程安全 List），里面的元素应该是有序的，按照小顶堆，应该是从小到大。

但是这种测试方案没有测试一边 Enqueue 一边 Dequeue，这种很难设计可以自动化执行并且生成预期结果的测试，你们有什么好建议吗？

2022-10-13 02:58 UTC, flycash commented on internal/slice/shrink.go
> +func calCapacity(c, l int) int {
这个方法改成返回两个返回值，第一个是新容量，第二个是容量是否发生了变化。因为在 Shrink 里面 n==c 这个判断条件读起来有点隐晦，所以你在这里显式告诉调用者有没有缩容，可读性更好一点

2022-10-13 02:58 UTC, flycash commented on queue/priority_array_queue.go
> +type PriorityArrayQueueOption[T any] func(p *PriorityArrayQueue[T])
嗯嗯，就只保留这个

2022-10-13 02:58 UTC, flycash commented on queue/priority_array_queue.go
> +func WithNewCapacity[T any](capacity int) PriorityArrayQueueOption[T] {
👌🏻

2022-10-13 02:58 UTC, flycash commented on queue/priority_array_queue_test.go
> +	expected := []int{1, 2, 3, 4, 5, 6}
像这两个，在每个测试用例里面定义。

2022-10-13 02:58 UTC, flycash commented on queue/priority_array_queue_test.go
> +	testCases := []struct {
对于 Enqueue 来说，你只需要考虑这边 Enqueue 之后的结果是否符合预期就可以。所以实际上你这个测试用例可以简化为：
```go
testCases := []struct {
    name string
    input int
    q *ConcurrentPriorityQueue[int]
    wantErr error
    wantSlice error
}{

}

for _, tc := range testCases {
		t.Run(tc.name, func(t *testing.T) {
			err := tc.q.Enqueue(tc.input)
                         require.Equal(t, tc.wantErr, err)
                         require.Equal(t, tc.wantSlice, tc.q.data)
		})
```
在我们只保留 NewConcurrentPriorityQueue，可以将有界和无界的测试用例合并在一起，区别就是你在构造测试用例的时候，tc.q 会使用不同的 ConcurrentPriorityQueue

2022-10-13 02:58 UTC, flycash commented on queue/priority_array_queue_test.go
> +	testCases := []struct {
Dequeue 的测试用例设计也类似，你只需要比较两个东西：
- Dequeue 返回的 error 和 数据
- Dequeue 之后的 q.data 结构

2022-10-13 02:58 UTC, flycash commented
@flyhigher139 你把所有的评论都过一遍，已经改了的，你就点一下 resolve

2022-10-13 05:34 UTC, flyhigher139 commented
> @flyhigher139 你把所有的评论都过一遍，已经改了的，你就点一下 resolve

好的～

2022-10-13 06:31 UTC, longyue0521 commented
> 并发测试可以考虑使用这种方案：
多个goroutine不断往队列里面塞元素

>塞完之后过个 goroutine 从队列里面拿，拿出来的再放到一个 chan（或者线程安全 List) 里面，最后你比较最终的那个 chan（或者线程安全 List），里面的元素应该是有序的，按照小顶堆，应该是从小到大。

>但是这种测试方案没有测试一边 Enqueue 一边 Dequeue，这种很难设计可以自动化执行并且生成预期结果的测试，你们有什么好建议吗？

可以构造一个“多协程Enqueue，多协程Dequeue场景，记录操作日志”，根据日志再次模拟操作以验证正确性。

假设拿到的日志如下：
```
{gid: 1, op: E, val: 3}
{gid: 3, op: E, val: 1}
{gid: 2, op: E, val: 5}
{gid: 4, op: D, val: 1}
{gid: 5, op: E, val: 6}
{gid: 6, op: D, val: 3}
```
`gid 1,3,2,5` 证明多个协程调用Enqueue，`gid 4，6`证明多个协程调用Dequeue；

创建一个queue，遍历日志三元组，碰到`op==E`就Enqueue对应的val，碰到`op==D`就Dequeue，并将Dequeue结果与`op== D`的val比较,如果不相符就报错。

## 如何拿到日志

### 非侵入

尝试1：

```go
 go func(id int) {
     q.Enqueue(xxxx)
     // 写日志
    concurrentList.Append(.....) 
}(i)
```
这种方式记录不准确，当协程x刚要写日志，它的时间片到了，另一协程Y在时间片内先写入了，日志就乱序了。

尝试2，上面问题的本质是Enqueue/Dequeue操作与写日志操作是两个“事务”受两把锁保护，可以尝试封装一下

```go
type LogQueue struct {
      mu sync.Mutex
      que ConcurrentPriorityQueue
      logs []OpLog
}
func (l  *LogQueue) Enqueue(ctx Context.Context, gid , t T) error {
      l.mu.Lock()
     defer l.mu.UnLock()
     err := l.que.Enueue(ctx, t)
     // 返回前写日志
     logs = append(log, OpLog{gid: gid, op: E, val: t})
     return err
}
```

日志记录准确，但只验证了que是否满足优先级的特性，并没有真正测到在que上有并发的情况，并发由LogQueue的mu抗下来了。

### 侵入式

在现有实现的Enqueue/Dequeue内部，返回结果前（类似于上方LogQueue）记录日志，提供一个非导出方法拿到最终日志集合`queue.getLogs()`。做的再好一点，就加一个环境变量的判断，如果是测试环境，那就记录日志，如果不是测试环境就跳过。

2022-10-13 15:47 UTC, flyhigher139 commented
@flycash @longyue0521  现在基本就是单元测试还没完善了，其他的应该都resolved了，我明天再搞一下单元测试

2022-10-14 03:25 UTC, flycash commented
> @flycash
> 
> > 并发测试可以考虑使用这种方案：
> > 多个goroutine不断往队列里面塞元素
> 
> > 塞完之后过个 goroutine 从队列里面拿，拿出来的再放到一个 chan（或者线程安全 List) 里面，最后你比较最终的那个 chan（或者线程安全 List），里面的元素应该是有序的，按照小顶堆，应该是从小到大。
> 
> > 但是这种测试方案没有测试一边 Enqueue 一边 Dequeue，这种很难设计可以自动化执行并且生成预期结果的测试，你们有什么好建议吗？
> 
> 可以构造一个“多协程Enqueue，多协程Dequeue场景，记录操作日志”，根据日志再次模拟操作以验证正确性。
> 
> 假设拿到的日志如下：
> 
> ```
> {gid: 1, op: E, val: 3}
> {gid: 3, op: E, val: 1}
> {gid: 2, op: E, val: 5}
> {gid: 4, op: D, val: 1}
> {gid: 5, op: E, val: 6}
> {gid: 6, op: D, val: 3}
> ```
> 
> `gid 1,3,2,5` 证明多个协程调用Enqueue，`gid 4，6`证明多个协程调用Dequeue；
> 
> 创建一个queue，遍历日志三元组，碰到`op==E`就Enqueue对应的val，碰到`op==D`就Dequeue，并将Dequeue结果与`op== D`的val比较,如果不相符就报错。
> 
> ## 如何拿到日志
> ### 非侵入
> 尝试1：
> 
> ```go
>  go func(id int) {
>      q.Enqueue(xxxx)
>      // 写日志
>     concurrentList.Append(.....) 
> }(i)
> ```
> 
> 这种方式记录不准确，当协程x刚要写日志，它的时间片到了，另一协程Y在时间片内先写入了，日志就乱序了。
> 
> 尝试2，上面问题的本质是Enqueue/Dequeue操作与写日志操作是两个“事务”受两把锁保护，可以尝试封装一下
> 
> ```go
> type LogQueue struct {
>       mu sync.Mutex
>       que ConcurrentPriorityQueue
>       logs []OpLog
> }
> func (l  *LogQueue) Enqueue(ctx Context.Context, gid , t T) error {
>       l.mu.Lock()
>      defer l.mu.UnLock()
>      err := l.que.Enueue(ctx, t)
>      // 返回前写日志
>      logs = append(log, OpLog{gid: gid, op: E, val: t})
>      return err
> }
> ```
> 
> 日志记录准确，但只验证了que是否满足优先级的特性，并没有真正测到在que上有并发的情况，并发由LogQueue的mu抗下来了。
> 
> ### 侵入式
> 在现有实现的Enqueue/Dequeue内部，返回结果前（类似于上方LogQueue）记录日志，提供一个非导出方法拿到最终日志集合`queue.getLogs()`。做的再好一点，就加一个环境变量的判断，如果是测试环境，那就记录日志，如果不是测试环境就跳过。

侵入式方案在我们这种工具类的仓库里面不是很合适。倒是使用一个 Queue 进行二次封装还可以。我有一个简单的想法：
```go
type TestQueue struct {
     mux sync.Mutex
     q ConcurrentPriorityQueque[int]
}

func (q *TestQueue) Dequeue() (T, error) {
       // 加写锁
      t := q.q.Dequeue()
      // 比较 t,t 这个时候必须是优先级最高的那个
}
```

只是通过在 Dequeue 里面埋下一个探针，确保每次 Dequeue 出来的都是优先级最高的。这能够间接证明，Enqueue 是正确的

2022-10-14 06:05 UTC, flyhigher139 commented
> > @flycash
> > > 并发测试可以考虑使用这种方案：
> > > 多个goroutine不断往队列里面塞元素
> > 
> > 
> > > 塞完之后过个 goroutine 从队列里面拿，拿出来的再放到一个 chan（或者线程安全 List) 里面，最后你比较最终的那个 chan（或者线程安全 List），里面的元素应该是有序的，按照小顶堆，应该是从小到大。
> > 
> > 
> > > 但是这种测试方案没有测试一边 Enqueue 一边 Dequeue，这种很难设计可以自动化执行并且生成预期结果的测试，你们有什么好建议吗？
> > 
> > 
> > 可以构造一个“多协程Enqueue，多协程Dequeue场景，记录操作日志”，根据日志再次模拟操作以验证正确性。
> > 假设拿到的日志如下：
> > ```
> > {gid: 1, op: E, val: 3}
> > {gid: 3, op: E, val: 1}
> > {gid: 2, op: E, val: 5}
> > {gid: 4, op: D, val: 1}
> > {gid: 5, op: E, val: 6}
> > {gid: 6, op: D, val: 3}
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > `gid 1,3,2,5` 证明多个协程调用Enqueue，`gid 4，6`证明多个协程调用Dequeue；
> > 创建一个queue，遍历日志三元组，碰到`op==E`就Enqueue对应的val，碰到`op==D`就Dequeue，并将Dequeue结果与`op== D`的val比较,如果不相符就报错。
> > ## 如何拿到日志
> > ### 非侵入
> > 尝试1：
> > ```go
> >  go func(id int) {
> >      q.Enqueue(xxxx)
> >      // 写日志
> >     concurrentList.Append(.....) 
> > }(i)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 这种方式记录不准确，当协程x刚要写日志，它的时间片到了，另一协程Y在时间片内先写入了，日志就乱序了。
> > 尝试2，上面问题的本质是Enqueue/Dequeue操作与写日志操作是两个“事务”受两把锁保护，可以尝试封装一下
> > ```go
> > type LogQueue struct {
> >       mu sync.Mutex
> >       que ConcurrentPriorityQueue
> >       logs []OpLog
> > }
> > func (l  *LogQueue) Enqueue(ctx Context.Context, gid , t T) error {
> >       l.mu.Lock()
> >      defer l.mu.UnLock()
> >      err := l.que.Enueue(ctx, t)
> >      // 返回前写日志
> >      logs = append(log, OpLog{gid: gid, op: E, val: t})
> >      return err
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 日志记录准确，但只验证了que是否满足优先级的特性，并没有真正测到在que上有并发的情况，并发由LogQueue的mu抗下来了。
> > ### 侵入式
> > 在现有实现的Enqueue/Dequeue内部，返回结果前（类似于上方LogQueue）记录日志，提供一个非导出方法拿到最终日志集合`queue.getLogs()`。做的再好一点，就加一个环境变量的判断，如果是测试环境，那就记录日志，如果不是测试环境就跳过。
> 
> 侵入式方案在我们这种工具类的仓库里面不是很合适。倒是使用一个 Queue 进行二次封装还可以。我有一个简单的想法：
> 
> ```go
> type TestQueue struct {
>      mux sync.Mutex
>      q ConcurrentPriorityQueque[int]
> }
> 
> func (q *TestQueue) Dequeue() (T, error) {
>        // 加写锁
>       t := q.q.Dequeue()
>       // 比较 t,t 这个时候必须是优先级最高的那个
> }
> ```
> 
> 只是通过在 Dequeue 里面埋下一个探针，确保每次 Dequeue 出来的都是优先级最高的。这能够间接证明，Enqueue 是正确的

测试并发Enqueue，我是想先多个go rounte 执行入队操作，完成后，主携程把元素逐一出队，只要有序，可以认为并发入队没问题

测试并发Dequeue，主要是把出队元素写入channel时，可能会乱序，目前考虑2个方案：
1. 出队元素`el`写入channel，单独起一个go routine，写入前，根据`el`大小，sleep一定时间，这个方式，每个`el`写入前的sleep时间要控制好，才能保证顺序。我目前想到的一些睡眠时间计算方法，均不能保证每次写入有序
2. 加锁出队，这样虽然能保证顺序，但这让go routine在Dequeue前，已经通过锁变成有序的了，并不能达到测试并发dequeue的目的

2022-10-14 07:13 UTC, flycash commented
> > > @flycash
> > > > 并发测试可以考虑使用这种方案：
> > > > 多个goroutine不断往队列里面塞元素
> > > 
> > > 
> > > > 塞完之后过个 goroutine 从队列里面拿，拿出来的再放到一个 chan（或者线程安全 List) 里面，最后你比较最终的那个 chan（或者线程安全 List），里面的元素应该是有序的，按照小顶堆，应该是从小到大。
> > > 
> > > 
> > > > 但是这种测试方案没有测试一边 Enqueue 一边 Dequeue，这种很难设计可以自动化执行并且生成预期结果的测试，你们有什么好建议吗？
> > > 
> > > 
> > > 可以构造一个“多协程Enqueue，多协程Dequeue场景，记录操作日志”，根据日志再次模拟操作以验证正确性。
> > > 假设拿到的日志如下：
> > > ```
> > > {gid: 1, op: E, val: 3}
> > > {gid: 3, op: E, val: 1}
> > > {gid: 2, op: E, val: 5}
> > > {gid: 4, op: D, val: 1}
> > > {gid: 5, op: E, val: 6}
> > > {gid: 6, op: D, val: 3}
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > `gid 1,3,2,5` 证明多个协程调用Enqueue，`gid 4，6`证明多个协程调用Dequeue；
> > > 创建一个queue，遍历日志三元组，碰到`op==E`就Enqueue对应的val，碰到`op==D`就Dequeue，并将Dequeue结果与`op== D`的val比较,如果不相符就报错。
> > > ## 如何拿到日志
> > > ### 非侵入
> > > 尝试1：
> > > ```go
> > >  go func(id int) {
> > >      q.Enqueue(xxxx)
> > >      // 写日志
> > >     concurrentList.Append(.....) 
> > > }(i)
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 这种方式记录不准确，当协程x刚要写日志，它的时间片到了，另一协程Y在时间片内先写入了，日志就乱序了。
> > > 尝试2，上面问题的本质是Enqueue/Dequeue操作与写日志操作是两个“事务”受两把锁保护，可以尝试封装一下
> > > ```go
> > > type LogQueue struct {
> > >       mu sync.Mutex
> > >       que ConcurrentPriorityQueue
> > >       logs []OpLog
> > > }
> > > func (l  *LogQueue) Enqueue(ctx Context.Context, gid , t T) error {
> > >       l.mu.Lock()
> > >      defer l.mu.UnLock()
> > >      err := l.que.Enueue(ctx, t)
> > >      // 返回前写日志
> > >      logs = append(log, OpLog{gid: gid, op: E, val: t})
> > >      return err
> > > }
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 日志记录准确，但只验证了que是否满足优先级的特性，并没有真正测到在que上有并发的情况，并发由LogQueue的mu抗下来了。
> > > ### 侵入式
> > > 在现有实现的Enqueue/Dequeue内部，返回结果前（类似于上方LogQueue）记录日志，提供一个非导出方法拿到最终日志集合`queue.getLogs()`。做的再好一点，就加一个环境变量的判断，如果是测试环境，那就记录日志，如果不是测试环境就跳过。
> > 
> > 
> > 侵入式方案在我们这种工具类的仓库里面不是很合适。倒是使用一个 Queue 进行二次封装还可以。我有一个简单的想法：
> > ```go
> > type TestQueue struct {
> >      mux sync.Mutex
> >      q ConcurrentPriorityQueque[int]
> > }
> > 
> > func (q *TestQueue) Dequeue() (T, error) {
> >        // 加写锁
> >       t := q.q.Dequeue()
> >       // 比较 t,t 这个时候必须是优先级最高的那个
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 只是通过在 Dequeue 里面埋下一个探针，确保每次 Dequeue 出来的都是优先级最高的。这能够间接证明，Enqueue 是正确的
> 
> 测试并发Enqueue，我是想先多个go rounte 执行入队操作，完成后，主携程把元素逐一出队，只要有序，可以认为并发入队没问题
> 
> 测试并发Dequeue，主要是把出队元素写入channel时，可能会乱序，目前考虑2个方案：
> 
> 1. 出队元素`el`写入channel，单独起一个go routine，写入前，根据`el`大小，sleep一定时间，这个方式，每个`el`写入前的sleep时间要控制好，才能保证顺序。我目前想到的一些睡眠时间计算方法，均不能保证每次写入有序
> 2. 加锁出队，这样虽然能保证顺序，但这让go routine在Dequeue前，已经通过锁变成有序的了，并不能达到测试并发dequeue的目的

入队可以用你设计的方案。出队我觉得能不能用这种思路：虽然多个 goroutine 之间的顺序是不定，但是同一个 goroutine 取出来的元素，必然是按照优先级顺序排好了的。

我们设想一下，我多个 goroutine 从优先级队列里面拿元素，肯定是不会说希望多个 goroutine 之间的元素保持有序，只能是说保证单一个 goroutine 取出来的元素是有序的。

之后我们再将多个 goroutine 的数据合并起来，恰好就是全部数据，就意味着出队也没有什么问题。

2022-10-14 08:19 UTC, flycash requested changes
测试用例，一般就是：
- name：名字
- 输入：基本上就是参数是啥，结构体自身是啥
- 预期输出：基本上就是它的返回值是啥
- 调用后的结构体状态：这个是可选的，在一些场景下我们不需要测试，优先级队列比较特殊一点，所以需要测试一下

绝大多数情况下，测试用例都遵循这个模板。输入和输出一定要清晰，在执行测试用例的时候就要避免构造结构体或者参数，比如说你在执行测试用例的时候都是循环一个 data，组装起来。这就不够清晰，别人看测试用例难以一眼看出你构造的输入是什么。

类似的，输出也是一定要清晰。

总之，在执行测试用例的时候，那一段代码必然是很简单的。只有在一些特殊的，比如并发测试的场景下，执行测试用例的代码会比较复杂

2022-10-14 08:19 UTC, flycash commented on internal/queue/priority_queue_test.go
> +			}
因为你这里很多地方都用到了类似的代码，所以你可以考虑抽取出来一个方法，newPriorityQueue(t, data)

2022-10-14 08:19 UTC, flycash commented on internal/queue/priority_queue_test.go
> +func TestPriorityQueue_Dequeue(t *testing.T) {
在 Dequeue 这里，只需要考虑几个场景：
- 一个元素都没有，然后 Dequeue
- 有元素，但是只有一个元素，dequeue 了就没了
- 有元素，而且有很多元素，dequeue 之后还有很多元素
那么从这个角度出发，包括 Dequeue 的方法签名出发，那么我们可以设计测试用例为：
```go

	testCases := []struct {
		name      string
                // 输入
		q *PriorityQueue[int]
                // 预期输出
                 wantErr   error
                 wantVal int

                // 经过Dequeue 之后的预期结构。这是因为我们是一个小顶堆，所以要确保 Dequeue 之后依旧维持住了小顶堆
		wantSlice []int
                wantCap int
	}{
{
    name:"empty",
   q: newQueueOf(t, nil)
    wantErr: ErrEmpty,
    wantSlice:[]int{} // 还是 nil？
}
{
    name:"only one",
}
{
    name:"many"
}
}

// 具体每一个测试
val, err := tc.q.Dequeue()
assert.Equal(t, tc.wantErr, err)
assert.Equal(t, tc.wantSlice, t.q.data)
assert.Equal(t, tc.wantCap, t.q.Cap())
if err != nil {
    return 
}
assert.Equal(t. tc.wantVal, val)
```

2022-10-14 08:19 UTC, flycash commented on internal/queue/priority_queue_test.go
> +func TestPriorityQueue_Enqueue(t *testing.T) {
参考前面的 Dequeue 的测试用例设计，对于 Enqueue 来说，要考虑：
- 有界还是无界
- 在有界的情况下考虑：有位置，没位置，恰好有一个位置，队列中原本一个元素都没有
- 无界就是：队列中一个元素都没有，有很多元素

再综合考虑：
- 新加入的元素是最大的
- 新加入的元素是最小的
- 新加入的元素不大不小

在每一个用例里面，你要校验的是：
- Enqueue 返回的 error
- Enqueue 之后的结构，也就是 q 里面的 data 这个切片
- Enqueue 之后的 Cap()

2022-10-14 08:19 UTC, flycash commented on internal/queue/priority_queue_test.go
> +func TestPriorityQueue_Enqueue(t *testing.T) {
哦哦哦， 还要考虑 Enqueue 的元素和某些元素相等，比如说和最大值，和最小值相等。

2022-10-14 08:19 UTC, flycash commented on internal/queue/priority_queue_test.go
> +func TestPriorityQueue_Shrink(t *testing.T) {
这个倒也用不着仔细测试，因为它的正确性是依赖于 Shrink 方法的，所以稍微测一下触发了缩容的就可以的了，应该说，确保调用了 Shrink 就行了。Shrink 它自己的测试保证是对的

2022-10-14 08:44 UTC, flycash commented on internal/queue/priority_queue_test.go
> +func TestPriorityQueue_Enqueue(t *testing.T) {
Enqueue 比 Dequeue 测试要复杂主要就是因为 Enqueue 涉及到调整堆结构，相比 Dequeue，可测试性更强一些

2022-10-14 09:41 UTC, longyue0521 commented
我们的目的是什么？测试并发场景下满足优先级队列的不变性。

有哪些并发场景？

1. 只在Enqueue方法上的并发，然后单协程调用Dequeue
2. 先当协程多次调用Go协程，然后只在Dequeue方法上的并发
3. 以1：1方式，形成Enqueue与Dequeue的并发
4. 以n：m方式，形成Enqueue与Dequeue的并发

如果从头以TDD方式实现代码需要依次通过1～4，当代码完全实现后只保留测试用4就可以了，前三个测试用例只是为了驱动出最终代码的中间检查点而已。

@flyhigher139 

> 测试并发Enqueue，我是想先多个go rounte 执行入队操作，完成后，主携程把元素逐一出队，只要有序，可以认为并发入队没问题

这个是上面的用例1，只测到了”只在Enqueue上的并发“场景。

> 测试并发Dequeue，主要是把出队元素写入channel时，可能会乱序，目前考虑2个方案：
> 1. 出队元素el写入channel，单独起一个go routine，写入前，根据el大小，sleep一定时间，这个方式，每个el写入前的sleep时间要控制好，才能保证顺序。我目前想到的一些睡眠时间计算方法，均不能保证每次写入有序
> 2. 加锁出队，这样虽然能保证顺序，但这让go routine在Dequeue前，已经通过锁变成有序的了，并不能达到测试并发dequeue的目的

这个是上面的测试用例2，只测到了"只在Dequeue上的并发”场景。

你依然需要补充“Enqueue与Dequeue之间形成并发”的场景。

@flycash 

> 入队可以用你设计的方案。出队我觉得能不能用这种思路：虽然多个 goroutine 之间的顺序是不定，但是同一个 goroutine 取出来的元素，必然是按照优先级顺序排好了的。

在并发场景下，即便是同一个协程Dequeue出的元素之间也不存在任何特定关系。

举例，假设协程1～3希望将其ID入队并且仅有协程4执行出队操作，协程4可能得到如下序列：

1. 1,2,3，协程1～3全部入队完成，协程4执行3次出队
2. 1,3,2，协程1，3先入队成功，而协程2在协程4（拿走1，3后阻塞超时）后才入队成功
3. 2,1,3
4. 2,3,1
5. 3,1,2
6. 3,2,1，协程3入队，协程4出队；协程2入队，协程4出队；协程1入队，协程4出队；

我们不能假设Dequeue间元素的关系，因为Enqueue的调用时机以及入队元素的优先级总能破坏所谓的”出队元素间的优先级“条件。

对于任意一个并发Dequeue操作，正确的检验方法是：

1. 拿到锁后，记录当前队列状态，{1, 3, 2}
2. 执行Dequeue操作，返回1
3. 释放锁前，记录Dequeue后队列状态 {2, 3}

用上面三个变量来验证Dequeue是否成功。其中，队列的状态是由当前Dequeue之前的n个Enqueue及m个Dequeue合力形成的结果，这也是我为什么提出记录操作日志以及按日志复原验证的原因。

非侵入方法实现大概如下：

```go
type TestQueue struct {
     mux sync.Mutex
     q ConcurrentPriorityQueque[int]
}

func (q *TestQueue) Dequeue() (T, error) {
       q.mux.Lock()
       defer q.mux.UnLock()
      // 1.前置状态
      before :=q.q.toSlice()
      // 2.执行
      t := q.q.Dequeue()
      // 3.后置状态
      after := q.q.toSlice()
      // 4.用before，after来验证t是否满足优先级
}
```
老问题，并发在q.mux上而不是q.q.mux

2022-10-14 09:59 UTC, flycash commented
> 我们的目的是什么？测试并发场景下满足优先级队列的不变性。
> 
> 有哪些并发场景？
> 
> 1. 只在Enqueue方法上的并发，然后单协程调用Dequeue
> 2. 先当协程多次调用Go协程，然后只在Dequeue方法上的并发
> 3. 以1：1方式，形成Enqueue与Dequeue的并发
> 4. 以n：m方式，形成Enqueue与Dequeue的并发
> 
> 如果从头以TDD方式实现代码需要依次通过1～4，当代码完全实现后只保留测试4就可以了，前三个测试用例只是为了驱动出最终代码的中间检查点而已。
> 
> @flyhigher139
> 
> > 测试并发Enqueue，我是想先多个go rounte 执行入队操作，完成后，主携程把元素逐一出队，只要有序，可以认为并发入队没问题
> 
> 这个是上面的用例1，只测到了”只在Enqueue上的并发“场景。
> 
> > 测试并发Dequeue，主要是把出队元素写入channel时，可能会乱序，目前考虑2个方案：
> > 
> > 1. 出队元素el写入channel，单独起一个go routine，写入前，根据el大小，sleep一定时间，这个方式，每个el写入前的sleep时间要控制好，才能保证顺序。我目前想到的一些睡眠时间计算方法，均不能保证每次写入有序
> > 2. 加锁出队，这样虽然能保证顺序，但这让go routine在Dequeue前，已经通过锁变成有序的了，并不能达到测试并发dequeue的目的
> 
> 这个是上面的测试用例2，只测到了"只在Dequeue上的并发”场景。
> 
> 你依然需要补充“Enqueue与Dequeue之间形成并发”的场景。
> 
> @flycash
> 
> > 入队可以用你设计的方案。出队我觉得能不能用这种思路：虽然多个 goroutine 之间的顺序是不定，但是同一个 goroutine 取出来的元素，必然是按照优先级顺序排好了的。
> 
> 在并发场景下，即便是同一个协程Dequeue出的元素之间也不存在任何特定关系。
> 
> 举例，假设协程1～3希望将其ID入队并且仅有协程4执行出队操作，协程4可能得到如下序列：
> 
> 1. 1,2,3，协程1～3全部入队完成，协程4执行3次出队
> 2. 1,3,2，协程1，3先入队成功，而协程2在协程4（拿走1，3后阻塞超时）后才入队成功
> 3. 2,1,3
> 4. 2,3,1
> 5. 3,1,2
> 6. 3,2,1，协程3入队，协程4出队；协程2入队，协程4出队；协程1入队，协程4出队；
> 
> 我们不能假设Dequeue间元素的关系，因为Enqueue的调用时机以及入队元素的优先级总能破坏所谓的”出队元素间的优先级“条件。
> 
> 对于任意一个并发Dequeue操作，正确的检验方法是：
> 
> 1. 拿到锁后，记录当前队列状态，{1, 3, 2}
> 2. 执行Dequeue操作，返回1
> 3. 释放锁前，记录Dequeue后队列状态 {2, 3}
> 
> 用上面三个变量来验证Dequeue是否成功。其中，队列的状态是由当前Dequeue之前的n个Enqueue及m个Dequeue合力形成的结果，这也是我为什么提出记录操作日志以及按日志复原验证的原因。
> 
> 非侵入方法实现大概如下：
> 
> ```go
> type TestQueue struct {
>      mux sync.Mutex
>      q ConcurrentPriorityQueque[int]
> }
> 
> func (q *TestQueue) Dequeue() (T, error) {
>        q.mux.Lock()
>        defer q.mux.UnLock()
>       // 1.前置状态
>       before :=q.q.toSlice()
>       // 2.执行
>       t := q.q.Dequeue()
>       // 3.后置状态
>       after := q.q.toSlice()
>       // 4.用before，after来验证t是否满足优先级
> }
> ```
> 
> 老问题，并发在q.mux上而不是q.q.mux

先暂时实现比较好实现的吧，最后那个非侵入式的，我们暂时放弃。

我们暂时通过 review 的形式来确保并发没有问题：
- PriorityQueue 的可以确保单个 goroutine 状态下是对的；
- ConcurrentPriority 是一个装饰器，代码简单，那么我们可以通过检查所有方法上的加锁情况来达成目标

这样虽然没有真的测试到并发，但是也可以通过一种比较理论化的分析方法来证明确实没有并发问题

2022-10-14 12:08 UTC, longyue0521 requested changes

2022-10-14 12:17 UTC, longyue0521 commented
> 先暂时实现比较好实现的吧，最后那个非侵入式的，我们暂时放弃。
> 
> 我们暂时通过 review 的形式来确保并发没有问题：
> 
> * PriorityQueue 的可以确保单个 goroutine 状态下是对的；
> * ConcurrentPriority 是一个装饰器，代码简单，那么我们可以通过检查所有方法上的加锁情况来达成目标
> 
> 这样虽然没有真的测试到并发，但是也可以通过一种比较理论化的分析方法来证明确实没有并发问题

好的，还有个问题在不写并发测试的情况下，ConcurrentPriority要不要有测试文件？非并发场景下，其测试用例与PriorityQueue应该是一样的，即便没有测并发也要拷贝一份？

2022-10-14 15:01 UTC, flycash commented
> rentPriority要不要

Concurrent 的测试一下并发写入之后，单一 goroutine 读的就可以？这个比较好测试

2022-10-15 00:40 UTC, longyue0521 commented
> Concurrent 的测试一下并发写入之后，单一 goroutine 读的就可以？这个比较好测试

我看行，但要在测试中注明，这个测的是在Enqueue之间的并发而Enqueue与Dequeue之间是串行的。

2022-10-16 03:07 UTC, flyhigher139 commented on internal/queue/priority_queue.go
> +	p.shrinkIfNecessary()
这里讨论的问题是，对无界队列的扩缩容，没分歧；对有界队列看法不太一致

我的看法是，有界队列的capacity，没必要一步到位就分配好，可以逐步增长（优化：设个阈值，超过阈值逐步增长，不超过一步到位）

如果用户创建一个很大容量的有界队列，但大容量是偶尔遇到极端情况时用的，一步到位分配好会很浪费内存

capacity的作用是让队列有界，和扩缩容不是强关联的，属于优化点，我们没必要强加一条规则，让有界队列创建的时候，就必须把全部容量的内存都分配下来

2022-10-16 03:14 UTC, flyhigher139 commented on internal/queue/priority_queue.go
> +	p.shrinkIfNecessary()
> 另外一方面来说，如果顾虑到这是一个有界队列而不决定缩容，那么在最开始的时候直接把全部元素都创建出来看上去会不会就更加一致？

我之前那个NewPriorityQueueFromArray()，也多少考虑了这种情况。通过一个数组构造优先队列的，在数据全部出队前，可能就是当作滑动窗口用的

2022-10-16 07:18 UTC, longyue0521 commented on internal/queue/priority_queue.go
> +	p.shrinkIfNecessary()
我的核心观点是，只为用户提供机制，如何利用这些机制，在什么样的场景下使用这些机制，以及用的好与不好，用户自己负责。

我们能做的就是提供机制，给予一些指导即”最佳实践“。

我们提供了无界队列（自动扩缩容机制），也提供了有界队列（关闭自动扩缩容的机制）。

以Go语言自身为例，Go在slice上也提供了”关闭自动扩容“的机制——make([]T, 0, cap)，我们在ekit的slice包中的也要求这么做。作为Go的用户我们并没有抱怨这是Go的设计问题，反而自责这是我们没有使用最佳实践！

> 我的看法是，有界队列的capacity，没必要一步到位就分配好，可以逐步增长（优化：设个阈值，超过阈值逐步增长，不超过一步到位）

你设置的阀值再怎么优化，都会碰到我上面举例的问题——**因为队列中元素个数往复变化而导致扩缩容频繁触发**，只要有预设阀值在，不管其值的大小，这个问题就存在。

> 如果用户创建一个很大容量的有界队列，但大容量是偶尔遇到极端情况时用的，一步到位分配好会很浪费内存

为什么我们要操心浪费空间的问题呢？这难道不是用户该操心的吗？这难道不是用户没用对机制的问题吗？
用户应该根据自己的场景，甚至进行大量测试来确定对其最有效的capacity以避免内存浪费。我们在用`make([]T, 0,cap)`不就是这么做的吗？

> capacity的作用是让队列有界，和扩缩容不是强关联的，属于优化点，我们没必要强加一条规则，让有界队列创建的时候，就必须把全部容量的内存都分配下来

我们为什么还要在有界队列中要提供这种优化呢？用户可以使用无界队列，然后根据队列的长度来进行判断，以达到你说的这种效果。

Go的`make([]T, len)`提供了类似你说的这种优化，可是Go也提供了`make([]T, len, cap)`即关闭这种优化的方法。后者在高性能编程时被当作最佳实践，而我们却不提供这种最佳实践——关闭底层自动扩缩容机制的方法。

2022-10-17 01:56 UTC, flycash approved these changes

2022-10-17 01:56 UTC, flycash commented
@longyue0521 再看看？

2022-10-17 02:54 UTC, longyue0521 approved these changes

2022-10-17 02:54 UTC, longyue0521 commented on queue/concurrent_priority_queue_test.go
> +func TestConcurrentPriorityQueue_Dequeue(t *testing.T) {
向上面的注释那样说明，并发仅在Dequeue上，而Enqueue与Dequeue之间是串行的。

加一个todo：测试Enqueue之间并发、Dequeue之间并发、及Enqueue与Dequeue之间并发，三种并发同时存在在的场景。

2022-10-17 03:00 UTC, longyue0521 commented
@flycash 

看一下 https://github.com/gotomicro/ekit/pull/110#discussion_r996401420

我认为用户可以通过装饰器模式来封装`无界队列+维护cap`的方式自己实现**具备自动扩/缩容的有界队列**，但是对于用户需要**定长且不自动扩缩容的优先级队列**的需求无法满足。

2022-10-17 03:33 UTC, flycash commented on internal/queue/priority_queue.go
> +	p.shrinkIfNecessary()
我在这里并没有你那么担忧这种扩容缩容的抖动问题：
- 首先我们的缩容机制是留了扩容的余地的。比如说在 1000 以内，我们是在元素 1/4 的时候缩到一半，也就是还留出了两百多个空闲位置；
- 其次就是我认为不太可能出现 0 -> cap -> 0  之类的这种场景
- 再次就是我认为我们的有界和无界的概念只是对应于队列本身，而实现的细节里面的切片，我们其实还是可以考虑缩容来节省内存的，不管是有界还是无界。实际上，无界队列的应用场景倒也并不是真的说无界，而是说我不知道该设置多大比较好，或者说我预估我这里正常的需求可能是需要 1000 的容量，但是我出于兜底的目标，直接设置成无界的队列了。整体上来说无界队列是不怎么推荐使用的。
- 从我个人使用经验角度出发，队列的生产者的速率应该是 <= 消费者的速率的，否则迟早会遇到 BUG，要么是生产者放不进去，要么是无界队列导致内存炸掉。所以缩容更加多的是应付那种偶发性的情况，比如说突然来了一波需求，然后队列里面放了很多元素，后面它就会被消费完，然后这时候缩容可以保证内存使用量保持在一个比较低的效果
- 缩容应该算是一个内部机制，和 make 看起来又不太一样。即便 make 预估了容量，超出了容量它也是会扩容的

2022-10-17 03:37 UTC, longyue0521 commented on internal/queue/priority_queue.go
> +	p.shrinkIfNecessary()
`0->cap->0` 中的cap写错了，应该是内部设置的扩缩容的阀值

2022-10-17 03:45 UTC, longyue0521 commented on internal/queue/priority_queue.go
> +	p.shrinkIfNecessary()
make预估容量cap后，在[0, cap]之前是没有扩容，在大于cap后才会扩容。当前实现在[0, cap]之间就扩缩容了（cap大于阀值）。

2022-10-17 03:51 UTC, flycash commented on internal/queue/priority_queue.go
> +	p.shrinkIfNecessary()
@flyhigher139 想了一下，还是保持有界队列的语义吧。就是如果是有界队列，我们初始化好切片之后，后面就不会执行扩容和缩容了，在注释里面强调一下。如果是无界队列，我们就保持扩容和缩容的机制。

2022-10-17 03:53 UTC, flycash commented on internal/queue/priority_queue.go
> +	p.shrinkIfNecessary()
应该是：
- 如果创建的是有界队列，那么队列使用切片容量是固定的，既不会扩容也不会缩容
- 如果创建的是无界队列，那么队列使用的切片容量就不是固定的，我们会在合适的时机进行扩容或者缩容

2022-10-17 05:44 UTC, flyhigher139 commented on internal/queue/priority_queue.go
> +	p.shrinkIfNecessary()
> 应该是：
> 
> * 如果创建的是有界队列，那么队列使用切片容量是固定的，既不会扩容也不会缩容
> * 如果创建的是无界队列，那么队列使用的切片容量就不是固定的，我们会在合适的时机进行扩容或者缩容

好的，我按这个调整一下 @flycash @longyue0521

2022-10-17 13:29 UTC, flyhigher139 commented
@longyue0521 @flycash 扩缩容按上面说的完成了，新增了一个并发出入队的用例。这个用例为本地没报错，github报data race错误，我一时没看出问题在哪，能否帮我看看？

2022-10-17 13:45 UTC, flycash commented on queue/concurrent_priority_queue_test.go
> +	for _, tc := range testCases {
这个地方因为 tc 是一个引用，所以你后面开了 goroutine 之后，这个 tc 可能已经变掉了。你可以这样改：
```go
	for _, tt := range testCases {
		tc := tt
```
其它地方就是一样的了

2022-10-17 13:46 UTC, flycash reviewed
一般我都喜欢在开源软件里面用 go test -race 参数，所以你执行 make ut 命令就会得到报错

2022-10-17 15:12 UTC, longyue0521 requested changes

2022-10-17 15:12 UTC, longyue0521 commented on internal/queue/priority_queue.go
> +	if p.capacity < 1 {
抽取方法isBoundlessQueue

2022-10-17 15:12 UTC, longyue0521 commented on internal/queue/priority_queue.go
> +	if p.capacity > 0 {
使用`if !isBoundlessQueue()`替代

这个方法逻辑有问题，当无界队列`p.capacity <= 0`完成缩容后，`p.calCapacity()`会更新`p.capacity`使其从无界队列`p.capacity <= 0`变为”有界队列“`p.capacity > 0`此后不再缩容。

本质原因`p.capacity`承担的职责过多职责还互斥 —— 即表示有界或无界队列，又要实时反映队列容量

2022-10-17 15:15 UTC, flycash commented on internal/queue/priority_queue.go
> +	if p.capacity > 0 {
如果这么考虑的话，在初始化的时候设置一个标记位，反而比较不容易搞错

2022-10-17 15:19 UTC, longyue0521 commented
> 一般我都喜欢在开源软件里面用 go test -race 参数，所以你执行 make ut 命令就会得到报错

我喜欢尽可能地在test/subtest中使用`t.Parallel()`，以检查测试是否具有关联性以及并发问题（tc := tc那个问题一运行就可以发现了），再配合`go test -race`效果不错。

有没有那种场景不适合用`t.Parallel()`，如果没有或很少，咱们可以推荐`t.Parallel()`加速测试运行。

2022-10-17 15:21 UTC, flyhigher139 commented on internal/queue/priority_queue.go
> +	if p.capacity > 0 {
嗯，这里要再拆一下。改了扩缩容的逻辑后，再用calCapacity不合适了

2022-10-17 15:28 UTC, longyue0521 requested changes

2022-10-17 15:28 UTC, longyue0521 commented on internal/queue/priority_queue.go
> +	if p.capacity > 0 {
测试没有失败，这也是个问题。

这说明测试用例没有覆盖到这一场景，修改代码前先针对这个场景，写一个失败的测试用例以准确反映这个bug，接着修改代码通过那个失败的测试。

2022-10-18 02:34 UTC, flyhigher139 commented on internal/queue/priority_queue.go
> +	if p.capacity > 0 {
@longyue0521 
这里capacity > 0 直接返回了，参与缩容计算，capacity <= 0 时往下执行，会缩容，然后calCapacity那边，如果是原来是无界的，不会重新计算，还是无界的。

这个代码应该没bug，就是有点绕了
这个是顺着原来的逻辑修补了一下，把业务搞复杂了，这部分逻辑我简化一下重新写

2022-10-18 03:34 UTC, longyue0521 commented
@flycash @flyhigher139 

讨论一下，Cap()在无界队列与有界队列语义不一致的问题。

现在有界队列返回实际的cap，而有界队列返回的是0.

我认为既然提供了Cap()方法，就将底层自动扩容后的cap数实时地返回给用户，而不是返回一个固定的0. 这样有界队列与无界队列在Cap方法上的语义就一致了——实时反映队列的容量。

@flyhigher139 

关于强推的问题

除非在你提PR期间有其他人的PR先于你被Merge到了ekit，这时你需要将最新的ekit代码和你现在的代码通过`git pull --rebase upsteam dev` 融合再配合`git push --force`，否则不要用`git push --force` 。强推会使之前的review对话消失，无法进行增量review只能重新review，同时你也没办法将一个一个review对话作为检查清单，搞定一个resolve一个。

2022-10-18 05:37 UTC, flyhigher139 commented
我强推的，是那种比如现在本地比远端多3个commit，push之后，发现有点小问题漏掉了，比如改个注释之类的，就本地rebase一下重新强推，不会去刻意破坏时间线，你们review过的东西，我都不会rebase掉。

2022-10-18 05:38 UTC, flyhigher139 commented
> 关于强推的问题
> 
> 除非在你提PR期间有其他人的PR先于你被Merge到了ekit，这时你需要将最新的ekit代码和你现在的代码通过`git pull --rebase upsteam dev` 融合再配合`git push --force`（一般只需要一次），否则不要用`git push --force` 。强推会使之前的review对话消失，无法进行增量review只能重新review，同时你也没办法将一个一个review对话作为检查清单，搞定一个resolve一个。

我强推的，是那种比如现在本地比远端多3个commit，push之后，发现有点小问题漏掉了，比如改个注释之类的，就本地rebase一下重新强推，不会去刻意破坏时间线，你们review过的东西，我都不会rebase掉。 @longyue0521

2022-10-18 05:42 UTC, flyhigher139 commented
@longyue0521 
我昨晚强推一次，是开始不小心把那个扩缩容的逻辑写反了（无界的不缩容，有界的缩容），push之后才发现的，以为你们没review，马上改过来了。如果你在那5分钟内review过代码，那是我的锅

2022-10-18 05:50 UTC, flyhigher139 commented
> 讨论一下，Cap()在无界队列与有界队列语义不一致的问题。
> 
> 现在有界队列返回实际的cap，而有界队列返回的是0.
> 
> 我认为既然提供了Cap()方法，就将底层自动扩容后的cap数实时地返回给用户，而不是返回一个固定的0. 这样有界队列与无界队列在Cap方法上的语义就一致了——实时反映队列的容量。

这个是不是不用这么严格，就当作直接定义了0代表无界，大于0代表有界。
就像那个comparator，定义-1是小于，0是等于，1是大于，有界和无界我们在代码中的语意，就用大于0和等于0类界定
这么理解的话，就不算语意不一致了

2022-10-18 06:48 UTC, flycash commented
> > 讨论一下，Cap()在无界队列与有界队列语义不一致的问题。
> > 现在有界队列返回实际的cap，而有界队列返回的是0.
> > 我认为既然提供了Cap()方法，就将底层自动扩容后的cap数实时地返回给用户，而不是返回一个固定的0. 这样有界队列与无界队列在Cap方法上的语义就一致了——实时反映队列的容量。
> 
> @longyue0521 @flycash
> 
> 这个是不是不用这么严格，就当作直接定义了0代表无界，大于0代表有界。 就像那个comparator，定义-1是小于，0是等于，1是大于，有界和无界我们在代码中的语意，就用大于0和等于0类界定 这么理解的话，就不算语意不一致了

我也是赞同说返回 0 或者负数来表达无界的含义。

2022-10-18 06:56 UTC, flycash commented on queue/concurrent_priority_queue.go
> +	queue.PriorityQueue[T]
这个地方不能用组合，因为这样用户可以绕开你的锁，直接访问 PriorityQueue 上的元素

2022-10-18 06:56 UTC, flycash requested changes
@longyue0521 还有没有别的问题

2022-10-18 06:59 UTC, flycash commented
返回 0 或者 -1 来表达一个特殊含义，这算是一个源远流长的传统了。如果直接返回切片的容量，那么用户其实分辨不出来这个究竟是有界的，然后容量是这个值，还是说这个是无界的，但是目前容量是这个值。

另外， Cap 这个方法，在 LinkedList 里面是返回了 Len()，看起来也不太合适

2022-10-18 09:22 UTC, longyue0521 requested changes

2022-10-18 09:22 UTC, longyue0521 commented on queue/concurrent_priority_queue_test.go
> +					go func(i int) {
ConcurrentPriorityQueue的测试用例中，开启协程的数量普遍偏多，尤其是这里每个测试用例开启的协程数至少5000个

2022-10-18 09:36 UTC, longyue0521 commented
> > > 讨论一下，Cap()在无界队列与有界队列语义不一致的问题。
> > > 现在有界队列返回实际的cap，而有界队列返回的是0.
> > > 我认为既然提供了Cap()方法，就将底层自动扩容后的cap数实时地返回给用户，而不是返回一个固定的0. 这样有界队列与无界队列在Cap方法上的语义就一致了——实时反映队列的容量。
> > 
> > 
> > @longyue0521 @flycash
> > 这个是不是不用这么严格，就当作直接定义了0代表无界，大于0代表有界。 就像那个comparator，定义-1是小于，0是等于，1是大于，有界和无界我们在代码中的语意，就用大于0和等于0类界定 这么理解的话，就不算语意不一致了
> 
> 我也是赞同说返回 0 或者负数来表达无界的含义。

在Cap方法上加一个注释吧，大概就是 `无界队列返回0，有界队列返回创建队列时指定的值`

2022-10-18 12:00 UTC, flycash commented on queue/concurrent_priority_queue_test.go
> +					go func(i int) {
5000个的话确实有点多，github action 的资源跑起来应该稍微慢一点

2022-10-18 14:26 UTC, flyhigher139 commented
> > > > 讨论一下，Cap()在无界队列与有界队列语义不一致的问题。
> > > > 现在有界队列返回实际的cap，而有界队列返回的是0.
> > > > 我认为既然提供了Cap()方法，就将底层自动扩容后的cap数实时地返回给用户，而不是返回一个固定的0. 这样有界队列与无界队列在Cap方法上的语义就一致了——实时反映队列的容量。
> > > 
> > > 
> > > @longyue0521 @flycash
> > > 这个是不是不用这么严格，就当作直接定义了0代表无界，大于0代表有界。 就像那个comparator，定义-1是小于，0是等于，1是大于，有界和无界我们在代码中的语意，就用大于0和等于0类界定 这么理解的话，就不算语意不一致了
> > 
> > 
> > 我也是赞同说返回 0 或者负数来表达无界的含义。
> 
> 在Cap方法上加一个注释吧，大概就是 `无界队列返回0，有界队列返回创建队列时指定的值`

好的～

2022-10-19 00:47 UTC, flyhigher139 commented on queue/concurrent_priority_queue_test.go
> +					go func(i int) {
要不数量改成这个？

```go
func TestConcurrentPriorityQueue_EnqueueDequeue(t *testing.T) {
	testCases := []struct {
		name    string
		enqueue int
		dequeue int
		remain  int
	}{
		{
			name:    "出队等于入队",
			enqueue: 50,
			dequeue: 50,
			remain:  0,
		},
		{
			name:    "出队小于入队",
			enqueue: 50,
			dequeue: 40,
			remain:  10,
		},
		{
			name:    "出队大于入队",
			enqueue: 50,
			dequeue: 60,
			remain:  -10,
		},
	}
```

2022-10-19 00:53 UTC, longyue0521 requested changes

2022-10-19 00:53 UTC, longyue0521 commented on queue/concurrent_priority_queue_test.go
> +					go func(i int) {
我觉得50左右也可以，别忘了给并发安全和非并发安全队列的Cap加注释

2022-10-19 02:08 UTC, flyhigher139 commented on queue/concurrent_priority_queue_test.go
> +					go func(i int) {
> 我觉得50左右也可以，别忘了给并发安全和非并发安全队列的Cap加注释

好～ 已调整

2022-10-19 02:22 UTC, longyue0521 approved these changes

2022-10-19 06:34 UTC, flycash approved these changes

2022-10-19 06:35 UTC, merged