queue:使用list包中的LinkedList实现并发阻塞链式队列
gotomicro/ekit pull request #122
Opened 2022-11-24 12:20 UTC by kangdan6

再queue中增加并发阻塞链式队列

2022-11-24 13:34 UTC, kangdan6 commented
这是来自QQ邮箱的自动回复邮件。
 
您好，您的邮件已收到。我会尽快给您回复。

2022-11-24 13:40 UTC, flycash requested changes

2022-11-24 13:40 UTC, flycash commented on queue/concurrent_linked_blocking_queue.go
> +// 只有在被唤醒之后我们才会再次检测是否已经超时或者取消
我们已经实现了超时控制，把我在另外两个队列的注释修改过来

2022-11-24 13:40 UTC, flycash commented on queue/concurrent_linked_blocking_queue.go
> +// 核心在于当 goroutine 被阻塞之后，再无法监听超时或者取消
同样，这里应该是实现了

2022-11-24 13:40 UTC, flycash commented on queue/concurrent_linked_blocking_queue_test.go
> +			// 入队之后就满了，恰好放在中间
你没这个用例，因为你不是 ring buffer

2022-11-24 13:40 UTC, flycash commented on queue/concurrent_linked_blocking_queue_test.go
> +			// 元素本身就是零值
你也没这个用例，因为你不是 ring buffer

2022-11-24 13:40 UTC, flycash commented on queue/concurrent_linked_blocking_queue_test.go
> +			name: "dequeue and empty middle",
你也没这个用例

2022-11-24 13:40 UTC, flycash commented on queue/concurrent_linked_blocking_queue.go
> +		linkedlist: list.NewLinkedListOf[T]([]T{}),
直接使用 NewLinkedList，因为这里不需要初始化元素

2022-11-24 13:40 UTC, flycash commented on queue/concurrent_linked_blocking_queue.go
> +// ConcurrentLinkBlockingQueue 有界并发阻塞队列
这里，要改造一下：
- 如果 maxSize 是正数。那么就是有界并发阻塞队列
- 如果不是，就是无界并发阻塞队列。在这种情况下，入队永远能够成功

LinkedList 的设计，就是为了解决无界的问题。因为在 ringbuffer 里面，我们都是一次初始化好所有的内存，所以不能搞无界的。而且切片扩容性能也比较差。

在做了这种改进之后，你要重新设计测试用例。有界阻塞的和 arrayBlocking 差不多，要额外测试在无界的情况下，添加元素。

无界有界，应该不会影响你的出队代码

2022-11-27 11:19 UTC, kangdan6 commented on queue/concurrent_linked_blocking_queue_test.go
> +			// 元素本身就是零值
这个和是不是ring buffer没有关系吧，链表为啥就不需要验证元素都是零值的情况呢？

2022-11-27 12:16 UTC, longyue0521 commented on queue/concurrent_linked_blocking_queue_test.go
> +			// 元素本身就是零值
单元测试时推荐黑盒测试（功能测试/接口测试）为主，白盒测试（结构测试/代码测试/基于实现测试）为辅助。

从并发阻塞队列的**功能**角度来设计测试用例时，元素int的零值和非零值、极值等都同属于一个等价类划分——它们发现代码bug的能力是一样的。所以你在设计ConcurrentLinkBlockingQueue[int]的测试用例时，应该聚焦于ConcurrentLinkBlockingQueue的API/接口，在此过程中可以随便传元素的值（用不用零值都可以）。但是像这样单独针对元素零值写一个测试用例就有些突兀，因为ConcurrentLinkBlockingQueue[int]只关心有“有一个元素要入队”，“有一个元素要出队”，至于这个元素的具体值是多少它并不关心。

按理说ring buffer的实现从功能测试（黑盒测试）角度设计测试用例也不应该关心元素是否为零值，之所以加这个测试用例与ring buffer的实现有关（白盒测试），你去看ring buffer的实现就会发现——预分配的空间默认存储的是元素的零值，出队非零值的元素时要将出队元素所在的那个位置用零值覆盖。元素的零值在ring buffer内部实现中有了特殊的意义所以要单独测一下（白盒测试作为辅助/补充）。

你的实现中并没有赋予元素零值特殊的意义所以不用针对元素零值单独设计测试用例。

2022-11-28 04:46 UTC, kangdan6 commented on queue/concurrent_linked_blocking_queue_test.go
> +			// 元素本身就是零值
好的，谢谢大佬

2022-11-28 06:52 UTC, flycash commented on queue/concurrent_linked_blocking_queue.go
> +// 容量会在最开始的时候就初始化好
你这个没有容量初始化的问题……在 Array 那里我是指内存一开始就分配好，链表的话是没这个烦恼的

2022-11-28 06:55 UTC, flycash commented on queue/concurrent_linked_blocking_queue.go
> +// 容量会在最开始的时候就初始化好
所以删了这句话

2022-11-28 06:57 UTC, flycash commented
<img width="777" alt="image" src="https://user-images.githubusercontent.com/9923838/204212898-e7418ec3-06e6-4bda-86bc-e9cb742a9193.png">
看起来那个十万 Goroutine 的测试跑不了，CI 资源有限，删了吧。或者你改成十个 goroutine 每个写入 1000 个差不多了。

另外点进去 DeepSource:Go 这个action，点进去 Details 看看，修复一下问题。应该只是在
```go
// ConcurrentLinkBlockingQueue 基于链表的并发阻塞队列
```
这样就可以了

2022-11-28 09:09 UTC, flycash approved these changes

2022-11-28 09:09 UTC, merged