queue: 基于semaphore的并发阻塞队列实现
gotomicro/ekit pull request #129
Opened 2022-12-07 16:52 UTC by uzziahlin

-主要改造了concurrent_array_blocking_queue的实现，将原来基于cond的实现改造成基于semaphore的实现

2022-12-08 00:12 UTC, longyue0521 requested changes

2022-12-08 00:12 UTC, longyue0521 commented on queue/concurrent_array_blocking_queue.go
> +	c.dqSema.Release(1)
2. capacity = 1, g1 Enqueue成功, 释放一个位置允许g3调用Dequeue; 但此时偏偏没有g3,有的是g2再次调用Enqueue成功,又释放了一个“位置”——触发panic

2022-12-08 00:12 UTC, longyue0521 commented on queue/concurrent_array_blocking_queue.go
> +		return res, ctx.Err()
3. capacity = 1, g1 Enqueue(ctx, 1) 成功; g3 Dequeue,但在117处超时退出; g4 Dequeue 发现永久阻塞或超时退出.
   
本质问题: xxSema究竟表示什么? 谁, 在什么时机, 来维护 xxSema所表示的内容/条件

2022-12-08 00:59 UTC, flyhigher139 commented on queue/concurrent_array_blocking_queue.go
> +	dqSema := semaphore.NewWeighted(int64(capacity))
semaphore可以取代mutex，但取代不了condition

下面代码是分别用2个semaphore控制入队和出队，相当于分别给入队和出队上了2把锁，而不是用一把锁让并发互斥
所以下面代码应该是做不到并发安全的

condition是在同一把锁下，实现了并发之间的wait...notify机制

这段代码感觉有些问题

2022-12-08 01:07 UTC, uzziahlin commented on queue/concurrent_array_blocking_queue.go
> +	c.dqSema.Release(1)
这个时候g2没有办法再次Enqueue，因为eqSema没有g去Release，g2进不来

2022-12-08 01:08 UTC, uzziahlin commented on queue/concurrent_array_blocking_queue.go
> +		return ctx.Err()
这里是否可以考虑如果超时，当前goroutine主动归还信号量

2022-12-08 01:16 UTC, uzziahlin commented on queue/concurrent_array_blocking_queue.go
> +	dqSema := semaphore.NewWeighted(int64(capacity))
在这里semaphore的锁并不是用来控制并发，这里只是借助sema的特性，使得eqSema表示队列可入队的容量，dqSema表示队列可消费的元素个数，逻辑上保证eqSema和dqSema的容量之和时刻保持为队列的最大容量，这个逻辑由队列本身维护的mutex来保证。

2022-12-08 01:42 UTC, longyue0521 commented on queue/concurrent_array_blocking_queue.go
> +		return ctx.Err()
可以

2022-12-08 01:43 UTC, longyue0521 commented on queue/concurrent_array_blocking_queue.go
> +	c.dqSema.Release(1)
你说的对 这个case 你忽略

2022-12-08 01:44 UTC, longyue0521 commented on queue/concurrent_array_blocking_queue.go
> +		return res, ctx.Err()
那就用eqSema和dqSema所表示的“不变性”的内容命名,这样可读性更好,更容易理解代码

2022-12-08 02:18 UTC, longyue0521 commented on queue/concurrent_array_blocking_queue.go
> +	dqSema := semaphore.NewWeighted(int64(capacity))
我的理解是sema在某种程度上是用来控制最大并发数的,因为capacity规定必须为正数,所以恰好可以将最大值定义为capacity. 超过capacity个的并发调用就让其阻塞并可以超时. mutex用来保护临界区的data, 我觉得没什么问题,就是sema内部实现每个waiter一个ready chan, 性能可能会有点差.

让 @flycash 看一下

2022-12-08 02:58 UTC, uzziahlin commented on queue/concurrent_array_blocking_queue.go
> +		return res, ctx.Err()
这个命名确实是个问题，不容易理解，我目前想的是用EnqueueCap和DequeueCap来命名，是否会更具可读性？

2022-12-08 13:42 UTC, flycash commented
从逻辑上来看并不会引起什么问题，之前我还担心引发死锁的问题，目前来看也不会。
我简单总结一下两种实现的问题：
- 之前我的实现，问题就出在广播这里。意味着它会唤醒所有的 goroutine，但是最终只有一个 goroutine 拿到数据，其它的都会再次陷入沉睡。并发数越高，问题越大；
- 而改成 semaphore 之后，不存在广播的问题，但是问题变成了会有非常多的 channel，也就是问题出在 channel 这个开销了。之前我们在设计延时队列的时候，也考虑过类似的设计。容量越大，内存开支越大；

前者是一个 CPU 的问题，也就是 goroutine 被唤醒然后又沉睡；后者更加像是一个内存分配的问题，因为 semaphore 一次只会唤醒一个。

你们总体上倾向于哪种？

2022-12-08 13:43 UTC, flycash commented
要是问题你解决了就记得点一下 resolve

2022-12-09 09:09 UTC, flycash commented
我还是把这个合并进去了。核心就是：
- 广播的实现，其实也会有内存问题。因为每一次调用广播，都是要创建一个 channel，所以实际上相比之下我觉得这个实现可能会更加好

2022-12-09 09:09 UTC, merged

2022-12-09 11:48 UTC, longyue0521 commented
> 我还是把这个合并进去了。核心就是：
> 
> * 广播的实现，其实也会有内存问题。因为每一次调用广播，都是要创建一个 channel，所以实际上相比之下我觉得这个实现可能会更加好

广播的实现,channel与监听的协程比是1:N,semaphore的实现是1:1. 我好奇我们所担心的channel开销多低有多大.

所以我修改了一下semaphore包内semaphore_bench_test.go的BenchmarkAcquireSeq基准测试 发现一个不太符合我们直觉的现象——开销为0, 我们担心的channel创建开销并不存在, 不知道是我Go版本的问题?(我用的是1.19)还是我测的不对?或者真的就是没有这个开销.

我记得在课程也出现过这个现象,——开销就是为0

```
goos: darwin
goarch: amd64
cpu: Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
BenchmarkAcquireSeq
BenchmarkAcquireSeq/Weighted-acquire-1-1-1
BenchmarkAcquireSeq/Weighted-acquire-1-1-1-16         	35998287	        28.93 ns/op	       0 B/op	       0 allocs/op
BenchmarkAcquireSeq/Weighted-tryAcquire-1-1-1
BenchmarkAcquireSeq/Weighted-tryAcquire-1-1-1-16      	41879769	        27.04 ns/op	       0 B/op	       0 allocs/op
BenchmarkAcquireSeq/semChan-acquire-1-1-1
BenchmarkAcquireSeq/semChan-acquire-1-1-1-16          	24851871	        45.41 ns/op	       0 B/op	       0 allocs/op
BenchmarkAcquireSeq/semChan-tryAcquire-1-1-1
BenchmarkAcquireSeq/semChan-tryAcquire-1-1-1-16       	26257648	        43.67 ns/op	       0 B/op	       0 allocs/op
BenchmarkAcquireSeq/Weighted-acquire-2-1-1
BenchmarkAcquireSeq/Weighted-acquire-2-1-1-16         	43242860	        28.76 ns/op	       0 B/op	       0 allocs/op
BenchmarkAcquireSeq/Weighted-tryAcquire-2-1-1
BenchmarkAcquireSeq/Weighted-tryAcquire-2-1-1-16      	45190890	        26.94 ns/op	       0 B/op	       0 allocs/op
BenchmarkAcquireSeq/semChan-acquire-2-1-1
BenchmarkAcquireSeq/semChan-acquire-2-1-1-16          	28821824	        43.82 ns/op	       0 B/op	       0 allocs/op
BenchmarkAcquireSeq/semChan-tryAcquire-2-1-1
BenchmarkAcquireSeq/semChan-tryAcquire-2-1-1-16       	27721966	        44.96 ns/op	       0 B/op	       0 allocs/op
BenchmarkAcquireSeq/Weighted-acquire-16-1-1
BenchmarkAcquireSeq/Weighted-acquire-16-1-1-16        	44187162	        27.92 ns/op	       0 B/op	       0 allocs/op
BenchmarkAcquireSeq/Weighted-tryAcquire-16-1-1
BenchmarkAcquireSeq/Weighted-tryAcquire-16-1-1-16     	42152251	        26.67 ns/op	       0 B/op	       0 allocs/op
BenchmarkAcquireSeq/semChan-acquire-16-1-1
BenchmarkAcquireSeq/semChan-acquire-16-1-1-16         	28329458	        43.75 ns/op	       0 B/op	       0 allocs/op
BenchmarkAcquireSeq/semChan-tryAcquire-16-1-1
BenchmarkAcquireSeq/semChan-tryAcquire-16-1-1-16      	28469403	        43.39 ns/op	       0 B/op	       0 allocs/op
BenchmarkAcquireSeq/Weighted-acquire-128-1-1
BenchmarkAcquireSeq/Weighted-acquire-128-1-1-16       	43165717	        28.53 ns/op	       0 B/op	       0 allocs/op
BenchmarkAcquireSeq/Weighted-tryAcquire-128-1-1
BenchmarkAcquireSeq/Weighted-tryAcquire-128-1-1-16    	44714756	        27.37 ns/op	       0 B/op	       0 allocs/op
BenchmarkAcquireSeq/semChan-acquire-128-1-1
BenchmarkAcquireSeq/semChan-acquire-128-1-1-16        	28282513	        43.44 ns/op	       0 B/op	       0 allocs/op
BenchmarkAcquireSeq/semChan-tryAcquire-128-1-1
BenchmarkAcquireSeq/semChan-tryAcquire-128-1-1-16     	27839509	        42.90 ns/op	       0 B/op	       0 allocs/op
BenchmarkAcquireSeq/Weighted-acquire-2-2-1
BenchmarkAcquireSeq/Weighted-acquire-2-2-1-16         	45012165	        29.21 ns/op	       0 B/op	       0 allocs/op
BenchmarkAcquireSeq/Weighted-tryAcquire-2-2-1
BenchmarkAcquireSeq/Weighted-tryAcquire-2-2-1-16      	46323514	        26.54 ns/op	       0 B/op	       0 allocs/op
BenchmarkAcquireSeq/semChan-acquire-2-2-1
BenchmarkAcquireSeq/semChan-acquire-2-2-1-16          	14097836	        81.13 ns/op	       0 B/op	       0 allocs/op
BenchmarkAcquireSeq/semChan-tryAcquire-2-2-1
BenchmarkAcquireSeq/semChan-tryAcquire-2-2-1-16       	14871572	        80.53 ns/op	       0 B/op	       0 allocs/op
BenchmarkAcquireSeq/Weighted-acquire-16-2-8
BenchmarkAcquireSeq/Weighted-acquire-16-2-8-16        	 5685538	       212.2 ns/op	       0 B/op	       0 allocs/op
BenchmarkAcquireSeq/Weighted-tryAcquire-16-2-8
BenchmarkAcquireSeq/Weighted-tryAcquire-16-2-8-16     	 5542713	       214.1 ns/op	       0 B/op	       0 allocs/op
BenchmarkAcquireSeq/semChan-acquire-16-2-8
BenchmarkAcquireSeq/semChan-acquire-16-2-8-16         	 1754398	       634.1 ns/op	       0 B/op	       0 allocs/op
BenchmarkAcquireSeq/semChan-tryAcquire-16-2-8
BenchmarkAcquireSeq/semChan-tryAcquire-16-2-8-16      	 1889330	       636.1 ns/op	       0 B/op	       0 allocs/op
BenchmarkAcquireSeq/Weighted-acquire-128-2-64
BenchmarkAcquireSeq/Weighted-acquire-128-2-64-16      	  730034	      1708 ns/op	       0 B/op	       0 allocs/op
BenchmarkAcquireSeq/Weighted-tryAcquire-128-2-64
BenchmarkAcquireSeq/Weighted-tryAcquire-128-2-64-16   	  687126	      1731 ns/op	       0 B/op	       0 allocs/op
BenchmarkAcquireSeq/semChan-acquire-128-2-64
BenchmarkAcquireSeq/semChan-acquire-128-2-64-16       	  212145	      5204 ns/op	       0 B/op	       0 allocs/op
BenchmarkAcquireSeq/semChan-tryAcquire-128-2-64
BenchmarkAcquireSeq/semChan-tryAcquire-128-2-64-16    	  209847	      5137 ns/op	       0 B/op	       0 allocs/op
BenchmarkAcquireSeq/Weighted-acquire-2-1-2
BenchmarkAcquireSeq/Weighted-acquire-2-1-2-16         	22397176	        53.51 ns/op	       0 B/op	       0 allocs/op
BenchmarkAcquireSeq/Weighted-tryAcquire-2-1-2
BenchmarkAcquireSeq/Weighted-tryAcquire-2-1-2-16      	22724324	        55.06 ns/op	       0 B/op	       0 allocs/op
BenchmarkAcquireSeq/semChan-acquire-2-1-2
BenchmarkAcquireSeq/semChan-acquire-2-1-2-16          	13908943	        85.60 ns/op	       0 B/op	       0 allocs/op
BenchmarkAcquireSeq/semChan-tryAcquire-2-1-2
BenchmarkAcquireSeq/semChan-tryAcquire-2-1-2-16       	13333144	        84.69 ns/op	       0 B/op	       0 allocs/op
BenchmarkAcquireSeq/Weighted-acquire-16-8-2
BenchmarkAcquireSeq/Weighted-acquire-16-8-2-16        	20401054	        53.34 ns/op	       0 B/op	       0 allocs/op
BenchmarkAcquireSeq/Weighted-tryAcquire-16-8-2
BenchmarkAcquireSeq/Weighted-tryAcquire-16-8-2-16     	20004867	        53.01 ns/op	       0 B/op	       0 allocs/op
BenchmarkAcquireSeq/semChan-acquire-16-8-2
BenchmarkAcquireSeq/semChan-acquire-16-8-2-16         	 1970730	       611.3 ns/op	       0 B/op	       0 allocs/op
BenchmarkAcquireSeq/semChan-tryAcquire-16-8-2
BenchmarkAcquireSeq/semChan-tryAcquire-16-8-2-16      	 1941979	       647.4 ns/op	       0 B/op	       0 allocs/op
BenchmarkAcquireSeq/Weighted-acquire-128-64-2
BenchmarkAcquireSeq/Weighted-acquire-128-64-2-16      	21613214	        55.71 ns/op	       0 B/op	       0 allocs/op
BenchmarkAcquireSeq/Weighted-tryAcquire-128-64-2
BenchmarkAcquireSeq/Weighted-tryAcquire-128-64-2-16   	23113664	        54.97 ns/op	       0 B/op	       0 allocs/op
BenchmarkAcquireSeq/semChan-acquire-128-64-2
BenchmarkAcquireSeq/semChan-acquire-128-64-2-16       	  251800	      4888 ns/op	       0 B/op	       0 allocs/op
BenchmarkAcquireSeq/semChan-tryAcquire-128-64-2
BenchmarkAcquireSeq/semChan-tryAcquire-128-64-2-16    	  236616	      4836 ns/op	       0 B/op	       0 allocs/op
BenchmarkAcquireSeq/Weighted-acquire-1000000-1-100000
BenchmarkAcquireSeq/Weighted-acquire-1000000-1-100000-16         	     436	   2641038 ns/op	       0 B/op	       0 allocs/op
BenchmarkAcquireSeq/Weighted-tryAcquire-1000000-1-100000
BenchmarkAcquireSeq/Weighted-tryAcquire-1000000-1-100000-16      	     432	   2735235 ns/op	       0 B/op	       0 allocs/op
BenchmarkAcquireSeq/semChan-acquire-1000000-1-100000
BenchmarkAcquireSeq/semChan-acquire-1000000-1-100000-16          	     270	   4184122 ns/op	       0 B/op	       0 allocs/op
BenchmarkAcquireSeq/semChan-tryAcquire-1000000-1-100000
BenchmarkAcquireSeq/semChan-tryAcquire-1000000-1-100000-16       	     280	   4395449 ns/op	       0 B/op	       0 allocs/op
PASS
```