mapx: HashMap 增加 Keys 和 Values 方法
gotomicro/ekit pull request #141
Opened 2023-01-06 09:25 UTC by heroyf

2023-01-07 02:37 UTC, longyue0521 requested changes

2023-01-07 02:37 UTC, longyue0521 commented on mapx/hashmap.go
> +	// 默认初始化结果大小为hashmap的容量大小，也就是假设hash没有冲突，每个bucket存在一个元素
1. Go中len(map)指的是map中定义的key的个数并非map的容量大小
```go
mp1 := make(map[int]string)
mp2 := make(map[int]string, 100)
assert.True(t, len(mp1) == len(mp2))
```
2. 如果len(map)指的是容量,那么通过下方NewHashMap创建一个容量为100的hashmap,接着直接调用Keys()应该返回一个长度为100的[]Hashable{....},而不是len([]Hashable{}) == 0

3. 去掉这个注释

2023-01-07 02:37 UTC, longyue0521 commented on mapx/hashmap.go
> +// 注意：value 的顺序是随机。
修改同上

2023-01-07 02:37 UTC, longyue0521 commented on mapx/hashmap.go
> +	// 默认初始化结果大小为hashmap的容量大小，也就是假设hash没有冲突，每个bucket存在一个元素
去掉这个注释

2023-01-07 02:37 UTC, longyue0521 commented on mapx/hashmap.go
> +		res = append(res, bucketNode.value)
1. 注释中Spec宣称“Values 返回 hashmap 里面的所有的 value”,实现中却只返回链表的头,Spec与实现不相符
2. 请与 @flycash 确认需求重新实现
3. 修改相应测试

2023-01-07 02:37 UTC, longyue0521 commented on mapx/hashmap.go
> +		res = append(res, bucketNode.value)
1. 注释中Spec宣称“Values 返回 hashmap 里面的所有的 value”,实现中却只返回链表的头,Spec与实现不相符
2. 请与 @flycash 确认需求重新实现
3. 修改相应测试

2023-01-07 02:37 UTC, longyue0521 commented on mapx/hashmap.go
> +		res = append(res, bucketNode.value)
1. 注释中Spec宣称“Values 返回 hashmap 里面的所有的 value”,实现中却只返回链表的头,Spec与实现不相符
2. 请与 @flycash 确认需求重新实现
3. 修改相应测试

2023-01-07 02:37 UTC, longyue0521 commented on mapx/hashmap_test.go
> +			wantValues: []int{11},
1. Values返回的是随机的,那么这里也不应该假定为11,有可能为1
2. 确认好需求后修改这里

2023-01-07 02:37 UTC, longyue0521 commented on mapx/hashmap_test.go
> +			wantValues: []int{11, 20},
同上

2023-01-07 12:58 UTC, heroyf commented on mapx/hashmap.go
> +	// 默认初始化结果大小为hashmap的容量大小，也就是假设hash没有冲突，每个bucket存在一个元素
感谢纠正，确实没做实验产生理解偏差了☺

2023-01-07 13:25 UTC, heroyf commented on mapx/hashmap_test.go
> +			wantValues: []int{11},
我理解这里应该只有11，因为testData的Equals方法为：id相同时，就判定为相同。
<img width="571" alt="image" src="https://user-images.githubusercontent.com/21223279/211152955-aea3fb39-c318-464f-9e06-9d577d73e186.png">
这里两个key的id一致，会导致Put的时候认为相同的key，会直接覆盖

2023-01-07 15:02 UTC, longyue0521 commented on mapx/hashmap_test.go
> +			wantValues: []int{11},
1. 你说的对,是我看错了,我将第二个`testHashMap.Put(testData{id: 1}, 11)` 中的`testData{id: 1}`看成了`testData{id: 11}`
2. 正如我上面注释提到的,在你确认好Values()的需求后, 你需要添加这样一个测试用例——"same code of different keys / key collision",他们在Code()层面上是相等的,value会被挂链处理即一个bucket中有多个value.注意一下,挂链的方式可能是11->1也可能是1->11,你Values()当前的实现是只返回队头(可能是11),如果Put方法中挂链的方式变为是1->11,你的测试就不能通过了.
3. 可以简化一下Equels方法直接用`return t.id == val.id`,替换倒数四行
4. 既然有newTestData(id)这个方法,就统一一下用这个方法初始化吧

2023-01-07 15:03 UTC, longyue0521 commented on mapx/hashmap_test.go
> +			wantValues: []int{11, 20},
确认需求后,添加一个“multiple keys collision"

2023-01-07 15:07 UTC, longyue0521 commented on mapx/hashmap.go
> +		res = append(res, bucketNode.value)
其实这里,应该将所有value装入res, 因为key是根据Code()方法来找bucket的,两个不同的key但具有相同的Code,在调用Values()的时候就应该返回两个value

2023-01-08 08:07 UTC, heroyf commented
@longyue0521 已修复，添加了hash一致，但是equal不一致的测试场景，可以有空再帮忙看下

2023-01-08 14:24 UTC, flycash commented
@heroyf 麻烦把这个合并请求加进去 .CHANGELOG 里面，放在 developing 下面，顺序不要紧 😄

2023-01-08 14:25 UTC, flycash commented
@longyue0521 觉得没问题记得 approve 一下

2023-01-09 04:07 UTC, longyue0521 requested changes

2023-01-09 04:07 UTC, longyue0521 commented on mapx/hashmap_test.go
> +			name: "same code of different keys",
我给的这个用例名不太好,我想表达的是不同的key在hashcode层面是相同的,他们落入同一个bucket. 

改为 single key collision 吧

2023-01-09 04:07 UTC, longyue0521 commented on mapx/hashmap_test.go
> +					err := testHashMap.Put(newTestData(val), val)
multiple keys collision 指的是map内存在多个key冲突——这里的多个key是指的应该是(key1, val1) (key2,val2) 在同一个bucket中,(key3,val3)(key4, val4)再另外一个bucket中——至少有两个bucket中存在多个node.

1, 2,10,20只能使map处于有一个key冲突的状态即10和20在一个bucket中,1和2在各自的bucket中

2023-01-09 06:28 UTC, heroyf commented on mapx/hashmap_test.go
> +					err := testHashMap.Put(newTestData(val), val)
```go
for _, val := range []int{1, 2} {
  // 插入的node为(1,1)(10,10)(2,2)(20,20)
  err := testHashMap.Put(newTestData(val), val)
  require.NoError(t, err)
  err = testHashMap.Put(newTestData(val*10), val*10)
  require.NoError(t, err)
}
```
看了一下描述应该没理解错？这个测试用例是在验证多个桶存在多个node的场景
hashmap中会被放入4条数据

- (1,1)(10,10)计算code后落在了hash为1的bucket中

- (2,2)(20,20)计算code后落在了hash为2的bucket中

-- 即有两个bucket存在两个node，可能注释导致理解不清晰，我已经更新了注释😁

2023-01-09 07:41 UTC, longyue0521 requested changes

2023-01-09 07:41 UTC, longyue0521 commented on mapx/hashmap_test.go
> +					err := testHashMap.Put(newTestData(val), val)
1. 不是注释的问题,代码已经表明意图可以把注释去掉
2. 你可以运行下面的断言看看.
  - 根据你的描述,前两个应该通过,最后一个应该报错.
  - 根据我的描述,前两个应该报错,最后一个应该通过.

```go
assert.Equal(t, newTestData(1).Code(), newTestData(10).Code())
assert.Equal(t, newTestData(2).Code(), newTestData(20).Code())
assert.Equal(t, newTestData(10).Code(), newTestData(20).Code())
```

2023-01-09 08:04 UTC, heroyf commented on mapx/hashmap_test.go
> +					err := testHashMap.Put(newTestData(val), val)
我傻了，记成除以了，已经修复

2023-01-09 08:21 UTC, longyue0521 approved these changes

2023-01-09 08:22 UTC, longyue0521 commented
@flycash 有空看一下

2023-01-10 03:39 UTC, flycash approved these changes

2023-01-10 07:05 UTC, merged