TreeMap的简单实现
gotomicro/ekit pull request #142
Opened 2023-01-08 07:43 UTC by yzicheng

主要是参考Java TreeMap的思路实现。Key类型采用的是ekit.RealNumber,比较器采用的ekit.Comparator

2023-01-08 14:38 UTC, flycash reviewed
@longyue0521 @flyhigher139 麻烦帮忙验证一下测试用例。
红黑树因为涉及旋转调整树结构的过程，我一个人有点麻。

@yzicheng 这个红黑树的测试比较难验证，所以我要多花一点时间。我需要画个图来确认每一个测试用例，看代码我很难看出来代码有没有破绽。

2023-01-08 14:38 UTC, flycash commented on mapx/treemap.go
> +type TreeMap[Key ekit.RealNumber, Val any] struct {
这里面我不太想限制 Key 必须是实数（RealNumber)，在我的理解里面，[Key any, Val any] 就可以，因为我们的 Comparator 就足以构建红黑树了。

另外一个，你可以把这个红黑树挪进去 internal/tree 里面吗？然后我们在这里稍微封装一下，相当于：
```go
// internal/tree/red_black_tree.go
type RedBlackTree struct {}

// mapx
type TreeMap[K, V] struct {
}
```

2023-01-08 14:38 UTC, flycash commented on mapx/treemap.go
> +func NewTreeMap[Key ekit.RealNumber, Val any]() *TreeMap[Key, Val] {
compare 也让用户传

2023-01-08 14:38 UTC, flycash commented on mapx/treemap.go
> +func NewTreeMap[Key ekit.RealNumber, Val any]() *TreeMap[Key, Val] {
这样我们就不必把 K 局限在 RealNumber 上

2023-01-08 14:38 UTC, flycash commented on mapx/treemap.go
> +type TreeMap[Key ekit.RealNumber, Val any] struct {
在我们这个包里面， hashmap 里面，实现了一个 imap （还是 mapi？）接口，这里也确保这个 TreeMap 也实现了这个接口

2023-01-08 14:44 UTC, flycash reviewed
测试覆盖率的话尽量构造测试用例来覆盖。一些没有意义的，例如返回 error 的我们确实不会遇到就不用管。

另外，记得把这个合并请求放进去 .CHANGELOG 里面。

你可以运行一下 make setup，我们会设置一些 git hook。

记得运行一下 make check，里面会搞一些代码格式化和静态代码检查。

2023-01-08 14:44 UTC, flycash commented on mapx/treemap.go
> +				treeMap.rotateRight(x.parentOf().parentOf())
这个地方应该是可以构造测试用例测一下的？

2023-01-08 14:44 UTC, flycash commented on mapx/treemap.go
> +func BuildTreeMap[Key ekit.RealNumber, Val any](compare ekit.Comparator[Key], m map[Key]Val) (*TreeMap[Key, Val], error) {
如果我们把 Key 做成 any 的时候，这里可以把  Key 限制为 comparable

2023-01-08 14:57 UTC, yzicheng commented on mapx/treemap.go
> +func BuildTreeMap[Key ekit.RealNumber, Val any](compare ekit.Comparator[Key], m map[Key]Val) (*TreeMap[Key, Val], error) {
好的，最初我设置的时候定义的是comparable。我改回去。

2023-01-08 16:17 UTC, juniaoshaonian commented
treemap需要有删除的方法，还有添加测试当叔父节点为黑色，并且是lr的情况。

2023-01-09 00:54 UTC, flyhigher139 commented on mapx/treemap_test.go
> +
是不是可以加一个按红黑树定义，来判断树是否为红黑树的测试？

即，调用函数创建一个红黑树，然后判断这三个条件是不是都满足：
1. 测试根节点是否为黑色
2. 是否有连续的红节点
3. 测试每条路径上，黑节点是否数量相等

2023-01-09 00:54 UTC, flyhigher139 commented on mapx/treemap.go
> +func (treeMap *TreeMap[Key, Val]) fixAfterPut(x *treeNode[Key, Val]) {
是不是少了一个`fixAfterRemove()`的方法，即，从红黑树里移除节点时，也要做动态调整

2023-01-09 01:56 UTC, yzicheng commented on mapx/treemap.go
> +func (treeMap *TreeMap[Key, Val]) fixAfterPut(x *treeNode[Key, Val]) {
是的，现在只实现了Put和Get。接下来我把Remov方法实现

2023-01-09 04:27 UTC, longyue0521 commented
我同意 @flycash 的建议,@yzicheng 请将抽取到 internal/tree 中,在那里我们验证好红黑树后,再基于这个红黑树数据结构实现当前的TreeMap,关注点分离,测试用例也更有针对性,另外在hashmap的实现中也可以复用这个红黑树对冲突链进行优化

2023-01-09 04:29 UTC, longyue0521 requested changes

2023-01-09 04:29 UTC, longyue0521 commented on mapx/map.go
> +func Values[K comparable, V any](m map[K]V) []V {
这个Values和下面的KeysValues有被用到吗? 在哪里被用到?

2023-01-10 02:03 UTC, flyhigher139 commented on internal/tree/red_black_tree.go
> +func (redBlackTree *RedBlackTree[T]) fixAfterAdd(x *TreeNode[T]) {
`fixAfterAdd()` 能不能拆成几个函数调用，把逻辑主线突显出来，让代码可读性和可维护性有所改善？
主要就是插入时的集中case，分别放到不同函数里，主线函数上就是几个case的调用或流转。

我之前写的这块代码的半成品，是这种方式拆的：

```go
// insertFix 实现插入新节点后的动态调整平衡
// 红黑树插入新节点的动态平衡算法如下：
// 1. 插入node为root时，直接变为黑色即可；
// 2. 插入节点的父节点为黑时，已经符合要求，不用调整
// 3. 插入节点的父节点为红时，需要动态调整，分以下3个case分别处理：

func (r *RedBlackTree) insertFix(node *Node) error {
	if node == r.Root {
		node.SetBlack()
		return nil
	}
	if node.Parent.IsBlack() {
		return nil
	}
	return r.insertFixByCase(node)
}

func (r *RedBlackTree) insertFixByCase(n *Node) error {
	if r.insertFixCase1(n) || r.insertFixCase2(n) || r.insertFixCase3(n) {
		return nil
	}

	return ErrTreeBalancingFailed
}

func (r *RedBlackTree) insertFixCase1(n *Node) bool {...}
func (r *RedBlackTree) insertFixCase2(n *Node) bool {...}
func (r *RedBlackTree) insertFixCase3(n *Node) bool {...}
```

2023-01-12 15:32 UTC, flycash commented on internal/tree/red_black_tree.go
> +	replacement := &RBNode[T]{}
这边不用初始化一个，所以只需要 var replacement *RBNode[T]，这样可以稍微规避一些不必要的内存分配

2023-01-12 15:57 UTC, flycash commented on mapx/map.go
> +func Values[K comparable, V any](m map[K]V) []V {
这个应该是之前写的，我写的。

2023-01-12 15:57 UTC, flycash requested changes
修复一下 github action，然后我周末的时候画一下各种图。
记得 rebase 到 ekit/dev 上，不然你会带上我之前合并的代码

2023-01-12 16:08 UTC, flycash requested changes

2023-01-12 16:08 UTC, flycash commented on mapx/treemap.go
> +type TreeMap[Key comparable, Val any] struct {
不是这样的，是 Key 和 Val 都应该是 any。我们并不关心 Key 怎样，我们只关心怎么比较，所以 TreeMap 是不需要对 Key 和 Val 进行限制。

2023-01-12 16:08 UTC, flycash commented on mapx/treemap.go
> +func BuildTreeMap[Key comparable, Val any](compare ekit.Comparator[Key], m map[Key]Val) (*TreeMap[Key, Val], error) {
这里到是要限制为comparable，但是主要是为了 map，而不是为了 TreeMap

2023-01-13 08:57 UTC, flyhigher139 commented on internal/tree/red_black_tree.go
> +func (redBlackTree *RBTree[T]) addNode(node *RBNode[T]) {
对于插入新节点这里，我有几个问题想讨论一下：

1. 关于红黑树在代码中的定义
红黑树的定义中要求，每个叶子节点都是黑色的空节点（NIL），即，叶子节点不存储数据。
这里，我觉得把叶子节点定义为go中的`nil` 不合适，这会损失“黑色”这个信息，而且红黑树之所以要求叶子节点都是黑色的空节点，是为了简化后面代码处理逻辑的。
我在实现红黑树时，是在树的结构体上定义了一个blackLeaf这样一个共享黑色叶子节点，后面所有的node处理上，除了在根节点上有点额外处理外，其他逻辑里，有不用对节点判空做额外处理了，业务逻辑也能和红黑树文字描述的算法逻辑更加吻合：
```
type RedBlackTree struct {
	Root      *Node
	blackLeaf *Node
}

type RBTOption func(tree *RedBlackTree)

func NewRedBlackTree(opts ...RBTOption) *RedBlackTree {
	res := &RedBlackTree{
		blackLeaf: &Node{Color: BLACK},
	}
	for _, opt := range opts {
		opt(res)
	}
	return res
}
```
所以，我们这里的红黑树定义，叶子用`nil`表示，还是类似我这种共享的`blackLeaf`表示更好一点？ @flycash @yzicheng 

2. 关于这个`addNode ()`函数要涵盖的业务范畴
我的看法是，做这几件事：
（1）按二叉搜索树的逻辑，把新节点插入到合适的叶子节点上（剔除blackLeaf后树的叶子位置）
（2）给这个新节点添加blackLeaf 叶子节点
（3）把这个新节点设为红色

上述与这段代码逻辑，有这几个差异：
（1）这个代码没考虑黑色空节点怎么表达，即直接用nil 代表了blackLeaf，我感觉不太合适
（2）没有显式把新节点设为红色，这里我觉得可读性不好，虽然前面定义用bool的false表示了红色，这里默认就是红色了，但我觉得这样代码可维护性变差了，而且后面fixAfterAdd 上也有漏洞，即，如何新节点是root，要把root设为黑色，那里也么写出来

3. `addNode()`函数的返回值要不要提供
红黑树的定义好像不允许插入相同key的节点，而且我们把红黑树用于TreeMap的话，把key相同的问题吞掉，是不是也不太合适，所以这里是不是设计为让`addNode()`函数返回`error`更严谨一点？

2023-01-13 08:57 UTC, flyhigher139 commented on internal/tree/red_black_tree.go
> +	for x != nil && x != redBlackTree.root && !x.parent.color {
1. 漏掉了x为root时，把x设为黑色的逻辑
2. 这个函数是插入新节点后调用的，x一定不为nil，主线逻辑不用做x是否为nil的判断
3. 如果存在blackLeaf，即便有x=x.left/x=x.right的操作，也不需要nil的额外判断，代码逻辑能简化一点
4. 建议增加RBTree.getParent(node)/getBrother(node)/getGrandParent(node)/getUncle(node)，或node.getParent()/getBrother()/getUncle()等方法，这样，这段代码的可维护性会更好一点

2023-01-13 08:57 UTC, flyhigher139 commented on internal/tree/red_black_tree.go
> +func (redBlackTree *RBTree[T]) successor(node *RBNode[T]) *RBNode[T] {
1. 这里函数命名风格不太统一，大部分都是动宾短语，这里用了名次，保持统一的话，这里应该是getSuccessor()
2. 代码可以写的更清爽一点，每个else上面的if如果触发的话，都return了，所以这些else都没必要写，去掉没必要的else后，代码逻辑就更清晰了
3. 如果认同用共享的blackLeaf作为红黑树的黑色叶子节点的话，这里与nil的比较，都要改一下了

2023-01-13 09:27 UTC, flyhigher139 commented on internal/tree/red_black_tree.go
> +	for x != nil && x != redBlackTree.root && !x.parent.color {
我基本被下面这段复杂嵌套的if else 绕晕了，看了好半天
其实把获取叔叔节点、兄弟节点、父节点和祖父节点的函数写好后，这里就平铺三个if就好了，伪码为：

```
if uncle.color==red：x = redBlackTree.fixUncleRed(x, uncle); continue
if x == p.Left: x = redBlackTree.fixAddLeftBlack(x) continue
if x == p.Right: x = redBlackTree.fixAddRightBlack(x) continue
```

三个fixCase的逻辑，我肉眼看除了可读性也有类似的优化外，没发现问题

另，刚看到把root设为黑的代码放到最后了，这个建议拿到开头来，符合这个条件，执行完改颜色的逻辑后直接return，不用管后面的逻辑了，这样可读性也好一些

2023-01-13 14:11 UTC, yzicheng commented on internal/tree/red_black_tree.go
> +	for x != nil && x != redBlackTree.root && !x.parent.color {
1. 嗯，root我放在了addNode，但是直接return掉了导致没有染色，这个我修复了
2. x加上nil判断其实是因为在下面x会不断变换可能会有nil值出来，所以就加上了一个nil判断
3. root 设置我放后面是因为在平衡之后root节点会出现红色，所以我就在代码最后面处理了一把。

2023-01-13 14:12 UTC, yzicheng commented on internal/tree/red_black_tree.go
> +func (redBlackTree *RBTree[T]) successor(node *RBNode[T]) *RBNode[T] {
嗯，好的，我修改一下

2023-01-13 14:19 UTC, yzicheng commented on internal/tree/red_black_tree.go
> +func (redBlackTree *RBTree[T]) addNode(node *RBNode[T]) {
addNode() 相同节点这个问题，我想法和你一样,我准备再做一个replace方法。然后在TreeMap的Put函数里判断是调用add还是replace

2023-01-13 15:09 UTC, flyhigher139 commented on internal/tree/red_black_tree.go
> +	for x != nil && x != redBlackTree.root && !x.parent.color {
我记得好像红黑树的动态平衡过程，叶子节点是没参与进去的，除了叶子之外，其他节点都不会是nil，所以不需要对x判空，这个可以再核实一下

我写的那个实现中，叶子节点不是用nil表示的，而且创建了一个类型为Node的blackLeaf对象，本来就不是nil，所以更不需要有判空逻辑
这里也是我上面评论中说的，我感觉对红黑树而言，叶子直接用nil表示好像不太合适，丢失了black信息，也会给代码逻辑带来更多的特殊情况处理

2023-01-13 15:31 UTC, yzicheng commented on internal/tree/red_black_tree.go
> +	for x != nil && x != redBlackTree.root && !x.parent.color {
嗯，好的，我这个在核实下

2023-01-14 15:12 UTC, flycash reviewed
https://www.cs.usfca.edu/~galles/visualization/RedBlack.html

这是一个非常好的网站，可以用于验证测试用例。

2023-01-14 15:20 UTC, flycash commented
- 合并最新的分支。我觉得你貌似没有合并最新的 gotomicro/ekit dev 分支，记得 fetch，或者 git pull。你的本地的 gotomicro/ekit 可能没更新
- 检查我们的 github action 一个个修复过去。go build 都失败，可能是你有代码没提交，检查一下
- check license 是每一个新文件都要有一个 license 说明，这是 apache 要求的
- changelog 你只要把这个合并请求加进去 .CHANGELOG 里面就可以
- golangci-lint 一个个检查过去了，deepsource 也是如此。如果你觉得有一些可以不必修，那么你说明一下就可以

另外测试用例我看了，看上去是没问题。但是我有一个隐忧，就是这里面的测试用例依赖于 isRedBlackTree 这个方法，如果这个方法本身就是错的，那么就可能有问题。另外一方面来说，用一个新写的方法验证另外一个新写的方法，不是很可靠的样子。不过这个你可以暂时按照你的想法来测试，后面我琢磨一下怎么改进这个测试。

有一个你可以考虑做的，就是引入模糊测试，模糊测试里面不断往一棵红黑树里面增加节点，并且每加入一个节点，就验证一下是不是红黑树。这样子模糊测试也能保证红黑树这里没有问题。

2023-01-14 15:20 UTC, yzicheng commented
是的，我也在用这个做测试验证

2023-01-16 05:29 UTC, flycash reviewed
@flyhigher139 @longyue0521 请在确认你们是否还有问题。没有问题的话请 approve 一下。后面我可以在合并之后再去优化测试和引入模糊测试

2023-01-16 05:47 UTC, longyue0521 requested changes

2023-01-16 05:47 UTC, longyue0521 commented on internal/tree/red_black_tree.go
> +		redBlackTree.root = NewRBNode[T, V](node.Key, node.Value)
1. 代码走到这, root由nil变为NewRBNode, 可是t确还是root更新前的值 => nil
2. 因为t为nil
    -  所以会跳过107~117行`for t !=nil { ....}`
    - 走到118行,创建tempNode,这是没有必要的,名字取的也不好,temp有临时,用过可丢弃之意,改为newNode/child 
    - 走到130行, `fixAfterAdd`调整的是tempNode,而tempNode挂在parent下,而parent是一个临时生成的空节点并没指向红黑树上有效节点(因为t为nil没有进入for循环),而红黑树的根节点是NewRBNode(...)产生的,要调整也该调整它
3. 请梳理逻辑,修改实现,改进代码可读性

2023-01-16 05:58 UTC, longyue0521 requested changes

2023-01-16 05:58 UTC, longyue0521 commented on internal/tree/red_black_tree.go
> +func (redBlackTree *RBTree[T, V]) getSuccessor(node *RBNode[T, V]) *RBNode[T, V] {
改为 successor / findSuccessor https://google.github.io/styleguide/go/decisions#getters

2023-01-16 05:58 UTC, longyue0521 commented on internal/tree/red_black_tree.go
> +func (redBlackTree *RBTree[T, V]) getRBNode(key T) *RBNode[T, V] {
改为findNode

2023-01-16 05:58 UTC, longyue0521 commented on internal/tree/red_black_tree.go
> +func nodeCheck[T any, V any](node *RBNode[T, V], count int, num int) bool {
将这两个方法移到测试代码中,这两个方法与实现无关,是测试辅助方法.当检验红黑树是否正确的机制改变时,只需要修改测试代码而不需要产品代码.

2023-01-16 06:38 UTC, yzicheng commented on internal/tree/red_black_tree.go
> +		redBlackTree.root = NewRBNode[T, V](node.Key, node.Value)
这里我代码结构调整下，其实代码走到redBlackTree.root = NewRBNode[T, V](node.Key, node.Value) 后面只要root变色就可以返回

2023-01-16 06:57 UTC, yzicheng commented on internal/tree/red_black_tree.go
> +	Value               V
1. 好的我解决下
2. 这里我是考虑外部关心Key，Value两个属性所以设置成了可见。

2023-01-16 08:25 UTC, longyue0521 commented on internal/tree/red_black_tree.go
> +		redBlackTree.root = NewRBNode[T, V](node.Key, node.Value)
你每次提交后记得将这次提交相关的对话框resolve掉

2023-01-16 08:58 UTC, flyhigher139 commented on internal/tree/red_black_tree.go
> +	if node != nil {
这里也可以简洁一点：
1. 由于只有if的逻辑，没有else的逻辑，可以简化为 if node == nil： return 的写法，然后下面是核心逻辑
2. 下面那个return的条件也可以拿上来一起判断，所以代码可以简化为：

```go
 if node == nil || node.right == nil {
    return
}
// 下面是核心逻辑
```

2023-01-16 09:03 UTC, flyhigher139 commented
> @flyhigher139 @longyue0521 请在确认你们是否还有问题。没有问题的话请 approve 一下。后面我可以在合并之后再去优化测试和引入模糊测试

红黑树的主要逻辑，我觉得差不多了，也许还有点可读性可以优化的代码，存在暗坑没看出来，这种是不是直接依赖下一步优化测试的时候再进一步确认？我暂时没啥意见了

2023-01-16 09:06 UTC, flyhigher139 approved these changes

2023-01-16 09:26 UTC, yzicheng commented on internal/tree/red_black_tree.go
> +	if node != nil {
好的，我修改下

2023-01-16 11:27 UTC, longyue0521 requested changes

2023-01-16 11:27 UTC, longyue0521 commented on mapx/treemap_test.go
> +	}
在这个测试文件中只应该测试TreeMap相关的接口,为什么要有tree.RBNode出现?换句话说,RBTree的测试已经保证RBTree生产可用,你就不需要再测试RBTree相关的东西了.

删掉或改写这两个方法,采用TreeMap接口来实现,你想得到Val[], 你只需要遍历你预设key[],然后treeMap.Get(key)就能得到所有的Val.不需要拿到底层的tree.RBNode和tree.Root().

2023-01-16 11:27 UTC, longyue0521 commented on mapx/treemap_test.go
> +			if tt.v == nil {
两个分支大部分代码重复,可以将v==nil这个测试用例单独写在一个subtest中

2023-01-16 11:27 UTC, longyue0521 commented on mapx/treemap.go
> +	PutAll(treeMap, m)
1. 将BuildTreeMap重命名为NewTreeMapWithBuildInMap或其他可读性更好的名称
2. 将PutAll => putAll

2023-01-16 11:27 UTC, longyue0521 commented on mapx/treemap_test.go
> +func TestBuildTreeMap(t *testing.T) {
需要重命名

2023-01-16 11:27 UTC, longyue0521 commented on mapx/treemap_test.go
> +func TestPutAll(t *testing.T) {
删除该测试,原测试TestBuildTreeMap已经覆盖了putAll的测试用例

2023-01-16 12:09 UTC, longyue0521 requested changes

2023-01-16 13:45 UTC, yzicheng commented on mapx/treemap.go
> +	PutAll(treeMap, m)
这里我之前将PutAll设为可见，是想减少用户这样代码的调用
`	if len(m) != 0 {
		for k, v := range m {
			_ = treeMap.Put(k, v)
		}
	}` 
那我们需不需要这样支持？

2023-01-16 13:59 UTC, yzicheng commented on internal/tree/red_black_tree.go
> +	return rb.findRBNode(key)
RBNode =》 rbNode,然后清理rbNode上的方法,例如将Left和getLeft合并为一个left方法
这个地方改成getLeft,如果采用left会和属性名相同。类似的我都改成get+，这样是否合理

2023-01-16 14:19 UTC, yzicheng commented on internal/tree/red_black_tree.go
> +		if !y.getColor() {
!x.getParent().getColor() => x.parent.color == RED, 显示比较表明意图 
!y.getColor() => uncle.color == RED, 显示比较表明意图
这个地方我之前是这样写，但是make lint 会提示这里需要简写为!x.getParent().getColor()  @和!y.getColor()。我这里是否需要维护成 x.parent.color == RED这种写法？ @longyue0521 @flycash

2023-01-16 14:20 UTC, longyue0521 commented on mapx/treemap.go
> +	PutAll(treeMap, m)
类比list包中的做法,提供NewTreeMapWithBuildInMap就可以了, 剩下的让用户自己遍历插入就行了

另外, mp的遍历不需要判断`len(m) != 0` 直接用`for k, v := range m{ ...}`就行

2023-01-16 14:26 UTC, yzicheng commented on mapx/treemap.go
> +	PutAll(treeMap, m)
好的，我修改下

2023-01-16 14:30 UTC, longyue0521 commented on internal/tree/red_black_tree.go
> +	return rb.findRBNode(key)
- 其实rbNode就是一个值对象,不需要方法,通过添加虚节点(dummyNode)应该去掉`==nil`的判断,前面好像讨论过 https://github.com/gotomicro/ekit/pull/142#discussion_r1069092856,
- 你先去掉rbNode包外可见的方法吧,暂时用getXXX来写,后续再优化这里

2023-01-16 14:36 UTC, longyue0521 commented on internal/tree/red_black_tree.go
> +		if !y.getColor() {
应该用类似于`uncle.color == RED`的写法,make lint的提示也不能忽略,所以修改Color的类型

可以考虑用byte表示 RED = 'R', BLACK = 'B'

2023-01-16 14:51 UTC, yzicheng commented on internal/tree/red_black_tree.go
> +		if !y.getColor() {
`type color bool
const (
	Red   color = false
	Black color = true
)
type rbNode[K any, V any] struct {
	color               color
`
我重新定义color，make lint不会提示。这样是否会更合理一点

2023-01-16 14:54 UTC, yzicheng commented on internal/tree/red_black_tree.go
> +		if !y.getColor() {
type color bool

const (
	Red   color = false
	Black color = true
)
type rbNode[K any, V any] struct {
	color               color
我定义一个color是否会更合理

2023-01-16 15:11 UTC, longyue0521 commented on internal/tree/red_black_tree.go
> +		if !y.getColor() {
可以 const一般全大写

2023-01-17 05:54 UTC, longyue0521 approved these changes

2023-01-17 06:44 UTC, flyhigher139 approved these changes

2023-01-17 11:45 UTC, flycash approved these changes

2023-01-17 11:46 UTC, merged