setx: Set 接口设计和基于 map 的实现
gotomicro/ekit pull request #148
Opened 2023-02-03 12:21 UTC by juniaoshaonian

2023-02-04 15:14 UTC, flycash requested changes

2023-02-04 15:14 UTC, flycash commented on set/set.go
> +func (s *Setx[T]) Values() []T {
在这个实现里面备注一下，就是返回 Keys 的顺序是不确定的

2023-02-04 15:14 UTC, flycash commented on set/set.go
> +	_, ok := s.m[val]
```
val := s.m[key]
delete()
return val
```

2023-02-04 15:14 UTC, flycash commented on set/set.go
> +	Values() []T
所以对应的变量名字也改成 key

2023-02-05 07:56 UTC, juniaoshaonian commented on set/set.go
> +type Setx[T comparable] struct {
叫MapSet？我是个取名渣

2023-02-06 07:24 UTC, theoriz0 commented
看到使用的是map[T]bool，使用map[T]struct{} 是否会更好一些？https://blog.csdn.net/kevin_tech/article/details/122335317

2023-02-06 08:17 UTC, juniaoshaonian commented
> 看到使用的是map[T]bool，使用map[T]struct{} 是否会更好一些？https://blog.csdn.net/kevin_tech/article/details/122335317

我再测试一下使用struct{}要跑多久

2023-02-06 09:07 UTC, juniaoshaonian commented
> > 看到使用的是map[T]bool，使用map[T]struct{} 是否会更好一些？https://blog.csdn.net/kevin_tech/article/details/122335317
> 
> 我再测试一下使用struct{}要跑多久
确实是快一点

2023-02-07 01:19 UTC, flyhigher139 commented on set/set.go
> +	IsExist(key T) bool
Exist 是动词，命名统一的话，应该和Add, Remove一致，这里直接用`Exist(key T) bool`
如果用IsXXX的形式，可以改为`IsExistent(key T) bool`

2023-02-07 11:39 UTC, juniaoshaonian commented on set/set.go
> +	IsExist(key T) bool
好的

2023-02-08 02:53 UTC, flycash commented
根据 @theoriz0 贴出来的连接，你需要修改值为使用struct{}。另外你需要提供基准测试，测试直接操作 map，和使用这个 set 在性能上相差多少。

Remove 改成 Delete，我看了一下其他代码，都是叫做 Delete。

在改成使用 struct{} 之后，Delete 方法我感觉不需要返回值。

2023-02-08 02:53 UTC, flycash commented
顺便合并一下最新代码，然后解决冲突

2023-02-08 03:37 UTC, closed without merging