slice: FilterDelete
gotomicro/ekit pull request #152
Opened 2023-02-06 16:52 UTC by chenmingyong0423

- 新增 FilterDelete 函数，删除某些符合条件的元素。考虑到性能问题，所有操作都会在原切片上进行；被删除元素之后的元素会往前移动，有且只会一定一次
- 新增 FilterDelete 测试函数和编写测试用例

2023-02-07 01:39 UTC, flyhigher139 commented on slice/delete.go
> +}
这段逻辑，就是用双指针，把保留的元素挪到前面去，可以简化一下：

```go
emptyPos := 0
for idx := range src {
  if m(idx, src) {
    continue
  }
  src[emptyPos] = src[idx]
  emptyPos++
}
return src[:emptyPos]
```

2023-02-07 02:04 UTC, chenmingyong0423 commented on slice/delete.go
> +}
好的

2023-02-08 02:22 UTC, longyue0521 requested changes

2023-02-08 02:22 UTC, longyue0521 commented on slice/delete_test.go
> +		{
测试用例设计以黑盒技术为主(功能测试),白盒技术(结构测试)为辅:
1. 输入即precondition, src = {},{奇数个}, {偶数个}. 当前测试用例集缺少/并未覆盖前两个
2. 输出即postcondition, wantRes = {}, {奇数个}, {偶数个}。当前测试用例集已覆盖

添加src={}的用例, 调整某个现有src使其为奇数个,且保持上方2仍然成立

2023-02-08 02:26 UTC, chenmingyong0423 commented on slice/delete_test.go
> +		{
好的

2023-02-08 04:16 UTC, flycash approved these changes

2023-02-08 04:16 UTC, merged