实现AsSlice()功能
gotomicro/ekit pull request #19
Opened 2022-08-12 09:00 UTC by flyhigher139

实现AsSlice()功能

2022-08-12 14:09 UTC, flycash commented on list/array_list.go
> +	slice := make([]T, len(a.vals), cap(a.vals))
这边新创建的，将 cap 和 len 设置成为相等的，因为我们并不是要返回一个一模一样的切片，而是返回一个近似于只读的切片，虽然用户可以拿去写。

2022-08-12 15:03 UTC, flyhigher139 commented on list/array_list.go
> +	slice := make([]T, len(a.vals), cap(a.vals))
收到，已修改～

2022-08-12 16:09 UTC, flycash requested changes

2022-08-12 16:09 UTC, flycash commented on list/array_list.go
> +func NewArrayListOf2[T any](ts []T) *ArrayList[T] {
这个也删掉，才发现居然有一个 2 作为后缀？你可以直接实现 NewArrayListOf

2022-08-12 16:09 UTC, flycash commented on list/array_list.go
> +func NewArrayListOf2[T any](ts []T) *ArrayList[T] {
这个方法你就不用架测试也可以

2022-08-13 02:13 UTC, flyhigher139 commented on list/array_list.go
> +func NewArrayListOf2[T any](ts []T) *ArrayList[T] {
收到，已经把冗余的方法删除了～

2022-08-13 08:00 UTC, flycash commented
@flyhigher139 合并了一个合并请求之后，和你的代码冲突了，应该是两个人都写了 ArrayListOf 这个方法，你解决一下冲突就可以了，随便保留谁的

2022-08-13 08:00 UTC, flycash commented on list/array_list.go
> +	obj := &ArrayList[T]{}
正常来说，我们的代码风格都会倾向于
obj := &ArrayList[T]{
    vals: ts
}

2022-08-13 08:38 UTC, flyhigher139 commented on list/array_list.go
> +	obj := &ArrayList[T]{}
收到！

2022-08-13 08:48 UTC, merged