Linked list 实现asSlice()
gotomicro/ekit pull request #27
Opened 2022-08-14 08:58 UTC by flyhigher139

Linked list 实现asSlice()

2022-08-16 05:41 UTC, flycash requested changes

2022-08-16 05:41 UTC, flycash commented on list/linked_list.go
> +		prev = cur
这里你应该调用 Append 方法，而不是自己实现。如果 Append 还没有实现，那么你可以顺手实现一下

2022-08-16 05:41 UTC, flycash commented on list/linked_list_test.go
> +	fmt.Println("\nbackward")
不要用 fmt.Println，单元测试要自动化，那么到时候是没有人去检查有没有输出这种语句的。DEBUG 的时候可以用，但是后面都删掉

2022-08-16 05:41 UTC, flycash commented on list/linked_list_test.go
> +	t.Log(head.value, tail.value)
类似这种 log 也不要用

2022-08-16 05:41 UTC, flycash commented on list/linked_list_test.go
> +func TestNewLinkedListOf(t *testing.T) {
你这里要用 table driver，测试几个场景：
- 传入 nil
- 传入空的切片
- 传入单个元素的切片
- 传入多个元素的欺骗。
```
testCases := []struct{}{
    // 你的 case
}

for _, tc := range struct {
     list :=  NewLinkedListOf()
    // 在这里断言你的元素，可以利用 Get 方法，也可以直接用 AsSlice 来断言
    assert.Equal(t, tc.wantSlice, list.AsSlice())
}
```

2022-08-16 05:41 UTC, flycash commented on list/linked_list_test.go
> +	slice := a.AsSlice()
你是不是放错位置了？

2022-08-16 13:17 UTC, flyhigher139 commented on list/linked_list_test.go
> +func TestNewLinkedListOf(t *testing.T) {
收到～ 明天好好修改一下！

2022-08-17 02:16 UTC, flyhigher139 commented on list/linked_list.go
> +		prev = cur
> 这里你应该调用 Append 方法，而不是自己实现。如果 Append 还没有实现，那么你可以顺手实现一下

@flycash 老师，你合并好的dev里，已经有`NewLinkedListOf()`了，我直接用的那个，补充了单元测试

现在dev里的node定义是：
```go
type node[T any] struct {
	next *node[T]
	prev *node[T]
	val  T
}
```
val 是不是用指针更好？

2022-08-17 04:29 UTC, flycash approved these changes

2022-08-17 04:29 UTC, merged