LinkedList 实现 Get
gotomicro/ekit pull request #31
Opened 2022-08-15 16:53 UTC by hhh111119

- 实现 Get, 测试, benchmark
- 简化 Add 函数

2022-08-16 05:34 UTC, flycash requested changes

2022-08-16 05:34 UTC, flycash commented on list/linked_list.go
> +		cur = cur.move(headToLeft)
把 move 方法删掉。这种外面传递一个标记位进来控制行为的代码，还是比较丑的。调用者自己应该自己应该是从前往后或者从后往前。
对于 get 来说，你只需要判断一下长度和 index 的关系，然后就是决定从后往前还是从前往后，对应于代码大概就是：
```go
if l.fromTailToHead(index) {
      node = getFromTail
} else {
     node = getFromHead
}
```
即便 getFromHead 和 getFromTail 有轻微代码重复，代码可读性也要比这里看上去好一点

2022-08-16 05:34 UTC, flycash commented on list/linked_list.go
> +	if index < 0 || index >= l.length {
这个校验你挪过去，让公共方法 Get 校验，那么 Add 那边过来，这里就不会重复执行了。其它公开方法自己校验自己的，虽然他们逻辑都一样

2022-08-17 10:26 UTC, flycash commented on list/linked_list.go
> +func (l *LinkedList[T]) getNode(index int) (n *node[T]) {
其实你这个代码是没有必要在返回值里面声明返回值的名字 n 的，在最后可以直接返回 cur。
一般来说，返回值带名字一般是用在接口声明里面，这是为了让用户能够看懂返回值代表的是什么。
在实现里面就比较少用，当然有些人会用。但是这种用法相当于引入了一个在整个方法内部都有效果的变量，操作不当是容易出 BUG 的，我就修过类似的 BUG。
因此我不建议在使用命名的返回值，你在最后直接返回 cur 就可以了，这里改成：
```go
getNode(index int) *node[T]
```

2022-08-17 10:28 UTC, flycash commented on list/linked_list_test.go
> +			nil,
前面还是要加上字段名字，不要省事=。=不然将来加一个字段，要改的的地方就太多了。而且类似于 0, nil 这种类型零值，是没有必要赋值的。

2022-08-17 10:29 UTC, flycash commented on list/linked_list_test.go
> +			panic(err)
用 b.Fatal(err)，应该有这个调用

2022-08-17 15:47 UTC, hhh111119 commented
已修复

2022-08-17 16:56 UTC, merged