新增NewArrayList方法Append方法Set方法Delete方法，以及更新测试文件
gotomicro/ekit pull request #32
Opened 2022-08-16 05:24 UTC by mousseqin

本次提交内容：

List目录array_list.go文件
1.完成NewArrayList方法
2.完成Append方法
3.完成set方法
4.完成delete方法

List目录array_list_test.go文件
1.写了测试用例并完成测试

2022-08-16 05:50 UTC, flycash requested changes

2022-08-16 05:50 UTC, flycash commented on list/array_list.go
> +		panic("index参数超出ArrayList的边界(by set func)")
不要panic，我们这边都返回错误，至于要不要 panic，让调用者去决定

2022-08-16 05:50 UTC, flycash commented on list/array_list_test.go
> +func TestNewArrayList(t *testing.T) {
如果你测试 NewArrayList，那你就只测 NewArrayList。如果你测 Set，那你就在 Set 方法里面写；分开来写测试

2022-08-16 05:50 UTC, flycash commented on list/array_list_test.go
> +	spew.Dump(n)
不要用这种东西来判断结果，用 assert。对于 ArrayList 来说，你直接判断里面的元素是否符合你的预期，例如 assert(t, tc.wantSlice, list.vals)

2022-08-16 12:40 UTC, mousseqin commented on list/array_list.go
> +		panic("index参数超出ArrayList的边界(by set func)")
收到

2022-08-16 12:40 UTC, mousseqin commented on list/array_list_test.go
> +func TestNewArrayList(t *testing.T) {
> 如果你测试 NewArrayList，那你就只测 NewArrayList。如果你测 Set，那你就在 Set 方法里面写；分开来写测试

收到

2022-08-16 12:40 UTC, mousseqin commented on list/array_list_test.go
> +	spew.Dump(n)
> 不要用这种东西来判断结果，用 assert。对于 ArrayList 来说，你直接判断里面的元素是否符合你的预期，例如 assert(t, tc.wantSlice, list.vals)

好的

2022-08-17 04:35 UTC, flycash requested changes

2022-08-17 04:35 UTC, flycash commented on list/array_list_test.go
> +	//assert.Equal(t, wantData, nArr.vals) // pass
按照道理来说，元素的类型是不会对 arraylist 产生影响的，所以这部分测试如果你觉得有必要保留，那么就打开注释，如果你觉得没必要，就删掉好了。不要留着注释在这里。

我觉得可以直接删掉

2022-08-17 04:35 UTC, flycash commented on list/array_list_test.go
> +func TestArrayList_Append_Set(t *testing.T) {
整个测试，你需要考虑改造成 table driven 的形式来测试。一般来讲，我们都是采用这样一个模板
```go
testCases := []struct{
    name string
    // ... 其它字段
} {
     {
         // 用例名字，一般描述你测试了什么场景
          name:"xxx",
     }
}

for _, tc := range testCases {
    t.Run(tc.name, func(t *testing.T){
       // 初始化数据
      // 执行调用，在这里就是 set
     // 断言结果，一般用 assert 包
})
}
```
你可以参考 arraylist 中的其它测试，或者 linkedlist 里面的测试

2022-08-17 04:35 UTC, flycash commented on list/array_list.go
> +// NewArrayList 初始化一个len为0，cap为10的ArrayList
初始化一个 len 为0，容量为 cap 的ArrayList

2022-08-17 04:36 UTC, flycash commented on list/array_list.go
> +// NewArrayList 初始化一个len为0，cap为10的ArrayList
你可以再多加一句，我们不会对 cap 进行校验。

其实这里面就体现了这么一个决策：
正常人都不会传一个负数进来，所以我们也没必要检测。真要传入了负数，发生什么事情，我们也不管。

2022-08-17 05:37 UTC, mousseqin commented on list/array_list_test.go
> +	//assert.Equal(t, wantData, nArr.vals) // pass
> 按照道理来说，元素的类型是不会对 arraylist 产生影响的，所以这部分测试如果你觉得有必要保留，那么就打开注释，如果你觉得没必要，就删掉好了。不要留着注释在这里。
> 
> 我觉得可以直接删掉

收到

2022-08-17 06:14 UTC, mousseqin commented on list/array_list_test.go
> +func TestArrayList_Append_Set(t *testing.T) {
> 整个测试，你需要考虑改造成 table driven 的形式来测试。一般来讲，我们都是采用这样一个模板
> 
> ```go
> testCases := []struct{
>     name string
>     // ... 其它字段
> } {
>      {
>          // 用例名字，一般描述你测试了什么场景
>           name:"xxx",
>      }
> }
> 
> for _, tc := range testCases {
>     t.Run(tc.name, func(t *testing.T){
>        // 初始化数据
>       // 执行调用，在这里就是 set
>      // 断言结果，一般用 assert 包
> })
> }
> ```
> 
> 你可以参考 arraylist 中的其它测试，或者 linkedlist 里面的测试

感谢老师指点，这就去改

2022-08-17 06:59 UTC, flycash commented on list/array_list.go
> +// NewArrayList 初始化一个len为0，cap为10的ArrayList
我是说这个注释改一下 "NewArrayList 初始化一个长度为0，容量为 cap 指定的ArrayList"

2022-08-17 07:16 UTC, flycash commented on list/array_list_test.go
> +	testCase := []struct {
这两个测试用例设计得不对。首先在你的实现里面，其实值本身是正数还是负数，没有影响。我们用了泛型，所以用户不可能输入不同类型的数据。

实际上在你这个测试场景里面，应该考虑的是：如果 NewArrayListOf 传入的是一个 nil，然后再 Append，会发生什么。按照你的 Append 方法，应该是直接崩溃掉。

2022-08-17 07:16 UTC, flycash commented on list/array_list_test.go
> +	testCase := []struct {
也就是正常 append，和 vals 是 nil，然后 Append

2022-08-17 07:51 UTC, flycash commented
@mousseqin 我是说这个注释改为 "NewArrayList 初始化一个长度为0，容量为 cap 指定的ArrayList"

2022-08-17 12:00 UTC, mousseqin commented
> @mousseqin 我是说这个注释改为 "NewArrayList 初始化一个长度为0，容量为 cap 指定的ArrayList"

好的老师，我刚看到，今天课后我改好了提交

2022-08-17 16:50 UTC, flycash approved these changes

2022-08-17 16:52 UTC, merged