实现 reflect_copier
gotomicro/ekit pull request #47
Opened 2022-08-23 18:16 UTC by hhh111119

- 实现 reflect copier 的功能
- 单元测试
- 简单基准测试

2022-08-24 04:37 UTC, flycash reviewed
这里有一个地方你可能没有注意到，我会留下一个 fieldMap 的定义其实是为了提高性能。也就是说，我预期中用户使用这个实现是：
```go
copier := NewReflectCopier()
copier.Copy(xxx)
copier.Copy(xxx)
```
也就是说，NewReflectCopier 是一个很慢的过程，它主要利用反射解析来得到一些元数据，例如不同字段的映射关系，同时还可以维护住 index 之类的信息。
后面 Copy 的时候，我在考虑的就是能不能利用到这些元数据来加速这么一个过程。
我想了一下 fieldMap 可能不是特别合适，应该是
```go
srcMap map[string][]int
dstMap map[string][]int
```
key 应该是结构体连在一起，而 []int 则是 FieldByIndex里面的 Index。这样就是遍历 srcMap，然后找到 src index，再根据同样的 key 找到 dst 的 []int，然后反射直接 FieldByIndex，在这种情况下，我觉得应该比 FieldByName 层层递归下去要快很多。

你觉得呢？

2022-08-24 04:38 UTC, flycash commented
Copier 本身用在各种 O 之间的转换，所以还是要考虑一下怎么提高性能

2022-08-24 05:28 UTC, flycash commented
我想到使用两个 map 结构不太好，还不如定义一个 field 结构体：
```go
type field struct {
    name string
    src []int
    dst []int
    // 后续可以考虑的
   skip bool // 忽略这个字段
   converter func(val reflect.Value) reflect.Value // 类型转换
    validator xxx // 校验，虽然我觉得没啥必要=。=
    // ...
}
```
这样就有非常强的扩展性

2022-08-24 06:14 UTC, hhh111119 commented
> 这里有一个地方你可能没有注意到，我会留下一个 fieldMap 的定义其实是为了提高性能。也就是说，我预期中用户使用这个实现是：
> 
> ```go
> copier := NewReflectCopier()
> copier.Copy(xxx)
> copier.Copy(xxx)
> ```
> 
> 也就是说，NewReflectCopier 是一个很慢的过程，它主要利用反射解析来得到一些元数据，例如不同字段的映射关系，同时还可以维护住 index 之类的信息。 后面 Copy 的时候，我在考虑的就是能不能利用到这些元数据来加速这么一个过程。 我想了一下 fieldMap 可能不是特别合适，应该是
> 
> ```go
> srcMap map[string][]int
> dstMap map[string][]int
> ```
> 
> key 应该是结构体连在一起，而 []int 则是 FieldByIndex里面的 Index。这样就是遍历 srcMap，然后找到 src index，再根据同样的 key 找到 dst 的 []int，然后反射直接 FieldByIndex，在这种情况下，我觉得应该比 FieldByName 层层递归下去要快很多。
> 
> 你觉得呢？

嗯嗯, 这块我去看看, 能不能用下面的 field 来维护信息 . 之前没有理解到这个 map 的意思. 现在大概明白了, 希望在创建 copier 的时候把映射关系先建立好.

2022-08-24 16:37 UTC, longyue0521 commented
@flycash

现有需求来自一下几段代码:

```go
// ekit/ben/copier/copy.go
// Copier 复制数据
// 1. 深拷贝亦或是浅拷贝，取决于具体的实现。每个实现都要声明清楚这一点；
// 2. Src 和 Dst 都必须是普通的结构体，支持组合
// 3. 只复制公共字段
// 这种设计设计，即使用 *Src 和 *Dst 可能加剧内存逃逸
type Copier[Src any, Dst any] interface {
	// CopyTo 将 src 中的数据复制到 dst 中
	CopyTo(src *Src, dst *Dst) error
	// Copy 将创建一个 Dst 的实例，并且将 Src 中的数据复制过去
	Copy(src *Src) (*Dst, error)
}
```

```go
// reflectCopier 基于反射的实现
// reflectCopier 是浅拷贝
type reflectCopier[Src any, Dst any] struct {
        // ....
}
```
```go
// CopyTo 执行复制
// 执行复制的逻辑是：
// 1. 按照字段的映射关系进行匹配
// 2. 如果 Src 和 Dst 中匹配的字段，其类型是基本类型（及其指针）或者内置类型（及其指针），并且类型一样，则直接用 Src 的值
// 3. 如果 Src 和 Dst 中匹配的字段，其类型都是结构体，或者都是结构体指针，那么会深入复制
// 4. 否则，返回类型不匹配的错误
// TODO: 支持不同类型之间的转换
func (r *reflectCopier[Src, Dst]) CopyTo(src *Src, dst *Dst) error {
       // ....
}
```

### 需求澄清

1. “公共字段”的定义是什么?或两个结构体中的某个字段是否“匹配”的定义是什么?

现阶段的理解是,两个结构体中某一字段**名称、类型及相对位置**均相同,即为匹配/公共字段

```go
type Src struct {
      A string
      b int
      c bool
      D int32
      E error
      F user
}

type Dst struct {
     A string
     b int
     c *bool
     D string
     E  error
     F  *user
}
type user struct {}
```
匹配字段为A,b,E
不匹配字段为c,D
F是否认定为匹配?

2. 非导出字段如何处理? 是否忽略?

如果忽略非导出字段,上例中匹配字段为A,E;不匹配字段为D

3. 不匹配字段的处理细节

通常来说会**忽略不匹配字段**,但有一种特殊情况就是两个类型**没有任何公共/匹配字段**是否应该报错?

4. API设计,我为NewReflectCopier添加了error

```go
copier, err := NewReflectCopier[Src, Dst]()
if err != nil {
      // 至少要有一个匹配字段
      // Src/Dst类型非法等
      // Src/Dst中某字段类型为多级指针
}

err = copier.CopyTo(......)
if err != nil {
     // 复制时发生的错误
} 
```

2022-08-25 01:33 UTC, hhh111119 commented
这块我回去想了一下, 最后发现这里挺适合用字典树来做数据结构. 就实现了一版.

// 纯递归实现 bench
//goos: darwin
//goarch: amd64
//pkg: github.com/gotomicro/ekit/bean/copier
//cpu: Intel(R) Core(TM) i5-1030NG7 CPU @ 1.10GHz
//BenchmarkReflectCopier_Copy
//BenchmarkReflectCopier_Copy-8   	 1353440	       875.8 ns/op
//PASS


// 字典树实现
//goos: darwin
//goarch: amd64
//pkg: github.com/gotomicro/ekit/bean/copier
//cpu: Intel(R) Core(TM) i5-1030NG7 CPU @ 1.10GHz
//BenchmarkReflectCopier_Copy
//BenchmarkReflectCopier_Copy-8   	 1811790	       701.3 ns/op
//PASS

2022-08-25 02:28 UTC, hhh111119 commented
测试覆盖率低, 是因为之前的实现没有删, 我之后删了应该就没问题了.

2022-08-25 02:29 UTC, hhh111119 commented
还有一个改动是 
NewReflectCopier 返回值我加了一个 error,
因为现在的实现, 类型错误其实在创建的时候就知道了.  不需要等到 copy 的时候去触发

2022-08-25 02:31 UTC, flycash reviewed
字典树的想法非常优秀！
另外我还有一个想打，就是按照道理来说，如果我们在叶子节点里面维持住了 Indexes []int，那么我们可以不必使用递归下去，直接调用 FieldByIndex(Indexes)。按照 reflect 包，应该它们会帮我们处理递归的问题。

在这种设计之下，我们可以考虑把所有的叶子节点串起来，直接遍历叶子节点，然后调用 FieldByIndex，这有两个问题：
- 如果要是中间有字段是指针形态，而且是 Nil，那么 FieldByIndex 会不会 panic
- 它的性能会不会比现在字典树的性能更好
我希望你能尝试一下。

2022-08-25 02:31 UTC, flycash commented on bean/copier/reflect_copier.go
> +				continue
这是什么情况？这里我感觉应该返回一个 error，说明是我们的代码没写好，有漏网之鱼。

2022-08-25 02:31 UTC, flycash commented on bean/copier/reflect_copier.go
> +	srcFieldNameID := make(map[string]int, 0)
srcFieldNameID 改名叫做 srcFieldNameIndex。这个在反射里面其实叫做 Index

2022-08-25 02:31 UTC, flycash commented on bean/copier/reflect_copier.go
> +	isRoot bool
isRoot 貌似用不上，我看你只赋值了，但是并没有使用过。

2022-08-25 02:31 UTC, flycash commented on bean/copier/reflect_copier.go
> +				continue
理论上来说应该 panic 的，因为它属于出乎我们开发者的预料。不过我们无法预计用户会在什么地方使用这个方法，所以还是返回 error 比较好，然后让用户上报一个 issue

2022-08-25 02:31 UTC, flycash commented on bean/copier/reflect_copier.go
> +	srcFieldNameID := make(map[string]int, 0)
其它类似的也改了

2022-08-25 02:31 UTC, flycash commented on bean/copier/reflect_copier_test.go
> +		{
设计用例还需要有：
- Src 有私有字段，并且赋值了，这个字段会被忽略掉
- Dst 有私有字段，也会被忽略掉
- Src 比 Dst 多一些字段，多出来的会被忽略掉
- Dst 比 Src 多一些字段，多出来的也会被忽略掉

有几个地方我想征求一下你的看法，就是要不要支持：
- 假如说 Src 里面的字段是指针  *int，但是 Dst 里面的不是指针，直接就是 int，或者反过来。这种你觉得是否要考虑？
- 从你的代码里面来看，如果 Src 里面的字段是结构体，那么必然会触发复制。但是如果要是 Src 和 Dst 两边一模一样，比如说都有一个字段叫做 SimpleStruct，字段的类型定义一模一样。这种情况下其实不必递归进去 SimpleStruct 里面。这也算是一个深拷贝浅拷贝语义的问题；

2022-08-25 02:31 UTC, flycash commented on bean/copier/reflect_copy_benchmark
> +// 纯递归实现 bench
benchmark 测试加上内存分配的信息。
benchmark 测试要考虑两种情况：
- 简单结构体
- 多层嵌套结构体：字典树和反射的实现，在这个地方应该差异比较大。越是嵌套深的，比如说四五层嵌套，那么字典树的实现就越有优势。

2022-08-25 02:41 UTC, hhh111119 commented on bean/copier/reflect_copier.go
> +				continue
这里主要是 接口这种不拷贝的 , 我之前想的是, 不能拷贝的就不拷贝. 不过返回错误也可以.

2022-08-25 02:43 UTC, hhh111119 commented on bean/copier/reflect_copier_test.go
> +		{
int 和 *int 这种我感觉要不就先不实现了. 感觉会增加挺多逻辑去检查, 我现在是直接在创建的时候 返回类型不匹配的 error.
如果以后需要, 再加上应该也不会很困难.

2022-08-25 02:44 UTC, hhh111119 commented
上面其他的点 我晚上去修一下 ~

2022-08-25 02:55 UTC, flycash commented on bean/copier/reflect_copier.go
> +	dstValue := reflect.ValueOf(dst).Elem()
这个你是不是可以删掉，因为在 CopyTreeNode 里面会进去 if srcValue.Kind == reflect.Pointer 的分支

2022-08-25 02:55 UTC, flycash commented on bean/copier/reflect_copier.go
> +	for i := 0; i < dstTyp.NumField(); i += 1 {
嘿嘿，你这个可能有点被我误导了。这个 createFielNodes 是初始化过程，所以不是特别需要在意性能问题。我们比较在意的是初始化完成之后的 Copy 那个过程。比如说我在应用启动的时候初始化好我这个 Copier，那么你慢一点也没有关系。

所以这个方法其实是可以简写一下的。就是直接对 Src 的字段进行遍历，然后用 FieldByName(srcField.Name)来找对应的 dstField。代码会更好懂一下。

一般来说，就是初始化的这种，整个应用生命周期只执行一次的，就可以不必在意性能。所以我们常见的一个优化手段就是将繁琐的步骤从类似于 Copy 这样的方法里面挪出来，放到初始化过程里面。

2022-08-26 01:34 UTC, hhh111119 commented
新的基准测试
goos: darwin
goarch: amd64
pkg: github.com/gotomicro/ekit/bean/copier
cpu: Intel(R) Core(TM) i5-1030NG7 CPU @ 1.10GHz
// 字典树简单测试
BenchmarkReflectCopier_Copy-8                                    1973594               685.5 ns/op           192 B/op         11 allocs/op
// 纯递归反射简单测试
BenchmarkReflectCopier_Copy_PureRunTime-8                        1000000              1130 ns/op             240 B/op         17 allocs/op

// 字典树 复杂测试
BenchmarkReflectCopier_CopyComplexStruct-8                        410677              3039 ns/op             784 B/op         46 allocs/op
// 纯递归反射复杂测试
BenchmarkReflectCopier_CopyComplexStruct_WithPureRuntime-8        194046              5564 ns/op            1056 B/op         80 allocs/op

2022-08-26 01:35 UTC, hhh111119 commented on bean/copier/reflect_copier.go
> +	for i := 0; i < dstTyp.NumField(); i += 1 {
这里好像不行, FieldByName 只能作用于 reflect.Value, 但这里只有 reflect.Type

2022-08-26 01:38 UTC, hhh111119 commented
> 



> 字典树的想法非常优秀！ 另外我还有一个想打，就是按照道理来说，如果我们在叶子节点里面维持住了 Indexes []int，那么我们可以不必使用递归下去，直接调用 FieldByIndex(Indexes)。按照 reflect 包，应该它们会帮我们处理递归的问题。
> 
> 在这种设计之下，我们可以考虑把所有的叶子节点串起来，直接遍历叶子节点，然后调用 FieldByIndex，这有两个问题：
> 
> * 如果要是中间有字段是指针形态，而且是 Nil，那么 FieldByIndex 会不会 panic
> * 它的性能会不会比现在字典树的性能更好
>   我希望你能尝试一下。


如果要是中间有字段是指针形态，而且是 Nil，那么 FieldByIndex 会不会 panic
这个目前感觉可能实现起来有点问题, 因为如果 Struct 中有一个
Struct 的指针. 我们需要对src 和 dst 的指针判断是否为空来决定后续的操作. 所以好像不能直接遍历叶子节点. 这里不知道大明哥有解决的思路吗.

2022-08-26 02:39 UTC, flycash commented
> > 
> 
> > 字典树的想法非常优秀！ 另外我还有一个想打，就是按照道理来说，如果我们在叶子节点里面维持住了 Indexes []int，那么我们可以不必使用递归下去，直接调用 FieldByIndex(Indexes)。按照 reflect 包，应该它们会帮我们处理递归的问题。
> > 在这种设计之下，我们可以考虑把所有的叶子节点串起来，直接遍历叶子节点，然后调用 FieldByIndex，这有两个问题：
> > 
> > * 如果要是中间有字段是指针形态，而且是 Nil，那么 FieldByIndex 会不会 panic
> > * 它的性能会不会比现在字典树的性能更好
> >   我希望你能尝试一下。
> 
> 如果要是中间有字段是指针形态，而且是 Nil，那么 FieldByIndex 会不会 panic 这个目前感觉可能实现起来有点问题, 因为如果 Struct 中有一个 Struct 的指针. 我们需要对src 和 dst 的指针判断是否为空来决定后续的操作. 所以好像不能直接遍历叶子节点. 这里不知道大明哥有解决的思路吗.

看起来确实是不会自动创建中间 nil 的东西。那就保持这样好了

2022-08-26 02:44 UTC, flycash requested changes
顺便解决一下冲突

2022-08-26 02:44 UTC, flycash commented on .CHANGELOG.md
> +[ekit: 修复 reflect copier](https://github.com/gotomicro/ekit/pull/47)
改成 bean/copier: 实现了基于反射的 ReflectCopier

2022-08-26 02:44 UTC, flycash commented on bean/copier/reflect_copier.go
> +	for i := 0; i < dstTyp.NumField(); i += 1 {
<img width="633" alt="image" src="https://user-images.githubusercontent.com/9923838/186804928-a49a512b-b11c-42a3-a748-d71b877e982c.png">

也是有的呀

2022-08-26 02:44 UTC, flycash commented on bean/copier/reflect_copier_test.go
> +		{
可以的，我觉得 *int 和 int 这种人，正常人都不会这么用。后面抽象出来 converter 之后就可以统一解决

2022-08-26 02:44 UTC, flycash commented on bean/copier/reflect_copier_test.go
> +			name: "结构体有 diff 的情况",
改成 src 有额外字段

2022-08-26 02:44 UTC, flycash commented on bean/copier/reflect_copier_test.go
> +			name: "Copy2 结构体有 diff 的情况",
dst 有额外字段

2022-08-26 08:01 UTC, flycash commented on bean/copier/reflect_copier.go
> +				continue
也可以，就这样留着吧

2022-08-26 09:42 UTC, hhh111119 commented
剩下的点我晚上回去改一下. 纯递归实现我是直接删除吗, 是否 就保留字典树实现就好.

2022-08-26 10:14 UTC, flycash commented
> 剩下的点我晚上回去改一下. 纯递归实现我是直接删除吗, 是否 就保留字典树实现就好.

纯递归的做成一个简单的方法，就不需要定义结构体了。做成包方法:
```go
func CopyTo(src any, val any) error
```

2022-08-26 10:15 UTC, flycash commented
就相当于如果用户如果不在意性能，那么就用包方法，不然他们就可以考虑定义 Copier 来加速

2022-08-26 10:29 UTC, hhh111119 commented
嗯嗯 好的

2022-08-27 10:31 UTC, sp187 commented on bean/copier/reflect_copier.go
> +	for i := 0; i < dstTyp.NumField(); i += 1 {
@hhh111119  使用FieldByName的话，下面这种情况会导致调用拷贝方法时panic掉
```go
type SimpleDst struct {
	Name    string
	Age     *int
	Friends []string
}

type SimpleEmbedDst struct {
	SimpleSrc
}
```

2022-08-27 14:19 UTC, hhh111119 commented on bean/copier/reflect_copier.go
> +	for i := 0; i < dstTyp.NumField(); i += 1 {
> 
@sp187 
嗯嗯, FiledByName 似乎会有一个问题, 就是拿到的 index 不一定是一个层级的. 我看看能不能改, 不行就回退回去.

2022-08-27 14:49 UTC, hhh111119 commented on bean/copier/reflect_copier.go
> +	for i := 0; i < dstTyp.NumField(); i += 1 {
@sp187 已经回退 Filed(i) 了, 添加了对应测试用例, 现在没这问题了. 感谢.

2022-08-28 06:47 UTC, flycash commented
@hhh111119 格式化一下代码。然后把 reflect 的实现挪出去另外有一个文件就可以了

2022-08-28 07:18 UTC, hhh111119 commented
已经修改完毕~
我自己在本地也 gofmt 过, goland 提交的时候也会自动 fmt.
不过 ci 这个过不了, 不知道为啥. 难道是因为我目录中放了了 非 go 的文件吗.
![image](https://user-images.githubusercontent.com/12663407/187062516-8b1f282f-e40c-466e-8988-0f780bd2e5e2.png)

2022-08-28 07:36 UTC, flycash commented
你执行了 make check 之后，只是帮你格式化了代码，你要重新提交一下。
```shell
make[1]: Entering directory '/home/mindeng/workspace/go/src/gotomicro/ekit'
./bean/copier/reflect_copier_test.go
make[1]: Leaving directory '/home/mindeng/workspace/go/src/gotomicro/ekit'
make[1]: Entering directory '/home/mindeng/workspace/go/src/gotomicro/ekit'
make[1]: Leaving directory '/home/mindeng/workspace/go/src/gotomicro/ekit'
```
这个只是帮你格式化了 test.go 这个文件，但是并没有帮你提交

2022-08-28 07:39 UTC, hhh111119 commented
嗯嗯 找到原因了. 我本地之前的 go 环境是 1.15 的, 后来换成 1.18 但是 goimports 没有更新. 已修复.

2022-08-28 07:52 UTC, flycash approved these changes

2022-08-28 07:53 UTC, merged