实现了Taskpool
gotomicro/ekit pull request #56
Opened 2022-08-26 12:11 UTC by flyhigher139

实现了TaskPool

2022-08-27 10:46 UTC, flycash requested changes

2022-08-28 07:29 UTC, flycash requested changes

2022-08-28 07:29 UTC, flycash commented on pool/task_pool.go
> +	return nil
你这种一开始就是开启够了 goroutine 的，按照道理来说不会有问题。但是我担心有些用户这个并发度设置很高，比如说 100。你在注释里面解释清楚，你一开始就会创建好 concurrency 数量的 goroutine，后面反复利用。

2022-08-28 07:29 UTC, flycash commented on pool/task_pool.go
> +				select {
lint 检测到了你这里有问题，单一的 case 不必使用 select 语法

2022-08-28 07:29 UTC, flycash commented on pool/task_pool.go
> +	}
这个不太需要，因为超时我是希望用户自己去管的。我们这里即便管了其实也没管好，比如说 ctx.Done() 这里返回了，但是用户的真实的业务逻辑还在执行。

而且即便你要管，这个代码也不对，你想控制住超时的话，应该是还有一个 select 的 case，里面放 f()。因为你 default 进去，这个 ctx 又没有结束，立刻就进去了 default 分支了。

所以删掉这个方法

2022-08-28 07:29 UTC, flycash commented on pool/task_pool.go
> +						b.emptySignal <- struct{}{}
这里你会发好几次的信号，实际上你只能发一次信号。也就是说，按照你的设计逻辑，这里是每个 goroutine 都会进来一次，然后都会发一个信号。

这里你可能需要使用 once 来控制确保 singnalEmpty 只会触发一次

2022-08-28 07:29 UTC, flycash commented on pool/task_pool.go
> +	if !b.started.Load().(bool) {
你这个不是线程安全的。假如说我在这里判断为 started 是 false，然后我进来，但是还没执行下面你的 emptySignal的语句，这时候我调用了 Start，还是能够 Start，于是紧接着我就调用 Submit，我还是能够成功提交任务。

所以实际上，你不需要一个 forceShutdown 的标记位，你需要一个 Shutdown 的标记位，进来就置为 true。submit 是肯定要检测这个标记位的。

而 shutdown now 则是。置为 true 之后就和别的真正干活的 goroutine 抢任务，抢到的就是返回。
这种做法会导致 shutdown now 不够精准，也就是说在调用 shutdown now 之后，到你返回 []Task 的时候，依旧有任务会被调度走。如果你想做得更精准，那么在调度之前，也要检查一下 shutdown 的那个标记位

2022-08-28 07:29 UTC, flycash commented on pool/task_pool.go
> +	if !b.started.Load().(bool) {
如果我重复调用多次的 shutdown 和 shutdown now，看起来你这里可能会崩溃。所以引入 shutdown 标记位之后，你就可以避免多次调用

2022-08-28 07:29 UTC, flycash commented on pool/task_pool.go
> +	if b.started.Load().(bool) {
如果一个 pool 已经 shutdown 了，不允许它们再次调用。这个条件在注释里面标注一下

2022-08-28 07:29 UTC, flycash commented on pool/task_pool_test.go
> +func NewTaskPoolWithStatus(concurrency, size int, started bool, funcSize int) *BlockQueueTaskPool {
测试的话就都定义成私有的

2022-08-28 07:29 UTC, flycash commented on pool/task_pool_test.go
> +func TestBlockQueueTaskPool_ShutdownNow(t *testing.T) {
你还需要一个联合测试，就是混合测试 shutdown 和 shutdown now 都被调用了

2022-08-28 07:29 UTC, flycash commented on pool/task_pool_test.go
> +		{
要测试重复关闭的

2022-08-28 07:29 UTC, flycash commented on pool/task_pool_test.go
> +		{
要测试重复关闭

2022-08-28 07:29 UTC, flycash commented on pool/task_pool_test.go
> +		},
向 shutdown 和 shutdown now 的提交任务

2022-08-28 07:29 UTC, flycash commented on pool/task_pool_test.go
> +	}
还需要向 shutdown 和 shutdown now 的提交任务的用例

2022-08-28 08:27 UTC, flycash commented
记得检查一下我们的 Github action，把错误都修复一下，然后重新 rebase 到最新 dev 分支上

2022-08-29 05:32 UTC, flyhigher139 commented
@flycash 收到～ 这几天把问题都修复一下！

2022-08-29 06:15 UTC, flyhigher139 commented on pool/task_pool.go
> +	}
我当时写这个方法，主要是由于，任务池的queue里，放的是`func()`，`ShutdownNow()`里要返回`[]Task`，所以要把`func()`包装成`Task`，是不是这一块整体设计的不是很合理？

2022-09-01 13:44 UTC, flycash commented
这个你还要改吗？我准备留着它作为另外一种实现

2022-09-02 01:16 UTC, flyhigher139 commented
> 

@flycash 改的，现在只改了一部分，尽量周末改好，这周上班时间不方便划水，速度慢了

2022-09-02 14:20 UTC, flycash commented
没事，你还在改就可以，我担心你以为我已经合并了一个，所以不要这个了

2022-09-02 16:26 UTC, flyhigher139 commented
> 没事，你还在改就可以，我担心你以为我已经合并了一个，所以不要这个了

改好了，新建一个文件夹放进去了

2022-09-03 06:12 UTC, longyue0521 requested changes

2022-09-03 06:12 UTC, longyue0521 commented on pool/simple/task_pool.go
> +		task, ok := <-b.queue
这里会丢任务或者经常返回[]Task{}.

当close(b.queue)后,当前这个for循环是在和currency个工作go协程“抢”b.queue中未运行的任务,抢到了就将其当作b.queue中未运行的Task返回.要是没抢到b.queue中的任务还是被那currency个工作协程给拿去运行了.

这种情况并不符合ShudownNow的语义,——正在运行中任务不管了,但当ShutdownNow后,那currency个工作go协程不应该再从b.queue中拿任务运行. 

提示: 工作协程中应该监听b.ctx.Done()阻止其抢Task

2022-09-03 06:12 UTC, longyue0521 commented on pool/simple/task_pool.go
> +			b.emptySignal <- struct{}{}
这里不应该由ShutdownNow来发送b.emptySignal,因为ShutdownNow根本不管正在运行中的Task是否运行完毕,它只想阻止工作协程从queue中拿任务并将剩余剩余的未运行的任务返回给调用者.它根本不知道是否有任务在运行,以及那些正在运行中的任务是否完成了.

2022-09-03 07:02 UTC, flyhigher139 commented
@longyue0521 收到～ 我继续优化

2022-09-03 08:20 UTC, flycash requested changes
BlockQueueTaskPool 可以考虑换个名字，叫做 FixedBlockTaskPool? 强调一开始我们就会把所有的 goroutine 建起来？

然后你记得rebase 到最新的 main 分支上。

2022-09-03 08:20 UTC, flycash commented on pool/simple/task_pool.go
> +	Started         atomic.Value
这个可以引入 uber 的 atomic 库，倒也犯不着我们每次都使用类型断言

2022-09-03 08:20 UTC, flycash commented on pool/simple/task_pool.go
> +	}
这里面可能会有并发问题。即如果我在执行 select 的时候，又有另外一个人调用了 Shutdown 或者 ShutdownNow，直接就把 queue 给关闭了。这种情况下，case b.queue <- task 就是朝着关闭的  channel 的发送数据，直接崩溃

2022-09-03 08:20 UTC, flycash commented on pool/simple/task_pool.go
> +	}
如果简单来处理，就是不需要 close queue 那么快，等到最后我们要发 emptySignal 的时候直接关闭 queue 会比较简单一点。
如果我们要立刻 close queue，那么就会需要类似于另外一个 TaskPool 里面的那种互斥机制。即在我提交任务的时候，你不能把 queue 给我关了

2022-09-03 08:32 UTC, flycash commented
我在想，其实这个 TaskPool 可以复用另外一个 TaskPool 的状态管理。而后只是在调度那里有一点不太一样，其它地方都一样。

或者跟进一步，我们把调度这个东西，抽象出来作为一个策略，用户可以自己定制策略。这个策略就是要不要创建新的 goroutine 之类的，以及初始化你要不要全部 goroutine 建起来。

于是到目前我们就有两种策略：
- 按需分配
- 立刻创建

后面我们可以考虑引入类似线程池的初始化goroutine 数量，以及最大 goroutine 数量，goroutine 空闲时间 这种概念，可以做到灵活调度

2022-09-07 01:57 UTC, flyhigher139 commented
> 我在想，其实这个 TaskPool 可以复用另外一个 TaskPool 的状态管理。而后只是在调度那里有一点不太一样，其它地方都一样。
> 
> 或者跟进一步，我们把调度这个东西，抽象出来作为一个策略，用户可以自己定制策略。这个策略就是要不要创建新的 goroutine 之类的，以及初始化你要不要全部 goroutine 建起来。
> 
> 于是到目前我们就有两种策略：
> 
> * 按需分配
> * 立刻创建
> 
> 后面我们可以考虑引入类似线程池的初始化goroutine 数量，以及最大 goroutine 数量，goroutine 空闲时间 这种概念，可以做到灵活调度

@flycash  我一开始做的时候，是考虑按简单的逻辑来实现，后续可以考虑再设计一个类似java线程池的实现。
这个任务池的后续优化，是按保持简单来做，还是向复杂严谨看齐？

2022-09-07 02:40 UTC, flyhigher139 commented on pool/simple/task_pool.go
> +					b.emptySignalOnce.Do(func() {
@longyue0521 这里第6个goroutine发了信号，前5个保持执行至任务自己结束就好了，然后下一轮回来拿task时，发现channel已经关闭，就退出了；所以6发信号时，不用管前5个是不是有任务在运行吧？

2022-09-07 02:54 UTC, longyue0521 commented on pool/simple/task_pool.go
> +					b.emptySignalOnce.Do(func() {
调用者监听到Shutdown返回的chan中有信号(6发出的),调用者立即去查看1~5任务的运行结果,想要去做统计分析,结果发现没有任何结果数据. 详查之下发现1~5任务根本没运行完也没出结果.

这和Shutdown API Doc中宣称的“优雅关闭即一旦chan中有信号,就表示所有任务都自然运行结束了”不相符

2022-09-07 02:58 UTC, longyue0521 commented on pool/simple/task_pool.go
> +					b.emptySignalOnce.Do(func() {
6发的信号所表示的意义,不仅仅是Shutdown这个方法调用成功了,还表示在Shutdown前提交到队列里的任务都被运行了且自然结束了.

2022-09-07 05:58 UTC, flyhigher139 commented on pool/simple/task_pool.go
> +					b.emptySignalOnce.Do(func() {
了解了，所以shutdown的优雅关闭，要等所有任务都执行完成了才发出关闭信号。

不过我对shutdown理解不是这样的。
shutdown要做的事情，我的理解是，要让队列中的任务都能得到执行即可，不用等他们执行完，只要执行了，迟早会执行结束的
所以只要任务队列为空了，就可以shutdown了
而ShutdownNow的立即结束，是指如果有任务在队列中，不给这些任务执行的机会了，直接结束，这些任务从队列中取出来返回。

shutdown时，我认为没必要等正在执行的任务告知pool执行结束，再让pool结束。因为既然把任务提交到任务池执行了，已经是异步的，调用方本来就会等待任务结束（或超时退出），调用方关心的始终是任务，没必要监听任务池的状态

所以，我是按任务队列为空就让任务池结束来实现的

2022-09-07 07:28 UTC, flyhigher139 commented on pool/simple/task_pool.go
> +	}
@flycash  嗯，这个并发问题我也发现了。我先简单粗暴改了一下，思路是这样的：

这个SimpleTaskPool，是一个简单的轻量级任务池，不建议在高并发高性能的场景下使用，所以这个并发问题发生的概率不高。因此，如果发生这个并发问题造成panic时，直接recover掉，recover的主要逻辑是，把这个任务重新提交一次，这时由于任务池已经关闭了，就直接返回错误了

直接这么简单粗暴处理，是否合适？

```go
func (b *BlockQueueTaskPool) Submit(ctx context.Context, task Task) (err error) {
	defer func() {
		if recover() != nil {
			err = b.Submit(ctx, task)
		}
	}()
	if b.Closed.Load().(bool) {
		return errTaskPoolClosed
	}
	select {
	case b.queue <- task:
		return nil
	case <-ctx.Done():
		return ctx.Err()
	}
}
```

2022-09-07 07:39 UTC, flyhigher139 commented on pool/simple/task_pool.go
> +		task, ok := <-b.queue
好的～ 我改一下。

之前这里确实是放水了，考虑的是，ShutdownNow抢到几个就返回几个，没抢到的还是让它执行下去，问题也不大，就没想怎么严格实现这个功能。

2022-09-07 09:37 UTC, longyue0521 commented on pool/simple/task_pool.go
> +					b.emptySignalOnce.Do(func() {
调用放并没有监听任务池的状态,Shutdown返回的chan表示的不是任务池自身的状态(任务池自身的状态按照你的设计是started和closed),而是正在运行中的任务是否全部自然运行结束,换句话说Shutdown方法是一个中介它能感知到任务是否运行结束,然后以close掉chan的方式发送给调用者一个通知——你等待,正在运行中的任务已经结束了.

关于任务池的设计问题可以到 #50 讨论,建议在实现前讨论清楚需求

2022-09-08 10:19 UTC, flycash commented
可以的，先系统设计一下。因为我们已经有一个基础实现了，所以这个可以慢慢设计。我比较希望把它做成一个标杆=。=其它人可以参考它的状态控制，和它的 goroutine 增长策略抽象

2022-09-08 10:42 UTC, longyue0521 commented
👍 你可以先把设计思路发布到 #50 我们一起讨论一下再实现

2022-09-08 12:28 UTC, flyhigher139 commented
好的～ 我后面设计好，先发到 #50 上去讨论

2022-09-23 09:15 UTC, flycash commented
你可以看最新的代码，我觉得我们已经实现了一个很不错的了，这个我就先关了

2022-09-23 09:15 UTC, closed without merging