pool: TaskPool 实现 #50
gotomicro/ekit pull request #57
Opened 2022-08-27 07:32 UTC by longyue0521

TaskPool管理有限状态机，TaskExecutor负责启动任务，优雅关闭，强制退出等操作

Signed-off-by: longyue0521 <longyueli0521@gmail.com>

2022-08-27 07:37 UTC, longyue0521 commented
这个项目第一次提PR,忘了在本地setup了

2022-08-28 08:26 UTC, flycash requested changes
我觉得我大概看明白了。我有一些关于使用场景上的疑问：
按照 chanByTask 的逻辑，很显然如果用户得知道自己是不是需要使用 SlowTask。那么问题就在于，如果用户知道哪个是 slow task，它完全可以自己创建一个单独的 pool，然后不是 slow task，他就自己开 goroutine 来解决了。所以这么引入 slow queue 和 fast queue 是为了解决什么问题？

即便真需要解决场景，我觉得这样子更好：
- 你有一个 pool 的实现，就是来一个我就处理一个，也就是 fast 的，直接开 goroutine
- 你还有一个 pool 的实现，就是 slow 的，然后按照固定 goroutine 数量来调度
- 你最终有一个 pool 的实现，就是把两者结合在一起
我觉得这种设计要比 slow 和 fast 都塞进去一个要好一点。因为我们有非常清晰的三种 pool。

另外关于 panic 的处理，我们可以内部定义个 task 的结构体：
```go
type wrapTask struct {
    t Task
}

func (wrapTask) Run(ctx context.Context) error {
    defer func() {
            // 处理 panic 
    }
    // 后续如果我们暴露了处理 error 的回调，那么可以在这里扩展
}
```
即 panic 之类的这种问题，我们自己用装饰器来处理掉，那么在 pool 里面就剩下纯粹的调度逻辑了。

2022-08-28 10:26 UTC, longyue0521 commented on .CHANGELOG.md
> +[ekit: 实现了 TaskPool](https://github.com/gotomicro/ekit/pull/57)
```
所以这么引入 slow queue 和 fast queue 是为了解决什么问题？
```
在需求描述中 #50 有快慢任务分离的描述并且`task_pool.go`中只定义了`NewBlockQueueTaskPool`

```go
// NewBlockQueueTaskPool 创建一个新的 BlockQueueTaskPool
// concurrency 是并发数，即最多允许多少个 goroutine 执行任务
// queueSize 是队列大小，即最多有多少个任务在等待调度
func NewBlockQueueTaskPool(concurrency int, queueSize int) (*BlockQueueTaskPool, error) {
	return &BlockQueueTaskPool{}, nil
}
```
我以为需要在`NewBlockQueueTaskPool`中实现“快慢分离”的需求所以要有个区分“快”与“慢”的标准,这才有了SlowTask和FastTask结构体,进而有了slow queue 和 fast queue.

通过上面的讨论来,这个区分“快”和“慢”的标准是根据构造函数来的——用户通过指定最大go协程数,不指定就是不限制.比如这个`NewBlockQueueTaskPool`要实现的就是指定最大go协程数的TaskPool

我认为只需要提供限制最大go协程数和不限最大go协程数的TaskPool实现,不需要再提供整合前两者的TaskPool这个可以留给有需求的用户自己封装.

还想和你讨论一下这两种类型TaskPool的构造函数的API设计,我想显示分开表明意图如下代码,我把concurrency和queueSize换了顺序.
```go
// 限制Goroutine数量
func NewBlockQueueTaskPoolWithLimitGoroutine(queueSize int, concurrency int) (*BlockQueueTaskPool, error) {
	return &BlockQueueTaskPool{}, nil
}
// 不限制Goroutine数量
func NewBlockQueueTaskPool(queueSize int) (*BlockQueueTaskPool, error) {
         // concurrency为0表示不限制goroutine个数
	return NewBlockQueueTaskPoolLimitGo(queueSize, 0)
}
```
上面那个API能明确表示意图但是有点丑,的名字有点丑,你有什么更好的建议吗? 

或者还是只用`NewBlockQueueTaskPool(concurrency int, queueSize int) `但在注释中声明“concurrency>0“时限制go协程数,<=0时不限制.

2022-08-28 10:38 UTC, flycash commented on .CHANGELOG.md
> +[ekit: 实现了 TaskPool](https://github.com/gotomicro/ekit/pull/57)
其实我是觉得说，如果我们需要一个不限制 goroutine 数量的，那么用户为什么不直接开启 goroutine 呢？我们自己开 goroutine 和用户直接开 goroutine，我们好像没有什么优势。

我在任务描述里面是交代了背景，当时我是觉得说只有慢任务我们才需要考虑使用 TaskPool，快任务在我预期中是用户直接开 goroutine 的

2022-08-29 02:53 UTC, longyue0521 commented on .CHANGELOG.md
> +[ekit: 实现了 TaskPool](https://github.com/gotomicro/ekit/pull/57)
好的

2022-08-29 02:53 UTC, longyue0521 commented on pool/task_pool.go
> +	ErrTaskIsInvalid        = errors.New("pool: Task非法")
已改为私有

2022-08-29 03:16 UTC, hhh111119 commented on pool/task_pool_test.go
> +				<-time.After(1 * time.Millisecond)
<-time.After 是不是直接用 time.Sleep 更清楚一些.

2022-08-29 03:33 UTC, hhh111119 commented on pool/task_pool.go
> +			go b.startTasks()
这里有一个疑问, 是否需要 defer 捕获异常, 防止协程崩了导致进程崩了. 还是说要用户自己考虑这个问题.

2022-08-29 04:54 UTC, longyue0521 commented on pool/task_pool.go
> +		// 处理 panic
现阶段运行Task.Run()的go协程对其返回的error没有明确的处理方式,所以为了方便调试我选择打印出来看看是否符合预期,最新的提交已改为将panic封装为error返回

2022-08-29 05:36 UTC, longyue0521 commented on pool/task_pool.go
> +			go b.startTasks()
为了安全起见需要defer捕获panic,但我不知道捕获panic后要做什么?我认为在b.startTasks()中真的出现panic也是不可恢复的所以选择崩掉,你可以看看哪些场景可能导致b.startTasks() panic

另外,我在Shutdown方法中也开启了一个go协程,用于监视运行中Task的数量等其为0时以close(b.done)的方式通知外部调用者. 这里感觉没有明显能导致panic的地方,也要defer捕获panic? 但捕获后如何通知外部调用者呢?

欢迎说说你的看法

```go
// Shutdown方法中放出go协程
go func() {
	// 等待运行中的Task自然结束
	for atomic.LoadInt32(&b.num) != 0 {
	    time.Sleep(time.Second)
	}
       // 通知外部调用者
      close(b.done)
      // 完成最终的状态迁移
      atomic.CompareAndSwapInt32(&b.state, stateClosing, stateStopped)
}()
```

2022-08-29 05:36 UTC, longyue0521 commented on pool/task_pool_test.go
> +				<-time.After(1 * time.Millisecond)
已改为time.Sleep

2022-08-29 06:18 UTC, flycash requested changes

2022-08-29 06:18 UTC, flycash commented on pool/task_pool.go
> +				atomic.CompareAndSwapInt32(&b.state, stateClosing, stateStopped)
这边用 sleep 的方式还是稍微有点丑。按照道理来说，应该是调度任务执行那里，也就是 startTasks 那里，它在发现 channel 为空之后，判断一下目前是不是 closing 的状态，是的话就发送信号

2022-08-29 06:18 UTC, flycash commented on pool/task_pool.go
> +		if atomic.LoadInt32(&b.state) == stateStopped {
不需要缓存，直接禁止它重复调用，返回错误。类似地，shutdown 和 start 两个方法都是这样，正常的做法是不存在调用多次的可能的。我们想，正常用户会怎么用这个 TaskPool呢？一般也就是应用启动，或者初始化的时候，创建好，然后在应用结束的时候关掉。最多就是在关掉的时候想知道还有多少任务没有执行。
也就是，正常人都不会调用多次。

2022-08-29 06:18 UTC, flycash commented on pool/task_pool.go
> +			for task := range b.queue {
这里是不是要判断一个 ok? 因为 queue 被关了之后，我记得是每次读都能读到零值

2022-08-29 06:18 UTC, flycash commented on pool/task_pool.go
> +	if task == nil || reflect.ValueOf(task).IsNil() {
我感觉判断是不是 nil 就可以了。至于 Task(nil) 这种，不需要去管。甚至于我觉得连判断都不需要，后面调度的时候直接 panic。这也是一种设计方面的取舍，就是我一般都是防呆不防傻。类似这种 nil，我觉得除非是故意捣蛋，不然谁能写出这种代码

2022-08-29 06:18 UTC, flycash commented on pool/task_pool.go
> +	if atomic.CompareAndSwapInt32(&b.state, state, stateLocked) {
我觉得这个 stateLocked 是不是可以去掉了？我没看到这个 stateLocked 在别的地方使用到。按照道理来说这种应该在多个地方使用了，因为你需要用 locked 这个状态来达成互斥的效果。
这里我猜测你是在顾虑这样一个问题，就是你刚检测到它的状态还处于 running，结果下一刻就变成了 closing，所以你觉得这时候不能提交任务。实际上我的看法是我们不需要做那么精准，只要我判断的那一刻是可以提交的，我后面就继续提交，你 closing 不 closing 没关系。唯一要担心的就是这种情况下，会出现阻塞很久，最终走到 ctx.Done 里面去。这最终也算是帮我们达成了阻塞提交的效果

2022-08-29 06:18 UTC, flycash commented on pool/task_pool.go
> +			go b.startTasks()
用户的 task 是否需要捕捉 panic，很显然，用户是不会有这种意识的。在他看来，panic 就 panic 了，他也就是业务失败了，影响到了他自己。但是 panic 这个东西还会影响到我们。也就是，如果 TaskPool 是一开始就把所有的 goroutine 创建起来，后面都是这些 goroutine 调度的话，那么就需要 TaskPool 显式保护起来。否则 panic 会导致这些提前建立好的 goroutine 直接崩溃掉。
但是如果 TaskPool 是每个 task 都是新建的一个 goroutine（只是控制了 goroutine的数量），那么 TaskPool 即便不处理 panic 也没太大的问题，因为这个 goroutine 崩溃了，你下一个任务又是一个新的 goroutine。

2022-08-29 11:30 UTC, longyue0521 commented on pool/task_pool.go
> +	if task == nil || reflect.ValueOf(task).IsNil() {
已修改

2022-08-29 11:30 UTC, longyue0521 commented on pool/task_pool.go
> +			for task := range b.queue {
不需要,for-range会自动处理channel被close的情况,https://gobyexample.com/range-over-channels

2022-08-29 11:30 UTC, longyue0521 commented on pool/task_pool.go
> +		if atomic.LoadInt32(&b.state) == stateStopped {
已修改

2022-08-29 11:31 UTC, longyue0521 commented on pool/task_pool.go
> +			if task == nil {
这里其实是根据task即接口与nil比较来判断b.queue是否关闭,有点晦涩难懂, 已改为`task, ok := <-b.queue if !ok { return } `

2022-08-29 13:04 UTC, flycash commented on .CHANGELOG.md
> +[ekit: 实现了 TaskPool](https://github.com/gotomicro/ekit/pull/57)
你要重新 rebase 到最新的代码，这些应该是我整理过的。

2022-08-29 14:14 UTC, longyue0521 commented on pool/task_pool.go
> +				atomic.CompareAndSwapInt32(&b.state, stateClosing, stateStopped)
Shutdown的需求是返回一个channel,一旦从channel中拿到值就表示所有Task全部执行结束.
```go
startTasks 那里，它在发现 channel 为空之后，判断一下目前是不是 closing的状态，是的话就发送信号
```
这版的实现这样做不行,因为Closing状态表示“有正在运行的Task”,而所有任务结束的最准确标志是——计数为0.我的实现类似于``我注意到之前的讨论中提及的TaskPool两种实现方法

最新提交的实现用sync.WaitGroup干掉了`for atomic.LoadInt32(&b.num) != 0 {time.Sleep(time.Second)}`,思路就是在close(b.queue)之前不调用wg.Wait()

2022-08-29 14:30 UTC, longyue0521 commented on .CHANGELOG.md
> +[ekit: 实现了 TaskPool](https://github.com/gotomicro/ekit/pull/57)
做过了最后一个就是我新加入的`[ekit: 实现了 TaskPool](https://github.com/gotomicro/ekit/pull/57)`

2022-08-29 15:47 UTC, longyue0521 commented on pool/task_pool.go
> +	if atomic.CompareAndSwapInt32(&b.state, state, stateLocked) {
stateLocked不能去掉

它的作用是防止trySubmit阻塞期间被Shutdown和ShutdownNow抢占试进行状态迁移.因为状态迁移期间会close(b.queue).当用户使用`pool.Submit(context.Background(), task)`时,ctx.Done()会一直阻塞即依赖用户传入的ctx.Done不靠谱,而恰巧此时`b.queue<-task`也阻塞那么会一直阻塞在这里而出现无法Shutdown和ShutdownNow的情况,这也是为什么select中要有default原因——即给用户Submit提交任务的机会,也给了用户Shutdown和ShutdownNow的机会.

如果没有stateLocked保护,Shutdown和ShutdownNow在close(b.queue)时会导致`b.queue<-task`panic - send on closed channel.即使用defer接住panic,恐怕也无法准确报错让调用者知道发生了什么,并决定下一步该干什么——是因为Shutdown还是ShutdownNow而导致panic即使能通过扫描调用栈信息做到也太过丑陋.

其实可以将进入trySubmit到离开trySubmit看作是分配给Submit提交任务的时间片,当执行流程离开trySubmit后,就是下一次trySubmit与Shutdown,ShutdownNow竞争先到先得

2022-08-30 12:44 UTC, flycash reviewed
测试比较依赖于 sleep，这个我们后面再来优化它。我稍微有点担心后面在跑 CI 的时候，sleep 一毫秒的情况，可能因为一些乱七八糟的原因，引起了偶发性的失败

2022-08-30 12:44 UTC, flycash commented on .CHANGELOG.md
> +[ekit: 实现了 TaskPool](https://github.com/gotomicro/ekit/pull/57)
不对呀，要是你还原回去的话，我应该看不到这些修改。你重新 rebase 一下

2022-08-30 12:44 UTC, flycash commented on pool/task_pool.go
> +			var tasks []Task
这里可以直接根据 queque 的容量来创建，这样肯定不会引起扩容的问题

2022-08-30 12:44 UTC, flycash commented on pool/task_pool_test.go
> +			testSubmitBlockingAndTimeout(t, pool)
testSubmitBlockingAndTimeout 里面的 2 有点迷，你改成获得 pool 中 channel 的容量 + 1。

2022-08-30 12:44 UTC, flycash commented on pool/task_pool_test.go
> +			n := 5
queueSize := 2
n = queueSize + 3
前面用 queueSize 来创建 pool。这样改动不是为了我们两个，我们两个都能看懂，是为了后面的维护者能看懂这段

2022-08-30 12:44 UTC, flycash commented on pool/task_pool_test.go
> +	assert.NotEmpty(t, tasks)
按照设计，到这里这个 tasks 应该是还有 20 个，那么可以直接断言长度为 20

2022-08-30 12:44 UTC, flycash commented on pool/task_pool_test.go
> +	// 重复调用
还有两个测试用例？
- closing 的时候调用 start
- stopped 的时候调用 start

2022-08-30 12:44 UTC, flycash commented on pool/task_pool_test.go
> +func TestTaskPool_Shutdown(t *testing.T) {
shutdown 和 shutdownnow 都还需要一个 created 状态就调用这两个方法的测试用例

2022-08-30 13:06 UTC, longyue0521 commented on pool/task_pool_test.go
> +func TestTaskPool_Shutdown(t *testing.T) {
已经有了,在`TestTaskPool__Created_`中,我准备将其及其他测试状态的方法名重命名为`TestTaskPool__In_Created_State`.你觉得怎么样?

2022-08-30 13:10 UTC, longyue0521 commented on pool/task_pool_test.go
> +	// 重复调用
已经有了,分别在`TestTaskPool__Closing_`和`TestTaskPool__Stopped_`中

2022-08-30 13:15 UTC, longyue0521 commented on pool/task_pool_test.go
> +			testSubmitBlockingAndTimeout(t, pool)
已修改

2022-08-30 18:14 UTC, longyue0521 commented on pool/task_pool_test.go
> +			testSubmitBlockingAndTimeout(t, pool)
已修改

2022-08-30 18:14 UTC, longyue0521 commented on pool/task_pool.go
> +			var tasks []Task
已修改

2022-08-30 18:15 UTC, longyue0521 commented on pool/task_pool_test.go
> +			n := 5
已修改

2022-08-30 18:15 UTC, longyue0521 commented on pool/task_pool_test.go
> +func TestTaskPool_Shutdown(t *testing.T) {
已存在,在`TestTaskPool__Created_`中,最新提交重命名为`TestTaskPool_In_Created_State`

2022-08-30 18:15 UTC, longyue0521 commented on pool/task_pool_test.go
> +	assert.NotEmpty(t, tasks)
无法准确断言个数,因为只能优化为len(tasks)>0——前面已将ShutdownNow()中tasks声明修改为tasks:=make([]Task, 0, len(b.queue))

最新提交在TestTestPool_In_Stopped_State/ShutdownNow

2022-08-31 07:28 UTC, flycash approved these changes

2022-08-31 07:31 UTC, merged

2022-08-31 07:31 UTC, flycash commented
我要想想怎么设计一个模糊测试来测试我们这种结构，确保在长期运行的时候不会出现什么乱七八糟的情况