实现了contains.go,diff.go的一部分,map.go,并添加测试用例
gotomicro/ekit pull request #71
Opened 2022-09-01 14:39 UTC by zoupengyu3517

2022-09-01 15:20 UTC, zoupengyu3517 commented
基本思路:
1.集合和元素比较时,直接遍历比较。
2.集合和集合间比较时,首先考虑用哈希表临时存储,比双重循环复杂度低。
  当泛型实现comparable 接口时,可以作为哈希表的key.但是自定义equal函数时不行,所以用双重循环实现了部分函数。
优化:哈希表的put 比较消耗资源,某些场景可以把size 较小的切片作为key,比如求并集时。
3.map 操作好像语法不允许用切片作为函数接受者,同时再声明一个泛型作为目标转换类型,从而不能链式调用。reduce,filter似乎可以设计成链式。

2022-09-01 15:55 UTC, flycash requested changes
很不错！
还需要你为这些公共 API 提供一些例子，可以参考。例子里面不需要单元测试那么详细，提供最典型的就可以了
https://github.com/gotomicro/ekit/blob/dev/sqlx/json_test.go#L133

2022-09-01 15:55 UTC, flycash commented on slice/contains.go
> +	mp := make(map[T]bool)
指定容量

2022-09-01 15:55 UTC, flycash commented on slice/diff.go
> +
居然你 diff 没写完的话，就还原它吧，我看到另外一个人提了合并请求了。

2022-09-01 15:57 UTC, flycash commented
> 

其实我之前打算参考 java 的 stream API 来设计链式调用的。但是 API 还没特别好的想法，因为 stream API 我希望和集合类型，也就是 List Tree 之类的结合在一起。

Go 泛型很多限制，你要是有想法，可以设计一下 API，但是要注意先发一个草稿 API，我们可以在那里讨论 API 设计。

2022-09-01 15:57 UTC, flycash commented
记得格式化一下代码，然后为新文件加上 license，在 CHANGELOG 里面加上这个合并请求

2022-09-02 03:28 UTC, flycash commented
<img width="669" alt="image" src="https://user-images.githubusercontent.com/9923838/188053476-2bb5a95c-7fc4-4079-8235-47e204f150a3.png">
看看

2022-09-02 04:49 UTC, longyue0521 requested changes

2022-09-02 04:49 UTC, longyue0521 commented on slice/contains_test.go
> +		},
测试用例不够全面

|src| dst|
|---|---|
nil      |      nil, []T{}, []T{x}, []T{x, y}
[]T{}    |     同上
[]T{x}.  |    同上
[]T{x, y} |   同上

上面用例中某些用例还要考虑Contains返回true和false两大类,比如[]T{x}和[]T{x}形式,要分别测到返回会true和false

2022-09-02 04:49 UTC, longyue0521 commented on slice/contains_test.go
> +	fmt.Println(contains)
需要末尾需要注释 明确输出https://go.dev/blog/examples

2022-09-02 05:09 UTC, longyue0521 requested changes

2022-09-02 05:09 UTC, longyue0521 commented on slice/map.go
> +	var res []Dst
这里可以加一个根据len(src)的fast path判定快速返回,当然也可以src为nil,那就返回nil,src为[]Src{}你就返回[]Dst{}

在初始化res时根据len(src)提前分配好容量,防止后续自动扩容

2022-09-02 05:09 UTC, longyue0521 commented on slice/map.go
> +		res = append(res, m(index, elem))
其实所有出入的func比如这里还需要考虑m func(idx int, src Src)  Dst如果发生panic怎么办? 
一般会在doc中说明不理会

2022-09-02 07:39 UTC, zoupengyu3517 commented on slice/map.go
> +		res = append(res, m(index, elem))
谢谢您的建议,按照您的建议修改了

2022-09-02 10:31 UTC, longyue0521 requested changes

2022-09-02 10:31 UTC, longyue0521 commented on slice/contains.go
> +	if src == nil || len(src) == 0 {
不管src为nil还是[]T{},len(src)都为0,只用len(src)就可以了.

2022-09-02 10:31 UTC, longyue0521 commented on slice/contains.go
> +	if src == nil || len(src) == 0 {
同上

2022-09-02 10:31 UTC, longyue0521 commented on slice/contains_test.go
> +		},
contains实现虽然简单一看就知道对错,但却可以利用它来学习测试用例设计.
一个相对完善的测试用例设计大概如下:
|src|dst|
|--|--|
|nil| nil, []T{}, []T{x}, []T{y,z}|
|[]T{}|nil, []T{}, []T{x}, []T{y,z}|
|[]T{1}|nil, []T{}, []T{x}, []T{y,z}|
|[]T{2, 3}|nil, []T{}, []T{x}, []T{y,z}|

另外你要考虑
前置条件:src=[]T{1}, dst=[]T{x}即src中只包含一个元素,dst只包含一个元素,
contains为true的情况,
contains为false的情况

2022-09-02 10:31 UTC, longyue0521 commented on slice/contains_test.go
> +		{
根据上面的提示补充一下缺少的测试用例

2022-09-02 10:31 UTC, longyue0521 commented on slice/contains_test.go
> +		{"dst和src为nil", args{nil, nil}, false},
根据上面的提示补充一下缺少的测试用例

2022-09-02 10:31 UTC, longyue0521 commented on slice/contains_test.go
> +		{"dst和src为nil", args{nil, nil, f}, false},
根据上面的提示补充一下缺少的测试用例

2022-09-02 10:31 UTC, longyue0521 commented on slice/contains_test.go
> +		{name: "dst和src为nil", args: args{nil, nil}, want: false},
根据上方提示补充一下缺少的测试用例,比如src和dst都只含有一个元素,ContainsAll返回true或false的情况

2022-09-02 10:31 UTC, longyue0521 commented on slice/contains_test.go
> +		{name: "dst和src为nil", args: args{nil, nil, f}, want: false},
同上

2022-09-02 10:31 UTC, longyue0521 commented on slice/map.go
> +		res = append(res, m(index, elem))
报歉,我的话可能误导你了,咱们这里的设计是不理会m中的panic,前面的ContainsFunc等也是,所以只在方法的doc上说明不会处理m中的panic即可. 不用内部处理panic,把这部分代码去掉吧

不用客气 欢迎继续提PR

2022-09-02 10:31 UTC, longyue0521 commented on slice/map_test.go
> +			name: "发生panic",
这个去掉吧

2022-09-02 12:08 UTC, flycash commented
![image](https://user-images.githubusercontent.com/9923838/188139642-044d509c-5f20-4181-890e-e7c6c78f31d0.png)
一个个检查过去吧……

2022-09-02 12:23 UTC, longyue0521 commented
同步到最新的代码 然后再ekit的根目录下 执行`make setup`等待安装所需工具,可以查看makefile中常用的命令,git commit/push的时候注意提示信息

2022-09-05 11:56 UTC, flycash commented
还是各种崩=。=

2022-09-07 09:20 UTC, zoupengyu3517 commented
执行了make setup 之后，goimports 似乎没有正确安装，本地git提交不了= =
错误信息:
17:18:45.476: [ekit] git -c credential.helper= -c core.quotepath=false -c log.showSignature=false add --ignore-errors -A -f -- slice/map.go slice/map_test.go slice/contains_test.go
17:18:45.489: [ekit] git -c credential.helper= -c core.quotepath=false -c log.showSignature=false commit -F /tmp/git-commit-msg-.txt "--author=zoupengyu3517 <86946716+zoupengyu3517@users.noreply.github.com>" --
./script/goimports.sh: 15: goimports: not found
make[1]: *** [Makefile:15: fmt] Error 127
make: *** [Makefile:27: check] Error 2
执行检查中...
[ERROR]: 有文件发生变更，请将变更文件添加到本次提交中

2022-09-07 09:53 UTC, longyue0521 commented
1. 安装`go install golang.org/x/tools/cmd/goimports@latest`,需要能上外网或者配置goproxy
3. 进入slice目录下执行`goimports -l -w .`(其实等效于`make fmt`)

2022-09-07 17:26 UTC, zoupengyu3517 commented
> 1. 安装`go install golang.org/x/tools/cmd/goimports@latest`,需要能上外网或者配置goproxy
> 2. 进入slice目录下执行`goimports -l -w .`(其实等效于`make fmt`)
> 3. go install好像会将其放在go的bin目录里,而这本bin目录一般在path下,确认一下

配了下环境变量,goimports 的问题解决了。
但是git-hub 那个预提交的error仍然存在。

日志:
01:23:46.723: [ekit] git -c credential.helper= -c core.quotepath=false -c log.showSignature=false add --ignore-errors -A -f -- slice/map.go slice/map_test.go slice/contains_test.go
01:23:46.727: [ekit] git -c credential.helper= -c core.quotepath=false -c log.showSignature=false commit -F /tmp/git-commit-msg-.txt "--author=zoupengyu3517 <86946716+zoupengyu3517@users.noreply.github.com>" --
执行检查中...
[ERROR]: 有文件发生变更，请将变更文件添加到本次提交中

是./.github/pre-commit.sh 打印出的日志
`RESULT=$(make check)
printf "执行检查中...\n"
if [ -n "$RESULT" ]; then
  echo >&2 "[ERROR]: 有文件发生变更，请将变更文件添加到本次提交中"
  exit 1
fi

exit 0`

2022-09-08 03:33 UTC, longyue0521 commented
1. pre-commit里执行的其实就是`make check`命令,你可以单独执行一下这个命令看看是否报错?
2. 不要跳过pre-commit,因为你会忘记在每次提交前`make check`
3. 根据提示可能是git的问题,你可以考将原git彻底卸载,再重新装一下最新版本的git
4. 别忘了执行`make setup`

2022-09-08 10:06 UTC, zoupengyu3517 commented
> 1. pre-commit里执行的其实就是`make check`命令,你可以单独执行一下这个命令看看是否报错?
> 2. 不要跳过pre-commit,因为你会忘记在每次提交前`make check`
> 3. 根据提示可能是git的问题,你可以考将原git彻底卸载,再重新装一下最新版本的git
> 4. 别忘了执行`make setup`
> 
> 如果还是不行 在群里问问其他人 没准有人遇到过



> 1. pre-commit里执行的其实就是`make check`命令,你可以单独执行一下这个命令看看是否报错?
> 2. 不要跳过pre-commit,因为你会忘记在每次提交前`make check`
> 3. 根据提示可能是git的问题,你可以考将原git彻底卸载,再重新装一下最新版本的git
> 4. 别忘了执行`make setup`
> 
> 如果还是不行 在群里问问其他人 没准有人遇到过



> 1. pre-commit里执行的其实就是`make check`命令,你可以单独执行一下这个命令看看是否报错?
> 2. 不要跳过pre-commit,因为你会忘记在每次提交前`make check`
> 3. 根据提示可能是git的问题,你可以考将原git彻底卸载,再重新装一下最新版本的git
> 4. 别忘了执行`make setup`
> 
> 如果还是不行 在群里问问其他人 没准有人遇到过

1.单独执行不报错控制台显示:

make: 进入目录“/home/zpy/goProjicets/ekit”
make[1]: 进入目录“/home/zpy/goProjicets/ekit”
make[1]: 离开目录“/home/zpy/goProjicets/ekit”
make[1]: 进入目录“/home/zpy/goProjicets/ekit”
make[1]: 离开目录“/home/zpy/goProjicets/ekit”
make: 离开目录“/home/zpy/goProjicets/ekit”

2 我觉得应该不是git问题,可能是make这是pre-commit.sh的脚本:

`RESULT=$(make check)
printf "执行检查中...\n"

if [ -n "$RESULT" ]; then
  echo >&2 "[ERROR]: 有文件发生变更，请将变更文件添加到本次提交中"
  exit 1
fi

exit 0`

大概意思是make check 有返回就打印error提示并异常退出,否则正常退出。
问题可能出在我执行这个命令不知道为啥会把这些进/退出 目录的日志打出来...

2022-09-08 10:38 UTC, longyue0521 commented
你可以试着找找禁止make命令输出“进入/离开目录....”log的方式

2022-09-09 15:25 UTC, flycash commented
#83 我自己实现了，感谢了！！

2022-09-09 15:25 UTC, closed without merging