实现切片的diff方法
gotomicro/ekit pull request #72
Opened 2022-09-01 14:44 UTC by penbox

基本思路就是通过双重循环来找不同的元素，首先做一次双重循环查找src切片中的不同元素，然后再做一次双重循环查找dst切片中的不同元素。
第一次设计测试用例，不知道有没有考虑得够充分，请大老师多多指教。

2022-09-01 15:39 UTC, flycash requested changes
你需要为这两个方法提供例子，也就是 Example，你可以看我在 issue 里面贴出来的那个地址，也可以参考这个：
```go
func ExampleJsonColumn_Value() {
	js := JsonColumn[User]{Valid: true, Val: User{Name: "Tom"}}
	value, err := js.Value()
	if err != nil {
		fmt.Println(err)
	}
	fmt.Print(string(value.([]byte)))
	// Output:
	// {"Name":"Tom"}
}

func ExampleJsonColumn_Scan() {
	js := JsonColumn[User]{}
	err := js.Scan(`{"Name":"Tom"}`)
	if err != nil {
		fmt.Println(err)
	}
	fmt.Print(js.Val)
	// Output:
	// {Tom}
}
```
在 sqlx 的 json_column_test 里面。例子只需要提供一个 src 和 dst 都有差异的就可以了。

2022-09-01 15:39 UTC, flycash commented on slice/diff.go
>  func Diff[T comparable](src, dst []T) []T {
这个被我声明成为泛型约束使用 comparable，是希望使用 map 来计算的=。=。下面那个 Func 才是双重循环

2022-09-01 15:40 UTC, flycash commented
changelog 检测是希望你能在 .CHANGELOG 文件里面把这个合并请求添加进去

2022-09-01 15:40 UTC, flycash commented
测试用例设计得很好

2022-09-01 15:58 UTC, flycash commented
我觉得有一个地方我没有讲清楚，Diff 是指 src - dst，也就是 src 中 dst 没有的。反过来的不需要考虑，我们需要另外一个方法

2022-09-01 16:18 UTC, flycash commented
https://baike.baidu.com/item/%E5%AF%B9%E7%A7%B0%E5%B7%AE%E9%9B%86/1739582
对称差集，所以你可以加两个方法：
SymmetricDiff
SymmetricDiffFunc

2022-09-02 07:18 UTC, penbox commented
实现了contains方法，并用contains方法重写了diff方法。

2022-09-02 11:21 UTC, flycash approved these changes

2022-09-02 11:22 UTC, flycash commented
执行一下 make check，有一些代码格式化的问题。

2022-09-02 11:22 UTC, flycash commented
![image](https://user-images.githubusercontent.com/9923838/188128991-cf723d07-d673-4bfa-a314-87c0feb11e9b.png)

2022-09-02 12:04 UTC, flycash requested changes

2022-09-03 08:05 UTC, flycash requested changes
ContainsAll 和 ContainsAllFunc 的语义在 dst 为 nil 或者长度为 0 的时候，都应该返回 true。这个主要是为了和别的语言的类似框架保持语义一致，例如在 Java 的 containsAll 里面，就是返回 true。

2022-09-03 08:05 UTC, flycash commented on slice/contains.go
> +	}
这个判断也是不需要的，直接遍历。毕竟 Contains 里面也能正确处理

2022-09-03 08:05 UTC, flycash commented on slice/contains.go
> +	}
类似地，这个也不需要

2022-09-03 08:05 UTC, flycash commented on slice/diff.go
>  func Diff[T comparable](src, dst []T) []T {
这个用 map。

2022-09-03 08:05 UTC, flycash commented on slice/diff.go
>  func Diff[T comparable](src, dst []T) []T {
如果你要是做得比较仔细的话，你可以在 src 和 dst 很大的时候用 map，在比较小的时候使用双重循环。因为在切片数据量不多的时候，map 并不会快很多，但是会引入额外内存分配

2022-09-07 16:13 UTC, flycash commented
@penbox 你还改吗？不改的话我后面自己来实现，这个合并请求我就关了

2022-09-08 09:21 UTC, penbox commented
要改要改，我这两天补作业去了，我今天晚上就把这块改完

2022-09-08 16:04 UTC, penbox commented
大明老师Diff和Contain都实现好了，如果我想把剩余的slice方法都实现一遍，是等你关闭这个PR，还是我直接在这个PR上继续提交？

2022-09-09 06:10 UTC, penbox commented
一口气把所有slice方法都实现了，辛苦大明老师帮我看看

2022-09-09 07:29 UTC, flycash commented
好的，你的合并请求和  .CHANGELOG.md 冲突了，解决一下

2022-09-09 07:49 UTC, flycash requested changes

2022-09-09 07:49 UTC, flycash commented on slice/contains.go
> +	for _, val := range dst {
ContainsAny 和 ContainsAll 都应该用 map 来实现（Contains 不用）。你应该注意到，就是为什么我有些地方泛型约束用 any，有些用 comparable。那是我希望，在 comparable 的地方用 map。

在 ContainsAny 和 ContainsAll 这里你就应该用 map。目前你的实现是双重循环，但是用 map 就变成了两次遍历，所以时间要快很多

2022-09-09 07:49 UTC, flycash commented on slice/diff.go
> +	for i := 0; i < len(src); i++ {
这里是没有去重？

2022-09-09 07:49 UTC, flycash commented on slice/index.go
> +	fd := make([]int, 0)
这里好几个地方你都创建了 0 容量的切片，那么但凡找到了元素，你都要引起扩容。所以实际上你还是需要在这里考虑预估容量。

比如说 IndexAll 这个场景下，极端情况下就是整个 src 的元素都等于 dst，那么你创建一个和 src 一样容量的，肯定不会引起扩容。但是问题又在于，如果 src 很大，但是和 dst 相等的元素又很少的情况下，直接按照 src 的容量来创建，是不合适的。

因此你需要决策你这里怎么预估容量

2022-09-09 10:06 UTC, penbox commented on slice/index.go
> +	fd := make([]int, 0)
大明老师，关于slice初始容量的问题，你看由0固定调整为8怎么样。我是这样考虑的：
slice的扩容次数是一个对数曲线，随着slice容量的变大，扩容次数会越来越少。
初期容量：0->8，会触发0->1 1->2 2->4 4->8一共4次扩容，扩容次数比较频繁。
反过来8这个容量，占用的内存也比较小，即时不满8也不会浪费很多空间。

2022-09-09 15:26 UTC, flycash commented
感谢你的代码，我抄了你的 map 代码。因为有人急着用，所以我自己先搞了。后面你可以在我的代码基础上优化容量预估的问题 #83

2022-09-09 15:26 UTC, closed without merging