实现union、index、intersect方法，equal添加异常捕获
gotomicro/ekit pull request #74
Opened 2022-09-05 12:31 UTC by aristletl

2022-09-05 13:03 UTC, longyue0521 commented on slice/types.go
> +	isPanic = false
这里的isPanic=false可以去掉,将上面isPanic=true移动到defer中if 判断内即可.命名返回值变量默认值也为其类型的零值.

2022-09-05 13:10 UTC, longyue0521 commented on slice/index_test.go
> +		},
再补充一个包含两个dst,返回第一个dst下标的测试用例

2022-09-05 13:13 UTC, longyue0521 commented on slice/index_test.go
> +
补充包含两个dst,返回最后那个dst下标的测试用例

2022-09-05 13:13 UTC, longyue0521 commented on slice/index_test.go
> +		},
同上

2022-09-05 13:26 UTC, longyue0521 commented on slice/index_test.go
> +	//Output: 2
你可能需要调整一下IDE的配置,让//与Output之间要有一个空格,保存时自动格式化注释.这里只是以这个为例子不是说这里有错,否者deepsource不会过这是我踩过的坑.

2022-09-05 13:36 UTC, longyue0521 commented on slice/index.go
> +			return ans
这里用显示返回nil替换return ans与你下方IntersectByFunc中处理逻辑保持一致

2022-09-05 13:43 UTC, longyue0521 commented on slice/intersect.go
>  func IntersectByFunc[T any](src []T, dst []T, equal EqualFunc[T]) []T {
IntersectByFunc与Intersect的逻辑语义不相符. 因为Intersect内部使用集合数据结构(map的key)天然处理了src与dst中各自有重复元素的情况而IntersectByFunc并未处理这种情况.
src = [1, 1, 2, 3], dst = [2, 3, 4, 4] Intersect = [2, 3] IntersectByFunc=[2, 3], src与dst都有重复,但重复元素不在交集中
src = [1, 2, 3, 2], dst = [2, 3] Intersect = [2, 3] IntersectByFunc=[2,3,2], src/dst其中之一或者都有重复,重复在交集中

2022-09-05 13:58 UTC, longyue0521 requested changes

2022-09-05 13:58 UTC, longyue0521 commented on slice/intersect_test.go
> +		},
添加一个“only dst nil"测试用例

2022-09-05 13:58 UTC, longyue0521 commented on slice/intersect_test.go
> +		},
添加一个"src equals/same to dst" src=dst = []int{1}测试用例,体现两重含义——src与dst完全相同,交集为1个元素

2022-09-05 13:58 UTC, longyue0521 commented on slice/intersect_test.go
> +		},
添加"only dst nil"测试用例

2022-09-05 13:58 UTC, longyue0521 commented on slice/intersect_test.go
> +		},
添加"src equals/same to dst" src=dst=[]int{1}, 体现两重含义——src与dst元素相同,交集为1个元素

2022-09-05 14:24 UTC, longyue0521 requested changes

2022-09-05 14:24 UTC, longyue0521 commented on slice/union.go
> +	result := src
对于指针类型或其内部含有指针的入参一个基本原则是不要在函数内部对其进行修改.

src在调用完Union后可能还有其他用途,可以使用copy函数将src拷贝一份给result.也可以考虑下方这种实现方式:

```go
set := map[T]struct{}{}
for _, v := range src {
    set[v] = struct{}{}
}
for _, v := range dst {
    set[v] = struct{}{}
}
result := make([]T, 0, len(set))
for k := range set {
     result = append(result, k)
}
return result
```
这段伪代码可以干掉if len(src) == 0 && len(dst) == 0 这个判断,同时可以按需创建result

2022-09-05 14:24 UTC, longyue0521 commented on slice/union.go
> +	result := src
此处问题同上, result与src指向同一个底层数组的问题.

Union与UnionByFunc逻辑语义不同的问题——src和/或dst中有重复元素的问题. 
src = [1, 1, 2, 3] dst = [2, 3, 4, 4] Union=[1, 2, 3, 4] UnionByFunc=[1, 1, 2, 3, 4, 4]

2022-09-05 14:24 UTC, longyue0521 commented on slice/union_test.go
> +		},
添加"only dst nil"测试用例

2022-09-05 14:24 UTC, longyue0521 commented on slice/union_test.go
> +		{
添加"src equals/same to dst" src=dst=[]int{1}测试用例

2022-09-05 14:24 UTC, longyue0521 commented on slice/union_test.go
> +		},
添加"only dst nil"测试用例

2022-09-05 14:24 UTC, longyue0521 commented on slice/union_test.go
> +		{
添加"src equals/same to dst" src=dst=[]int{1}测试用例

2022-09-06 16:25 UTC, longyue0521 requested changes

2022-09-06 16:25 UTC, longyue0521 commented on slice/union.go
> +	dstSet := map[any]struct{}{}
any表示T可能不是comparable的即不能作为map的key来使用,比如T为[]int

2022-09-06 16:25 UTC, longyue0521 commented on slice/intersect.go
> +	dstMap := map[any]int{}
any表示T可能不是comparable的即不能作为map的key来使用,比如T为[]int, 通过EqualFunc来将[]int当作一个元素比较

2022-09-06 16:40 UTC, longyue0521 requested changes

2022-09-06 16:40 UTC, longyue0521 commented on slice/intersect.go
> +		if num := srcMap[v]; num > 0 {
这里还是有问题,src = [1, 2, 3, 2], dst = [2, 2, 3]

2022-09-06 16:40 UTC, longyue0521 commented on slice/union_test.go
> +		{
别忘添加测试用例

2022-09-06 16:40 UTC, longyue0521 commented on slice/union_test.go
> +		{
别忘添加测试用例

2022-09-07 06:33 UTC, flycash commented on slice/types.go
> +func (e EqualFunc[any]) safeEqual(src, dst any) (isPanic bool, result bool) {
我对这个 safeEqual 稍微有一点疑虑，即我认为用户在使用这个 EqualFunc 的时候需要自己去管 panic 的问题。比较关键的理由就是如果我们管的话，我们不知道怎么管。比如说在这个实现里面，我们试图输出一个错误信息，但是这不一定非常契合用户自己的需求。所以在我想来，我们应该让用户去处理 panic 的事情。

意味着我们不需要这个 safeEqual 方法，直接使用 EqualFunc。

2022-09-07 06:50 UTC, flycash requested changes

2022-09-07 06:50 UTC, flycash commented on slice/index.go
> +	var ans []int
这种要不要考虑说计算一个预期的容量。如说在 src 很小的时候，我们就直接创建一个和 src 一样大的；如果 src 比较大，我们就创建一个它的 1/2 或者 1/3的。我们可以有一个基本的假设，就是 dst 在 src 中是比较稀疏的，所以我可以用 1/3 或者 1/4 的容量来初始化最终结果。
直接 append 的话，可能中间会触发多次扩容。
这方面我们可以设计一个 benchmark 测试来试试效果

2022-09-07 06:50 UTC, flycash commented on slice/index.go
> +	var ans []int
```go
func TestSlice(t *testing.T) {
	var s []int
	for i := 0; i < 10; i++ {
		s = append(s, i)
		fmt.Println(cap(s))
	}
	fmt.Println(s)
}
```
它最终输出的容量是：
```go
1
2
4
4
8
8
8
8
16
16
[0 1 2 3 4 5 6 7 8 9]
```
中间经过了多次扩容。

2022-09-07 06:50 UTC, flycash commented on slice/index.go
> +	var ans []int
我平时观察到一个现象，就是如果我们分配内存的话，需要的内存大小对性能影响不大，比如说我们分配一个 10 容量和 20 容量的 []int，性能基本一样。触发分配内存本身，影响比较大。所以在预估容量的时候，稍微往大里面预估有点，其实影响不大——当然，浪费内存是肯定。不过在元素不大的情况下，可能也就是多浪费几十个字节，并没太大关系。

2022-09-07 11:53 UTC, aristletl commented on slice/types.go
> +func (e EqualFunc[any]) safeEqual(src, dst any) (isPanic bool, result bool) {
我现在有些疑问，那什么时候需要我们进行兜底，什么时候不需要呢？是对于那些有用户自行实现的回调都不需要兜底吗

2022-09-07 12:13 UTC, aristletl commented on slice/intersect.go
> +		if num := srcMap[v]; num > 0 {
这里我纠结了很久，我是这么想的，这个函数用于求两个数组的公共部分，他们两个的公共部分有重复元素的话，也是他们公共的一部分，重复元素不应该被去掉

2022-09-10 10:41 UTC, flycash commented
#83 可以在这个基础上做优化。我这两天要发布新版本了，就不等了

2022-09-10 10:41 UTC, closed without merging