Wyz
gotomicro/ekit pull request #75
Opened 2022-09-06 02:54 UTC by TopWay2Hogwarts

完成copier，并使用LongYue的test作一定的修复。
1. 基准测试优于LongYue，主要在内存分配方面，耗时由于CPU不同，虽然快但尚不具备说服力
2. 支持多重指针
3. 和LongYue不同，子结构体类型、字段必须严格相同，才认为需要匹配，即便内部结构完全一样
4. 存在问题：
    (1)  错误字段的匹配，目前大多采取忽略的方法，看了历史的提交后，发现需要修改
    (2) 目前内部存在两个全局的Map，后面考虑将它们提供给使用者创建
    (3) 对于slice、Map等特殊结构，暂时只浅拷贝
    (4) 内存分配方面，struct_helper的内部结构只是凭感觉写的，尚未比较是直接存 filed offset还是存当前结构更好

2022-09-06 07:12 UTC, longyue0521 commented
感谢你的PR,当前实现不是我实现的而是 @hhh111119 ,我只是在 #45 留言澄清需求. 你可以先看看我刚提的issue #76 说说你的想法.

2022-09-06 08:16 UTC, longyue0521 requested changes

2022-09-06 08:16 UTC, longyue0521 commented on bean/copier/reflect_copier.go
> +type structFieldMap map[string][]int
这个变量要表示的是src与dst Field索引的映射关系,fieldIndexMapping或许更好

2022-09-06 08:16 UTC, longyue0521 commented on bean/copier/reflect_copier.go
> +			switch srcVal.Type().Kind() {
这里switch条件应该是srcVal.Field(i).Kind()

2022-09-06 08:16 UTC, longyue0521 commented on bean/copier/reflect_copier.go
> +		if srcVal.Pointer() != 0 {
0改为reflect.Invalid

2022-09-06 08:54 UTC, longyue0521 requested changes

2022-09-06 08:54 UTC, longyue0521 commented on bean/copier/reflect_copier.go
> +			if subSrcValue.Pointer() != 0 {
魔数0改为reflect.Invalid

2022-09-06 08:54 UTC, longyue0521 commented on bean/copier/struct_helper.go
> +	return 1<<kind&deepCopyKind > 0
使用switch kind, case reflect.Chan,reflect.Array,reflect.Map, reflect.Slice 代替

2022-09-06 08:54 UTC, longyue0521 commented on bean/copier/struct_helper.go
> +var structOffsetsMapGlobal = make(map[string]*structOffsets)
全局变量在并发/并行读写的情况下会有data race问题,比如go协程1在第83行写,而go协程2在第31行读或第121行读

建议去掉structOffsetsMapGlobal

2022-09-06 09:14 UTC, longyue0521 commented
你先根据下方DeepSource:Go后面的Details中的错误提示修复一下代码问题. 再看看我提的issue #76 重新思考一下你的Benchmark,有什么问题欢迎讨论

2022-09-07 16:02 UTC, flycash commented
> 3. 和LongYue不同，子结构体类型、字段必须严格相同，才认为需要匹配，即便内部结构完全一样
这一条其实值得商榷的问题。一般来说在 DTO 里面有的引用，在 BO 里面也会有。例如：
```go
type UserDTO struct {
    Address AddressDTO
}
```
type UserBO struct {
    Address UserBO
}
```
在严格分层的应用中，基本可以认为，DTO 有什么，BO 就有什么，PO 里面也会有什么。只不过 PO 如果不使用关联关系的会，结构会有所差异。
所以实际上，我们是需要支持这种形态，也就是字段类型不同，但是还是要互相转化。

但是你的说法是有道理的。实际上这也可以认为是一个字段类型转换，我在原始的 issue #45 里面就提到过，应该要考虑类型之间的转换关系。

所以我们可以提供一个最基础的实现，就是非常严格的匹配，例如 int 一定要和 int 匹配，和 *int, **int 都不匹配，也就是不会复制，并且返回错误。任何不符合这个严格匹配规则的，都返回错误。

我不建议在这种工具类里面使用 panic，panic 按照我的预期在应用启动成功之后，就应该谨慎使用了，这种时候我们应该优先考虑 error。

而后我们提供一些选项：
- 在字段级别，允许用户指定类型转换，例如 int 匹配 *int, **int，AddressBO 转 AddressDTO；
- 允许完全异构的字段转化，例如 string 转 int64
- 在类型不匹配的时候，可以调过这个字段

2022-09-07 16:05 UTC, flycash requested changes

2022-09-07 16:05 UTC, flycash commented on bean/copier/reflect_copier.go
> +	if offsetMap, ok := structFieldMapBuffer[mapName]; ok {
并发是一个问题，另外一个问题是我们完全没有必要缓存这个。
我们的预期是，用户是应该创建一个 Copier 之后就一直使用这个 Copier，用到天荒地老；而不是每次使用都创建出来一个新的。因此没有必要在这里缓存。

这其实也是一种设计差异。你们应该注意到在一些 ORM 框架里面， ORM 本身是一种即开即用的；但是这种设计我是不太赞成的，诸如 ORM，Client，Server 类，也包括这种 Copier，它的生命周期是伴随整个应用的。

所以之前我们设计 benchmark 的时候没有设计那种一次性使用的，因为预期中，用户不能这么用。用户如果要这么用，干嘛不直接使用 CopyTo 包方法呢？

2022-09-07 16:05 UTC, flycash commented on bean/copier/reflect_copier.go
> +	if offsetMap, ok := structFieldMapBuffer[mapName]; ok {
此外就是，不到逼不得已不要使用包变量，非常难测试，而且可读性不佳

2022-09-07 16:13 UTC, flycash requested changes

2022-09-07 16:13 UTC, flycash commented on bean/copier/reflect_copier_test.go
> +				src1 := &CompositeSrc2{
这里有这样一个用例，也就是现在那个实现为什么还是维持住这样一颗前缀树的原因，在那个合并请求里面，我们讨论过直接计算 map[string][]int 这种，当时我也建议了这种重构。但是它在使用指针结构，并且没有初始化的时候，会出错。例如：

```go
type Dst struct {
    S1 *Sub
    S2  Sub
}

type Src struct {
    S1 *Sub
    S2  Sub
}
```
那么如果我们执行 copier.CopyTo(src, &Dst{}) 的时候，因为 s1 是指针，没有被初始化，所以直接用 FieldIndex 是会报错的（据同学反馈）

2022-09-07 16:13 UTC, flycash commented on bean/copier/reflect_copier_test.go
> +				src1 := &CompositeSrc2{
这里我们并不能预期用户会把所有的指针字段都初始化好

2022-09-07 16:13 UTC, flycash commented on bean/copier/reflect_copier_test.go
> +				src1 := &CompositeSrc2{
你也需要加这么一个测试用例

2022-09-14 15:12 UTC, flycash commented on bean/copier/reflect_copier_test.go
> +				src1 := &CompositeSrc2{
@TopWay2Hogwarts 你需要先加这个测试用例。这个用例很关键，它直接决定了你能不能继续沿着你的思路进行下去

2022-09-20 03:23 UTC, flycash requested changes

2022-09-20 03:23 UTC, flycash commented on sqlx/encrypt.go
> +}
我觉得这个我们不需要去管，而是让用户使用足够长度的密钥。比如说32位正好的那种。

按照道理来说，密钥长度不够会影响加密的效果。

2022-09-20 03:23 UTC, flycash commented on sqlx/encrypt.go
> +func (e *EncryptColumn[T]) Scan(src any, key []byte) error {
Scan 是只有 src 作为输入的，它实现的是 Scanner 接口。所以你不能把密钥放在这里。你可以在 EncryptColumn 里面加一个字段。
另外你要看一下 Scanner 里面 src 可能的类型，它不仅仅是只能为 []byte

2022-09-20 03:23 UTC, flycash commented on sqlx/encrypt.go
> +			tmp := int64(0)
这边的处理同样可以直接对 Val 进行类型断言，不需要借助反射。这边更加要小心 nil 的问题

2022-09-20 03:23 UTC, flycash commented on sqlx/encrypt.go
> +	case reflect.Bool, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64,
在 Value 方法里面，如果是 nil 的话，就不需要进行加密了。因为也没办法加密。

所以我建议是禁止用户在这里使用任何指针

2022-09-20 03:23 UTC, flycash commented on sqlx/encrypt.go
> +			json := &JsonColumn[T]{}
这边不要借助 JsonColumn，你直接使用 json 包就可以了。

2022-09-20 03:23 UTC, flycash commented on sqlx/encrypt_test.go
> +func TestEncryptColumn_Basic(t *testing.T) {
在测试的时候，可以利用 sqlite3 来测试。相当于你构造一个输入，然后插入进去 sqlite3，然后再把它读出来（SELECT），然后看看解密后的结果是不是等于你构造的输入。

2022-09-20 03:23 UTC, flycash commented on sqlx/encrypt_test.go
> +func TestEncryptColumn_Basic(t *testing.T) {
额外考虑 Valid 为 false 的场景

2022-09-23 09:17 UTC, flycash commented
我先关了，后面你可以在已有的基础上继续修改。我还是觉得，在字段为指针的时候，这种思路是不太 OK 的。不过我们可以有一个急速实现，不允许用户使用指针。

2022-09-23 09:17 UTC, closed without merging