实现函数功能
gotomicro/ekit pull request #77
Opened 2022-09-06 14:02 UTC by jackj-ohn1

2022-09-06 15:51 UTC, longyue0521 requested changes

2022-09-06 15:51 UTC, longyue0521 commented on slice/diff.go
> +	srcMap, dstMap := setMapStruct[T](src), setMapStruct[T](dst)
src={1, 2, 3, 4}, dst={3, 4, 5} 的差集是指src-dst={1,2}即在src中但不在dst中的元素的集合
对称差集才是(src-dst)与(dst-src)的并集={1, 2, 5}

你可以添加对称差的接口及实现

2022-09-06 15:51 UTC, longyue0521 commented on slice/contains.go
> +	for i := 0; i < len(dst); i++ {
for-range slice的时候并不会占用大量内存,继续使用for-range与前后文保持一致吧

https://groups.google.com/g/golang-nuts/c/tzYlW3eijMA

2022-09-06 15:51 UTC, longyue0521 commented on slice/contains.go
> +		for j := 0; j < len(src); j++ {
同上

2022-09-06 15:51 UTC, longyue0521 commented on slice/diff.go
> +	for i := 0; i < len(dst); i++ {
同上

2022-09-06 15:51 UTC, longyue0521 commented on slice/diff.go
> +	var sameData = make([]T, 0, min(len(src), len(dst)))
intersection可能比sameData更好

2022-09-07 06:50 UTC, flycash commented
你怎么会把我的 commit 带进来……你重新切一个分支……

2022-09-07 08:51 UTC, closed without merging