slice: 支持 Diff*, Union*, SymmetricDiff*, Intersection*, Index* 方法
gotomicro/ekit pull request #83
Opened 2022-09-09 15:04 UTC by flycash

2022-09-09 15:11 UTC, flycash commented
看看我有没有漏掉你的 review，没有修改的

2022-09-09 15:12 UTC, flycash commented
同时感谢 @penbox

2022-09-09 15:36 UTC, flycash commented
容量预估和非去重的版本，以后再实现

2022-09-10 01:42 UTC, longyue0521 requested changes

2022-09-10 01:42 UTC, longyue0521 commented on slice/diff_test.go
>  	tests := []struct {
改为TestDiffSetFunc

2022-09-10 01:42 UTC, longyue0521 commented on slice/index.go
>  	return nil
与下方IndexAllFunc,没找到时的处理不一致,这里返回nil,下方IndexAllFunc返回[]T{}

2022-09-10 01:42 UTC, longyue0521 commented on slice/intersect_test.go
> +			want: []int{1, 3, 5},
TestIntersect -> TestIntersectSet

2022-09-10 01:42 UTC, longyue0521 commented on slice/intersect_test.go
> +func TestIntersectFunc(t *testing.T) {
TestIntersectFunc -> TestIntersectSetFunc

2022-09-10 01:42 UTC, longyue0521 commented on slice/map.go
> -	return []Dst{}
Map让人感觉是从src[]T 构造map, 改为Mapping或者Convert, ConvertTo怎么样?

2022-09-10 01:42 UTC, longyue0521 commented on slice/map_test.go
> +func TestMap(t *testing.T) {
如果上方的Map要改,TestMap, ExampleMap也需要修改

2022-09-10 01:42 UTC, longyue0521 commented on slice/symmetric_diff.go
> +	return ret
ret需要去重, src = []int{1, 1, 2, 2, 3, 3}, dst = []int{2,2, 3, 3, 4, 4}

2022-09-10 01:42 UTC, longyue0521 commented on slice/symmetric_diff_test.go
> +func TestSymmetricDiff(t *testing.T) {
TestSymmetricDiff -> TestSymmetricDiffSet

2022-09-10 01:42 UTC, longyue0521 commented on slice/symmetric_diff_test.go
> +func TestSymmetricDiffAny(t *testing.T) {
TestSymmetricDiffSetFunc

2022-09-10 01:42 UTC, longyue0521 commented on slice/union.go
>  	// 双重循环检测
注释去掉

2022-09-10 01:42 UTC, longyue0521 commented on slice/union_test.go
> -			name: "src and dst nil",
TestUnion -> TestUnionSet

2022-09-10 01:42 UTC, longyue0521 commented on slice/union_test.go
> -			name: "src and dst nil",
TestUnionAny->TestUnionSetFunc

2022-09-10 01:46 UTC, longyue0521 commented
测试用例设计的不够全面,只考虑一般情况,边界情况未考虑. 后续补全、重构吧

2022-09-10 03:20 UTC, flycash commented
改了，再看看 @longyue0521

2022-09-10 03:40 UTC, longyue0521 requested changes

2022-09-10 03:40 UTC, longyue0521 commented on slice/contains.go
> +	// 两个切片,制造两个map
注释去掉

2022-09-10 03:41 UTC, longyue0521 commented
上面未折叠的review,表示问题还在或者需要澄清

2022-09-10 03:52 UTC, longyue0521 commented on slice/symmetric_diff.go
> +	return ret
这是个bug,添加测试用例并修复

2022-09-10 03:54 UTC, flycash commented
应该都好了。nil 的那个，我改成了都返回空切片

2022-09-10 03:54 UTC, flycash commented
后面你可以点 Resolve。一般就是谁开的对话，谁来 resolve

2022-09-10 04:02 UTC, longyue0521 requested changes

2022-09-10 04:02 UTC, longyue0521 commented on slice/map.go
> -	return []Dst{}
Map让人感觉是从src[]T 构造map, 改为Mapping或者Convert, ConvertTo怎么样?

2022-09-10 04:02 UTC, longyue0521 commented on slice/map_test.go
> +func TestMap(t *testing.T) {
如果上方的Map要改,TestMap, ExampleMap也需要修改

2022-09-10 04:02 UTC, longyue0521 commented on slice/symmetric_diff.go
> +	return ret
ret需要去重, src = []int{1, 1, 2, 2, 3, 3}, dst = []int{2,2, 3, 3, 4, 4}; 添加测试用例并修复

2022-09-10 04:06 UTC, longyue0521 commented
force push对review不太友好,会丢失之前review的对话,导致只能人工对比,效率很低. 多个commit可以在合并到dev的时候压缩成一个commit并修改comment. 不使用force push时,可以在review时使用如下选项提高效率.

![review](https://user-images.githubusercontent.com/6337745/189467950-c101a51b-0445-4e2d-bd03-db750b524d34.jpg)

2022-09-10 04:16 UTC, longyue0521 commented
> 后面你可以点 Resolve。一般就是谁开的对话，谁来 resolve

这个Resolve是不是指review对话框右上角"..."里的hide->resolve

2022-09-10 08:24 UTC, flycash commented on slice/symmetric_diff.go
> +	return ret
好了

2022-09-10 08:25 UTC, flycash commented on slice/map.go
> -	return []Dst{}
这个是 map reduce API 中的 map。或者我们可以考虑有一个专门的 mapreduce 包，这样这个方法就可以重命名为 ConvertTo

2022-09-10 08:25 UTC, flycash commented on slice/map.go
> -	return []Dst{}
但是专门的 mapreduce 包看起来不是特别好，因为在其它数据结构里面也可以引入类似的 API

2022-09-10 08:26 UTC, flycash commented
![image](https://user-images.githubusercontent.com/9923838/189475386-eef267b5-6606-4ae7-8de2-643750b34446.png)

2022-09-10 08:27 UTC, flycash commented
你说的每次 force push 确实是一个问题。

从排查问题的角度来说，一个合并请求只有一个 commit id 是稍微有点帮助的。但是我发现很多人不会 rebase，以及你提到的 review 的问题，所以我觉得后面可以不做这种要求。

2022-09-10 08:29 UTC, flycash commented on slice/map.go
> -	return []Dst{}
依旧保留这个命名吧，我下一步就是要引入 reduce API。最开始我是计划在 Sum 的那个合并请求里面引入的

2022-09-10 10:39 UTC, merged

2022-09-10 12:32 UTC, longyue0521 commented
@flycash 不知道什么原因,我看到的对话框和你看到的不一样,我这没有那个按钮.

当我再次review时我能做的只是点击右侧三个点->hide->reslove comment以表示这个问题解决了.

![reslove_coversion](https://user-images.githubusercontent.com/6337745/189483507-eecbeed0-fdda-42bf-8bee-e126ff5d32dc.jpg)

2022-09-10 13:12 UTC, longyue0521 commented
> 从排查问题的角度来说，一个合并请求只有一个 commit id 是稍微有点帮助的。但是我发现很多人不会 rebase，以及你提到的 review 的问题，所以我觉得后面可以不做这种要求。

想要达到一个PR一个commit, 你在合并PR的时候可以试试[Squash and merge](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/about-pull-request-merges#squash-and-merge-your-commits)选项,将PR中的多个commit压缩成一个并[自定义最终的message](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/about-pull-request-merges#merge-message-for-a-squash-merge),应该可以达到一个PR合并到dev时就是一个commit的效果. 上面的链接中有图示,看看是不是你想要的结果. 

如果这个方案可行,PR中就可以不限制commit数了,review也能方便点

2022-09-10 13:34 UTC, longyue0521 commented
@flycash 

https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/commenting-on-a-pull-request#resolving-conversations

大意是如果PR是我开的即我是被review的人,我可以看到resolve conversation按钮, 还有就是对ekit有写权限的人能够看到.

看这个意思resolve conversation是给**被review的人**用的,修改完了点一下,相当于在对话下回复了一个”已修改“.