sqlx初步完成.
gotomicro/ekit pull request #92
Opened 2022-09-18 15:04 UTC by TopWay2Hogwarts

初步完成 sqlx的功能，还有如下工作留给明天:
1.  benchmark分析、优化
2. 错误用例的测试

存在疑虑：
由于学习、工作阶段，sql的使用较少，加密也几乎没有使用过，对于使用场景不太熟悉；所以不太清楚 #53讨论中的key应该放在哪，目前修改了接口函数，key在加、解密时都要传入。当然，如果放在结构体里应用场景更广，只需搞一个装饰器即可。

加、解密的代码基本是复制、粘贴网络上的。

PS:
copier的代码，虽说已经做好了，但修改好后还是会提的。
eorm的issue，我需要去回顾一下sql。

2022-09-20 03:40 UTC, flycash requested changes

2022-09-20 03:40 UTC, flycash commented on sqlx/encrypt.go
> +	encrypt   cipher.BlockMode
这边应该只需要一个 Key 字段，让用户设置加密的密钥。
mode 固定为使用 GCM 的话应该不再需要这两个字段了

2022-09-20 03:40 UTC, flycash commented on sqlx/encrypt.go
> +	encrypt   cipher.BlockMode
我们认为用户传入的 key 必然是一个合法的 key，也就是长度是正确的

2022-09-20 03:40 UTC, flycash commented on sqlx/encrypt.go
> +func valueToBytes[T any](relValue reflect.Value, valT *T) ([]byte, error) {
这里没有必要使用反射的，可以直接对 Val 的类型进行断言。
然后只支持：
- 基本类型
- string 和 []byte
- 结构体
我觉得不需要支持任何指针，这样可以让代码保持简单

2022-09-20 03:40 UTC, flycash commented on sqlx/encrypt.go
> +		jsonColumn := &JsonColumn[T]{
不用借助 JsonColumn，直接操作 json 库

2022-09-20 03:40 UTC, flycash commented on sqlx/encrypt.go
> +func setVal[T any](relValue reflect.Value, reader io.Reader, deData []byte, val *T) error {
这里我觉得也不需要指针，你对 Val  进行类型断言之后直接赋值就可以

2022-09-20 03:40 UTC, flycash commented on sqlx/encrypt.go
> +}
不需要我们来处理 padding。用户需要传入符合长度的 key

2022-09-20 03:40 UTC, flycash commented on encrypt_benchmark
> +ok  	github.com/gotomicro/ekit	0.429s
这个可以删掉

2022-09-20 03:40 UTC, flycash commented on sqlx/encrypt.go
> +	switch value := src.(type) {
要看 Scanner 的方法签名，还有别的类型需要考虑。

2022-09-20 03:40 UTC, flycash commented on sqlx/encrypt_test.go
> +func TestEncryptColumn_Basic(t *testing.T) {
这个测试设计得不是特别好。你可以考虑只用 sqlite3 来做测试：
```go
testCases := []struct{
    name string
    input any // 因为泛型的缘故我们这里只能使用 any
    output any
    wantErr
} {
     {
         name:"int",
        input: EncryptColumn[int]{Key: key, Val: 123, Valid true}
        output: EncryptColumn[int]{Key: key}
     }
}

fro _, tc := range testCases {
     t.Run(tc.name, func(t *testing.T) {
         res, err := db.Exec("INSERT INTO xxx", a, b, tc.input) // 构造一个DB和一张表，然后往里面插入数据
         // 检查 res 和 err
        err := db.Query("SELECT xxx FROM", tc.output)
        // 检车 err
        assert.Equal(t, tc.input, tc.output)
     })
}

```

2022-09-20 03:40 UTC, flycash commented on sqlx/encrypt_test.go
> +func TestEncryptColumn_Basic(t *testing.T) {
input 和 output 都是 EncryptColumn，但是可以使用不同的泛型参数，然后测试基本类型，string，[]byte 和结构体

2022-09-20 03:40 UTC, flycash commented on sqlx/encrypt.go
> +	encrypt   cipher.BlockMode
type EncryptColumn[T any] struct {
    Key string
    Val T
    Valid bool
}

2022-09-20 14:02 UTC, flycash reviewed
你的测试可读性实在不高，还是按照我的建议来进行一点修改吧

2022-09-20 14:02 UTC, flycash commented on sqlx/encrypt.go
> +	case map[any]any, []any, *any, uintptr:
我猜你这里是想断言所有的 map，切片和指针。那么这个 case 会让你失望了，因为在 Go 里面 map[any][any] 和 map[string]any 之类的完全是两种类型，比如说 Val 确实是 map[string]any，那么它并不会命中这个分支。
你可以留：
- 基本类型
- string
- []byte
- default
在 default 里面就用 json 了。不能转化的话，json 包本身会报错。虽然丑了一点，但是还能接受

2022-09-20 14:09 UTC, TopWay2Hogwarts commented on sqlx/encrypt_test.go
> +func TestEncryptColumn_Basic(t *testing.T) {
嗯，在构思换了，确实写的很有问题。
其他的改动也有点多，目前是固定住已有的测试用例，先把其他的改了。

2022-09-20 14:14 UTC, TopWay2Hogwarts commented on sqlx/encrypt.go
> +	encrypt   cipher.BlockMode
这两个字段主要是用来优化的。
benchmark发现耗时、内存分配主要在  aes.NewCipher([]byte(e.Key))等新建上面；
当然，如果应用场景中很少有复用的情况，就是过度设计了，目前删除了这几个字段。

2022-09-21 07:40 UTC, TopWay2Hogwarts commented on sqlx/encrypt.go
> +		return nil
实际上我是不会范型的赋值，e.Val = string(xxx)一定不对，
用断言，这样写会报错
![image](https://user-images.githubusercontent.com/88173543/191443440-b07a81f6-fe92-4af6-aabc-c03bb1d7a234.png)
即便通过点奇怪的方法通过，断言的 valT也是 e.Val的副本，并不能正确完成赋值
![image](https://user-images.githubusercontent.com/88173543/191443823-061120e5-85e8-4d1c-af8d-bf2b9abd61ee.png)
![image](https://user-images.githubusercontent.com/88173543/191443876-7848dfeb-cd44-496c-ac16-7dc3af9d22f6.png)
其他的基本类型也是一样，需要指针操作才行，反射的话感觉也没必要，不如这样。
其他的写法，俺还真不知道..........

2022-09-21 10:05 UTC, TopWay2Hogwarts commented on sqlx/encrypt_test.go
> +func TestEncryptColumn_Basic(t *testing.T) {
改好了，但还是存在最后的范型比较问题

2022-09-23 08:07 UTC, TopWay2Hogwarts commented on sqlx/encrypt.go
> +		return nil
自己SB了，取 e.Val的指针为any就好
```go
var val any = &e.Val
```

2022-09-23 08:15 UTC, flycash requested changes

2022-09-23 08:15 UTC, flycash commented on sqlx/encrypt.go
> +	if err == nil {
这个判断可以改成：
```go
e.Valid = err == nil
```
前面 err != nil 那个 if 里面不需要将 e.Valid 赋值为 false。默认初始化的时候就应该是 false。只有这里 err 为 nil 的时候才会改为 true

2022-09-23 08:15 UTC, flycash commented on sqlx/encrypt_test.go
> +func TestEncryptColumn_Sql(t *testing.T) {
把所有的类型都测试一遍。就是你在前面 switch case 里面的。加测试用例应该很容易，你一路复制粘贴下去，还是很快。

2022-09-23 08:16 UTC, flycash commented
最近忙翻了，不好意思……

2022-09-23 09:05 UTC, flycash requested changes
.DS_Store 文件和根目录下的 encrypt_branchmark 文件都不用提交。
记得在 .CHANGELOG 文件里面加上这个 PR

2022-09-26 02:09 UTC, flycash approved these changes

2022-09-26 02:12 UTC, flycash commented
<img width="400" alt="image" src="https://user-images.githubusercontent.com/9923838/192180270-387cef62-bb1e-41b8-9d54-7cd4923d2406.png">
算了，我先合并了这个，然后我在你的基础上修复这些问题。以后你要学会检查 license，以及添加 change log

2022-09-26 02:12 UTC, merged